### ISSUE TITLE
mingw-w64-x86_64-lldb Segmentation fault

### ISSUE THREAD

**Issue by hhaoao** [msys2/MINGW-packages#8868] opened 2021-06-10 01:19 UTC
What did I do wrong that the LLDB never worked properly.
I don't know what useful thing to offer.

Administrator@WIN-6HQQN44B4H7 MINGW64 ~
$ lldb --version

```bash
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Program arguments: D:\\msys64\\mingw64\\bin\\lldb.exe --version
#0 0x00007ff81d460000
#1 0x00007ff87d8535f5 (D:\msys64\mingw64\bin\liblldb.dll+0x835f5)
#2 0x00007ff87d86c9b8 (D:\msys64\mingw64\bin\liblldb.dll+0x9c9b8)
#3 0x00007ff7c416db74 (D:\msys64\mingw64\bin\lldb.exe+0xdb74)
#4 0x00007ff7c41613c1 (D:\msys64\mingw64\bin\lldb.exe+0x13c1)
#5 0x00007ff7c41614f6 (D:\msys64\mingw64\bin\lldb.exe+0x14f6)
#6 0x00007ff8c4dd7974 (C:\WINDOWS\System32\KERNEL32.DLL+0x17974)
#7 0x00007ff8c7bea2f1 (C:\WINDOWS\SYSTEM32\ntdll.dll+0x5a2f1)
Segmentation fault
```

**Comment by jeremyd2019** [comment] 2021-06-11 05:32
@mati865 emutls issue?

<details>
<summary>WinDbgX analysis</summary>

```
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************


KEY_VALUES_STRING: 1

    Key  : AV.Fault
    Value: Execute

    Key  : Analysis.CPU.mSec
    Value: 197906

    Key  : Analysis.DebugAnalysisManager
    Value: Create

    Key  : Analysis.Elapsed.mSec
    Value: 201379

    Key  : Analysis.Init.CPU.mSec
    Value: 13999

    Key  : Analysis.Init.Elapsed.mSec
    Value: 73006

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 501

    Key  : Timeline.OS.Boot.DeltaSec
    Value: 190167

    Key  : Timeline.Process.Start.DeltaSec
    Value: 72

    Key  : WER.OS.Branch
    Value: vb_release

    Key  : WER.OS.Timestamp
    Value: 2019-12-06T14:06:00Z

    Key  : WER.OS.Version
    Value: 10.0.19041.1


NTGLOBALFLAG:  470

PROCESS_BAM_CURRENT_THROTTLED: 0

PROCESS_BAM_PREVIOUS_THROTTLED: 0

APPLICATION_VERIFIER_FLAGS:  0

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007fff1ec50000
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000008
   Parameter[1]: 00007fff1ec50000
Attempt to execute non-executable address 00007fff1ec50000

FAULTING_THREAD:  00000f40

PROCESS_NAME:  lldb.exe

EXECUTE_ADDRESS: 7fff1ec50000

FAILED_INSTRUCTION_ADDRESS: 
+0
00007fff`1ec50000 ??              ???

ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

EXCEPTION_CODE_STR:  c0000005

EXCEPTION_PARAMETER1:  0000000000000008

EXCEPTION_PARAMETER2:  00007fff1ec50000

IP_ON_HEAP:  00007fff1ec50000
The fault address in not in any loaded module, please check your build's rebase
log at <releasedir>\bin\build_logs\timebuild\ntrebase.log for module which may
contain the address if it were loaded.

IP_IN_FREE_BLOCK: 7fff1ec50000

STACK_TEXT:  
000000ef`77bff2e8 00007fff`7f0435f5     : 00000000`00000008 00000201`d83b2850 000000ef`77bff380 000000ef`77bff508 : 0x00007fff`1ec50000
000000ef`77bff2f0 00007fff`7f05c9b8     : 00000000`0000001e 00000201`d83b1240 00000000`0000000d 000000ef`77bff7b0 : liblldb!UpdateBoundary+0x15
000000ef`77bff320 00007ff6`5e8cdb74     : 00000000`00000001 00000201`d8500000 00000000`00000002 00007fff`c461b44d : liblldb!InitializeWithErrorHandling+0x198
000000ef`77bff440 00007ff6`5e8c13c1     : 00000000`00000002 00000201`d83b1240 00007ff6`5e8d50b8 00000000`00000000 : lldb+0xdb74
000000ef`77bff960 00007ff6`5e8c14f6     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : lldb+0x13c1
000000ef`77bffa30 00007fff`c2f37034     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : lldb+0x14f6
000000ef`77bffa60 00007fff`c4642651     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : KERNEL32!BaseThreadInitThunk+0x14
000000ef`77bffa90 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21


STACK_COMMAND:  ~0s ; .cxr ; kb

FAULTING_SOURCE_LINE:  E:\MINGW-packages\mingw-w64-clang\src\lldb\include\lldb\Utility\ReproducerInstrumentation.h

FAULTING_SOURCE_FILE:  E:\MINGW-packages\mingw-w64-clang\src\lldb\include\lldb\Utility\ReproducerInstrumentation.h

FAULTING_SOURCE_LINE_NUMBER:  881

FAULTING_SOURCE_CODE:  
   877: 
   878:   template <typename T> friend struct replay;
   879:   void UpdateBoundary() {
   880:     if (m_local_boundary)
>  881:       g_global_boundary = false;
   882:   }
   883: 
   884: #ifdef LLDB_REPRO_INSTR_TRACE
   885:   void Log(unsigned id) {
   886:     this_thread_id() << "Recording " << id << ": " << m_pretty_func << " ("


SYMBOL_NAME:  liblldb!UpdateBoundary+15

MODULE_NAME: liblldb

IMAGE_NAME:  liblldb.dll

FAILURE_BUCKET_ID:  SOFTWARE_NX_FAULT_c0000005_liblldb.dll!UpdateBoundary

OS_VERSION:  10.0.19041.1

BUILDLAB_STR:  vb_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {b3715546-3616-a06b-9d00-d23b7b5aaea1}

Followup:     MachineOwner
---------
```
</details>

**Comment by jeremyd2019** [comment] 2021-06-11 17:23
I realized that this would have to be an emutls issue in GCC, because for mingw64 lldb is built with GCC not clang.  😱

**Comment by mati865** [comment] 2021-06-11 18:36
If the trace is correct then indeed looks like emutls/relocation issue.

**Comment by zufuliu** [comment] 2021-06-19 02:59
It seems lld-12.0.0-6 is also broken, see https://github.com/zufuliu/notepad2/actions/runs/951639414 for ucrt, x86_64 and i686 builds.
https://github.com/zufuliu/notepad2/runs/2863091346?check_suite_focus=true#step:7:203
> #0 0x00007ff7b65bef8c (C:\msys64\ucrt64\bin\ld.lld.exe+0x5ef8c)
> #1 0x00007ff7b658e915 (C:\msys64\ucrt64\bin\ld.lld.exe+0x2e915)
> #2 0x00007ff7b658fe5d (C:\msys64\ucrt64\bin\ld.lld.exe+0x2fe5d)
> #3 0x00007ff7b65921b6 (C:\msys64\ucrt64\bin\ld.lld.exe+0x321b6)
> #4 0x00007ff7b65928d6 (C:\msys64\ucrt64\bin\ld.lld.exe+0x328d6)
> #5 0x00007ff7b659d097 (C:\msys64\ucrt64\bin\ld.lld.exe+0x3d097)
> #6 0x00007ff7b656e79d (C:\msys64\ucrt64\bin\ld.lld.exe+0xe79d)
> #7 0x00007ff7b656eb04 (C:\msys64\ucrt64\bin\ld.lld.exe+0xeb04)
> #8 0x00007ff7b6569dfe (C:\msys64\ucrt64\bin\ld.lld.exe+0x9dfe)
> #9 0x00007ff7b657438f (C:\msys64\ucrt64\bin\ld.lld.exe+0x1438f)
>#10 0x00007ff7b657a2b8 (C:\msys64\ucrt64\bin\ld.lld.exe+0x1a2b8)
>#11 0x00007ff7b6729510 (C:\msys64\ucrt64\bin\ld.lld.exe+0x1c9510)
>#12 0x00007ff7b656237d (C:\msys64\ucrt64\bin\ld.lld.exe+0x237d)
>#13 0x00007ff7b691862e (C:\msys64\ucrt64\bin\ld.lld.exe+0x3b862e)
>#14 0x00007ff7b65613c1 (C:\msys64\ucrt64\bin\ld.lld.exe+0x13c1)
>#15 0x00007ff7b65614f6 (C:\msys64\ucrt64\bin\ld.lld.exe+0x14f6)
>#16 0x00007ffceac17974 (C:\Windows\System32\KERNEL32.DLL+0x17974)
>#17 0x00007ffcec04a2f1 (C:\Windows\SYSTEM32\ntdll.dll+0x5a2f1)
>clang++: error: linker command failed due to signal (use -v to see invocation)

While the 5 days ago lld-12.0.0-5 is working, see https://github.com/zufuliu/notepad2/actions/runs/934479857

**Comment by jeremyd2019** [comment] 2021-06-19 05:00
The only patch touching lld directly in 12.0.0-6 seems to be https://github.com/msys2/MINGW-packages/commit/41d7201de0d09f65538327cc852e6c4b6b96f465.  Getting a debug (or RelWithDebInfo) build can be problematic, though.

**Comment by jeremyd2019** [comment] 2021-06-19 05:30
BTW, I think this is a different issue than the original lldb one.  That had an unknown address as frame 0, and seems to be an issue with emutls/relocations in gcc (and happened in 12.0.0-5) .  This is in lld, seems to be something else, and is new in 12.0.0-6.

**Comment by zufuliu** [comment] 2021-06-19 08:58
Tested locally, with all other llvm/clang 12.0.0-6 packages but overwritten with manually downloaded (don't find a option `pacman -S` to specific the exactly version) lld-12.0.0-5-any.pkg.tar.zst , it indeed works, so a regression in lld-12.0.0-6.

**Comment by mati865** [comment] 2021-06-19 15:31
Probably the only action we can take is building clang with clang (but using bfd, libstdc++). Unless somebody can fix GCC/Binutils.

**Comment by jeremyd2019** [comment] 2021-06-19 17:44
You mean to get debug symbols?  Or to work around presumed GCC bugs?  (or both :wink:)

**Comment by jeremyd2019** [comment] 2021-06-19 18:26
> Tested locally, with all other llvm/clang 12.0.0-6 packages but overwritten with manually downloaded (don't find a option `pacman -S` to specific the exactly version) lld-12.0.0-5-any.pkg.tar.zst , it indeed works, so a regression in lld-12.0.0-6.

How hard is it to get to this stage?  Could you provide a zip of the object files/whatever inputs to lld?  This sounds quite suspiciously like the LTO patch I referenced earlier.  I could make a build of lld without that patch to test, but I think that would be pretty much the same as what you did with everything 12.0.0-6 except lld 12.0.0-5...

**Comment by zufuliu** [comment] 2021-06-20 00:40
```
git clone --depth=1 https://github.com/zufuliu/notepad2.git
cd notepad2\build\mingw
```
the build command [`CALL "build\mingw\build.bat" x86_64 Clang`](https://github.com/zufuliu/notepad2/blob/master/.github/workflows/main.yml#L280) does something like:

https://github.com/zufuliu/notepad2/blob/master/build/mingw/build.bat#L60
```
SET "PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%"
mingw32-make CLANG=1 LTO=1
```

**Comment by jeremyd2019** [comment] 2021-06-20 00:50
Cool, basically no dependencies then.  Will do some testing

**Comment by jeremyd2019** [comment] 2021-06-20 01:31
```
(ad4.1ebc): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
ld_lld+0x5ef8c:
00007ff6`f675ef8c 488b8890000000  mov     rcx,qword ptr [rax+90h] ds:00000000`00000090=????????????????
```

does not occur on clang64 prefix

**Comment by jeremyd2019** [comment] 2021-06-20 02:43
I split the lld issue to #8963 to try to avoid confusion with the lldb issue

**Comment by Mr-Rayman** [comment] 2021-06-25 12:37
I do see exactly the same issue using LLDB with CLang 12 inside a MSYS2 windows environment. Calling lldb without any arguments results in this:

 ```
MINGW64 ~
$ lldb 
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Program arguments: D:\\Dev\\Tools\\MSYS64\\mingw64\\bin\\lldb.exe --version
#0 0x00007ff855da0000
#1 0x00007ff8b61935f5 (D:\Dev\Tools\MSYS64\mingw64\bin\liblldb.dll+0x835f5)
#2 0x00007ff8b61ac9b8 (D:\Dev\Tools\MSYS64\mingw64\bin\liblldb.dll+0x9c9b8)
#3 0x00007ff7033adb74 (D:\Dev\Tools\MSYS64\mingw64\bin\lldb.exe+0xdb74)
#4 0x00007ff7033a13c1 (D:\Dev\Tools\MSYS64\mingw64\bin\lldb.exe+0x13c1)
#5 0x00007ff7033a14f6 (D:\Dev\Tools\MSYS64\mingw64\bin\lldb.exe+0x14f6)
#6 0x00007ff9074b7034 (C:\WINDOWS\System32\KERNEL32.DLL+0x17034)
#7 0x00007ff907622651 (C:\WINDOWS\SYSTEM32\ntdll.dll+0x52651)
Segmentation fault

```

**Comment by jeremyd2019** [comment] 2021-06-26 02:40
@lhmouse I was advised to loop you in on what appears to be a GCC emutls issue.  Any ideas on how to further debug this would be appreciated.

**Comment by lhmouse** [comment] 2021-06-26 04:08
I haven't dug too much into emutls. AFAICT it's basically allocation-on-demand, which is initialized to either zeros or a templ(ate) which should points to static memory. Perhaps we should have a look at [the source](https://github.com/gcc-mirror/gcc/blob/master/libgcc/emutls.c).

The `__emutls_object` struct is a static descriptor, which GCC generates for each `__thread` object. When such an object is accessed, GCC emits a call to `__emutls_get_address()`, passing the descriptor as its only argument. This function checks whether `offset` is zero. If it is zero, a unique, auto-increment index is allocated and assigned to it. This index denotes the offset in the thread-local pointer array of all `__thread` objects for each individual thread. A thread-local object is allocated on demand, and returned.

**Comment by jeremyd2019** [comment] 2021-06-26 04:16
What appears to have happened here (and it's been a bit since I looked at this so it's a little fuzzy) is that the call to `__emutls_get_address` that GCC emitted somehow wound up turning into a call to an invalid address.  Previously when that happened it turned out to be due to an improper relocation type, essentially a 32-bit relative call to something that is more than +/- 31 bits away after ASLR gets done with it.

**Comment by lhmouse** [comment] 2021-06-26 09:12
might be an LTO bug I think.

**Comment by mati865** [comment] 2021-06-26 11:08
LLVM is built without LTO.

**Comment by Mr-Rayman** [comment] 2021-08-20 11:13
Just a follow up, the bug still remains in the current version:

```
clang version 12.0.1
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: D:/Dev/Tools/MSYS64/mingw64/bin

$ lldb
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Program arguments: D:\\Dev\\Tools\\MSYS64\\mingw64\\bin\\lldb.exe
#0 0x00007ffe8edd0000
#1 0x00007ffeef1c35f5 (D:\Dev\Tools\MSYS64\mingw64\bin\liblldb.dll+0x835f5)
#2 0x00007ffeef1dc9b8 (D:\Dev\Tools\MSYS64\mingw64\bin\liblldb.dll+0x9c9b8)
#3 0x00007ff73f3bdb04 (D:\Dev\Tools\MSYS64\mingw64\bin\lldb.exe+0xdb04)
#4 0x00007ff73f3b13b1 (D:\Dev\Tools\MSYS64\mingw64\bin\lldb.exe+0x13b1)
#5 0x00007ff73f3b14e6 (D:\Dev\Tools\MSYS64\mingw64\bin\lldb.exe+0x14e6)
#6 0x00007fff3a987034 (C:\WINDOWS\System32\KERNEL32.DLL+0x17034)
#7 0x00007fff3b782651 (C:\WINDOWS\SYSTEM32\ntdll.dll+0x52651)
Segmentation fault
```

Is there any information that I can provide to help solving this issue?

**Comment by silverqx** [comment] 2021-10-03 10:35
UCRT64 env. has the same problem

**Comment by lhmouse** [comment] 2021-10-03 17:04
@mstorsjo Do you have ideas on this?

**Comment by mstorsjo** [comment] 2021-10-03 18:25
No ideas offhand, but it’d be good to know exactly which TLS variable is causing the issue, if that’s the root cause.

So if I understand it correctly, this happens when lldb is built with gcc (in the mingw64 and ucrt64 msys2 environments) but not when built with native tls (in the clang64 environment - or do you force emutls there too?). Can someone pinpoint where the crash happens, either by running lldb in gdb, or just add printf statements to narrow down where it happens? (Printfs might need fflush to be accurate when debugging crashes.)

Without knowing what/where, there’s too many potential problems with TLS that I won’t try to guess what it could be here…

**Comment by silverqx** [comment] 2021-10-03 18:29
It crashes with simple `lldb --version`, `lldb --help` works good.

> Can someone pinpoint where the crash happens, either by running lldb in gdb, or just add printf statements to narrow down where it happens? 

This is too much for me, I'm not capable to do this, sry

**Comment by jeremyd2019** [comment] 2021-10-03 19:35
I thought I had a backtrace on this... I guess it was only WinDbgX not gdb, but it gives a bit of a hint:
```
FAULTING_SOURCE_CODE:  
   877: 
   878:   template <typename T> friend struct replay;
   879:   void UpdateBoundary() {
   880:     if (m_local_boundary)
>  881:       g_global_boundary = false;
   882:   }
   883: 
   884: #ifdef LLDB_REPRO_INSTR_TRACE
   885:   void Log(unsigned id) {
   886:     this_thread_id() << "Recording " << id << ": " << m_pretty_func << " ("
```

**Comment by mstorsjo** [comment] 2021-10-03 20:42
Hmm, ok, thanks. So TLS variables referenced in headers is a bit trickier case than if the variable is static within one object file (and you use an accessor method for getting the address of the current thread's copy of it), but I don't remember a specific bug in that area right now either.

Is it a case where the caller (which inlines `UpdateBounary()`) is in e.g. lldb*.exe while the `g_global_boundary` variable resides in libLLDB.dll? That would explain it, as cross-DLL TLS variables are really tricky (but native TLS doesn't support that case at all, so then it wouldn't even build correctly with native TLS as in my builds).

Other than that, I don't have much more to add, than looking at the compiler assembly output for the function that crashes (in the location where it's called/inlined), the relocations for that section and what it looks like after linking.

**Comment by mati865** [comment] 2021-10-03 20:58
> but not when built with native tls (in the clang64 environment - or do you force emutls there too?)

Correct, it uses native TLS. Emutls is forced only in GCC based environments.

**Comment by jeremyd2019** [comment] 2021-10-08 04:44
It looks like that function is in a header, so is in a COMDAT section in multiple object files:
```
1023 .text$_ZN12lldb_private5repro8Recorder12RecordResultIRN4lldb7SBErrorEEET_OS6_b 00000100  0000000000000000  0000000000000000  0004aee8  2**4
                  CONTENTS, ALLOC, LOAD, RELOC, READONLY, CODE, LINK_ONCE_DISCARD (COMDAT _ZN12lldb_private5repro8Recorder12RecordResultIRN4lldb7SBErrorEEET_OS6_b 1243)
1024 .xdata$_ZN12lldb_private5repro8Recorder12RecordResultIRN4lldb7SBErrorEEET_OS6_b 0000000c  0000000000000000  0000000000000000  0004afe8  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA, LINK_ONCE_DISCARD
1025 .pdata$_ZN12lldb_private5repro8Recorder12RecordResultIRN4lldb7SBErrorEEET_OS6_b 0000000c  0000000000000000  0000000000000000  0004aff4  2**2
                  CONTENTS, ALLOC, LOAD, RELOC, READONLY, DATA, LINK_ONCE_DISCARD
```

Disassembly with relocations:
```
$ objdump -r --disassemble=_ZN12lldb_private5repro8Recorder12RecordResultIRN4lldb7SBErrorEEET_OS6_b source/API/CMakeFiles/liblldb.dir/SBDebugger.cpp.obj
...
Disassembly of section .text$_ZN12lldb_private5repro8Recorder12RecordResultIRN4lldb7SBErrorEEET_OS6_b:

0000000000000000 <_ZN12lldb_private5repro8Recorder12RecordResultIRN4lldb7SBErrorEEET_OS6_b>:
   0:   57                      push   %rdi
   1:   56                      push   %rsi
   2:   53                      push   %rbx
   3:   48 83 ec 40             sub    $0x40,%rsp
   7:   48 89 cb                mov    %rcx,%rbx
   a:   48 89 d6                mov    %rdx,%rsi
   d:   45 84 c0                test   %r8b,%r8b
  10:   74 26                   je     38 <_ZN12lldb_private5repro8Recorder12RecordResultIRN4lldb7SBErrorEEET_OS6_b+0x38>
  12:   80 79 38 00             cmpb   $0x0,0x38(%rcx)
  16:   74 20                   je     38 <_ZN12lldb_private5repro8Recorder12RecordResultIRN4lldb7SBErrorEEET_OS6_b+0x38>
  18:   48 8d 05 00 00 00 00    lea    0x0(%rip),%rax        # 1f <_ZN12lldb_private5repro8Recorder12RecordResultIRN4lldb7SBErrorEEET_OS6_b+0x1f>
                        1b: IMAGE_REL_AMD64_REL32       _ZTHN12lldb_private5repro8Recorder17g_global_boundaryE
  1f:   48 85 c0                test   %rax,%rax
  22:   74 05                   je     29 <_ZN12lldb_private5repro8Recorder12RecordResultIRN4lldb7SBErrorEEET_OS6_b+0x29>
  24:   e8 00 00 00 00          call   29 <_ZN12lldb_private5repro8Recorder12RecordResultIRN4lldb7SBErrorEEET_OS6_b+0x29>
                        25: IMAGE_REL_AMD64_REL32       _ZTHN12lldb_private5repro8Recorder17g_global_boundaryE
  29:   48 8b 0d 00 00 00 00    mov    0x0(%rip),%rcx        # 30 <_ZN12lldb_private5repro8Recorder12RecordResultIRN4lldb7SBErrorEEET_OS6_b+0x30>
                        2c: IMAGE_REL_AMD64_REL32       .refptr.__emutls_v._ZN12lldb_private5repro8Recorder17g_global_boundaryE
  30:   e8 00 00 00 00          call   35 <_ZN12lldb_private5repro8Recorder12RecordResultIRN4lldb7SBErrorEEET_OS6_b+0x35>
                        31: IMAGE_REL_AMD64_REL32       __emutls_get_address
  35:   c6 00 00                movb   $0x0,(%rax)
  38:   48 83 3b 00             cmpq   $0x0,(%rbx)
  3c:   74 06                   je     44 <_ZN12lldb_private5repro8Recorder12RecordResultIRN4lldb7SBErrorEEET_OS6_b+0x44>
  3e:   80 7b 38 00             cmpb   $0x0,0x38(%rbx)
  42:   75 0b                   jne    4f <_ZN12lldb_private5repro8Recorder12RecordResultIRN4lldb7SBErrorEEET_OS6_b+0x4f>
  44:   48 89 f0                mov    %rsi,%rax
  47:   48 83 c4 40             add    $0x40,%rsp
  4b:   5b                      pop    %rbx
  4c:   5e                      pop    %rsi
  4d:   5f                      pop    %rdi
  4e:   c3                      ret
  4f:   48 8b 0d 00 00 00 00    mov    0x0(%rip),%rcx        # 56 <_ZN12lldb_private5repro8Recorder12RecordResultIRN4lldb7SBErrorEEET_OS6_b+0x56>
                        52: IMAGE_REL_AMD64_REL32       .refptr._ZN12lldb_private5repro8Recorder7g_mutexE
  56:   48 89 4c 24 30          mov    %rcx,0x30(%rsp)
...
```

**Comment by mstorsjo** [comment] 2021-10-08 05:05
Can you map the disassembly back to the compiler assembly output for an object file containing the function?

**Comment by jeremyd2019** [comment] 2021-10-08 05:06
How would I do that?

**Comment by jeremyd2019** [comment] 2021-10-08 05:35
I've started rebuilding with MSYS Makefiles generator in light of that cmake bug/feature request that has never been implemented.

**Comment by jeremyd2019** [comment] 2021-10-08 06:32
Also like https://sourceware.org/bugzilla/show_bug.cgi?id=26757 in that it involves TLS in that whole thing.

**Comment by mstorsjo** [comment] 2021-10-08 08:21
> How would I do that? (I have LLDB configured with Ninja, if that matters, ie something like `make something.s` for ninja, https://public.kitware.com/Bug/view.php?id=13839)

I usually do `rm file.obj; ninja -v file.obj`, then copy-paste the command and replace the `-c` option (and `-o`) with `-S`. Having a build system feature would be neat though.

**Comment by jeremyd2019** [comment] 2021-10-08 18:52
> You can try https://martin.st/temp/0001-WIP-lldb-Make-the-thread_local-g_global_boundary-acc.patch, which moves this variable into a `static thread_local` inside one single .cpp only, which should make the codegen for the variable much more straightforward.

This patch fixed `lldb --version` for me, and I can run it and get the prompt too.

**Comment by jeremyd2019** [comment] 2021-10-14 02:03
@mstorsjo do you plan to send your patch upstream, or should it be classed here as "not meant to upstream, for compatibility with GCC only"?

**Comment by mstorsjo** [comment] 2021-10-14 05:50
> @mstorsjo do you plan to send your patch upstream, or should it be classed here as "not meant to upstream, for compatibility with GCC only"?

Not sure, because the code is quite correct as is, and the fact that it fixes something shows that it's a toolchain bug in GCC/binutils. Too bad that it wasn't reproducible with my minimal testcase though.

**Comment by silverqx** [comment] 2021-10-14 08:59
> Ok, that was quick

Quick? Super quick 😀

**Closed** 2021-10-16 04:01 UTC
Labels: GCC
