### ISSUE TITLE
[texlive-core] msys2 binary needs a recompile to match the latest zlib version

### ISSUE THREAD

**Issue by qazmko1029** [msys2/MINGW-packages#20349] opened 2024-03-15 11:35 UTC
### Description / Steps to reproduce the issue

1. pacman -S mingw-w64-x86_64-texlive-latex-recommended
2. run "fmtutil-user"

### Expected behavior

it works

### Actual behavior

PANIC: unprotected error in call to Lua API (zlib library version does not match - header: 1.3, library: 1.3.1)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment] 2024-03-15 12:53
Duplicate of #19981

**Closed by Biswa96** 2024-03-15 12:53 UTC
Labels: bug
