### ISSUE TITLE
RE: error messages after installing/upgrading/removing adwaita-icon-theme

### ISSUE THREAD

**Issue by RadSuit** [msys2/MINGW-packages#10507] opened 2022-01-09 01:54 UTC
This is similar to another error that was already reported by @MehdiChinoune #9952

I tried installing build dependencies for GIMP plugin development for clang. mingw-w64-clang-x86_64-adwaita-icon-theme was the faulting package for me when initially installing it. The error I got was:
error: command (/usr/bin/bash /usr/bin/bash -c . /tmp/alpm_bbf87v/.INSTALL; post_install 41.0-1 ) failed to execute correctly

However, it doesn't reappear upon reinstalling it. So I guess this issue isn't as critical as the one @MehdiChinoune had. It just caught my attention that it threw out an error when installing it alongside the other packages for GIMP. Also, I don't want to uninstall and install it again because it might break a package that depends on it. So I haven't tested it again from a clean install.

**Comment by raedrizqie** [comment] 2022-01-09 03:07
this error also happens on every GHA

**Comment by RadSuit** [comment] 2022-01-09 05:20
Oh, okay, I didn't know if it was specific to the clang shell or not. Well, it happened when installing the GIMP packages for MINGW64 just now. I've switched to MINGW64 because there's a script that only works with the MINGW64 libraries. I've changed the title now, thanks.

**Comment by raedrizqie** [comment] 2022-01-09 05:30
from theme-${MSYSTEM}.install:
```
post_install() {
  [[ -f ${MINGW_INSTALL}/bin/gtk-update-icon-cache.exe ]] && {
    ${MINGW_INSTALL}/bin/gtk-update-icon-cache -q -t -f ${MINGW_INSTALL}/share/icons/Adwaita
  }
  [[ -f ${MINGW_INSTALL}/bin/gtk-update-icon-cache-3.0.exe ]] && {
    ${MINGW_INSTALL}/bin/gtk-update-icon-cache-3.0 -q -t -f ${MINGW_INSTALL}/share/icons/Adwaita
  }
}
```
there is no `gtk-update-icon-cache{-3.0}.exe` in gtk3. it is only available for gtk2..

**Comment by RadSuit** [comment] 2022-01-09 05:47
oh, so I guess I'm seeing this because it can only see gtk3 before gtk2 is installed later. Is that right? (bit a of a noob to this here).

**Comment by jeremyd2019** [comment] 2022-01-09 06:07
So it's just that the function returns non-zero, so pacman *thinks* it failed?  Maybe it would be better to use `if`s (or is that just for `set -e` issues, and it really needs an explicit `return 0`)?

**Comment by MehdiChinoune** [comment] 2022-01-09 06:09
> from theme-${MSYSTEM}.install:
> 
> ```
> post_install() {
>   [[ -f ${MINGW_INSTALL}/bin/gtk-update-icon-cache.exe ]] && {
>     ${MINGW_INSTALL}/bin/gtk-update-icon-cache -q -t -f ${MINGW_INSTALL}/share/icons/Adwaita
>   }
>   [[ -f ${MINGW_INSTALL}/bin/gtk-update-icon-cache-3.0.exe ]] && {
>     ${MINGW_INSTALL}/bin/gtk-update-icon-cache-3.0 -q -t -f ${MINGW_INSTALL}/share/icons/Adwaita
>   }
> }
> ```
> 
> there is no `gtk-update-icon-cache{-3.0}.exe` in gtk3. it is only available for gtk2..

```
$ pacman -Fx gtk-update-icon-cache
mingw64/mingw-w64-x86_64-gtk-update-icon-cache 3.24.30-5
    mingw64/bin/gtk-update-icon-cache-3.0.exe
    mingw64/share/man/man1/gtk-update-icon-cache-3.0.1.gz
    usr/share/libalpm/hooks/mingw-w64-x86_64-gtk-update-icon-cache.hook
    usr/share/libalpm/scripts/mingw-w64-x86_64-gtk-update-icon-cache.script
mingw64/mingw-w64-x86_64-gtk2 2.24.33-4
    mingw64/bin/gtk-update-icon-cache.exe
```

**Comment by raedrizqie** [comment] 2022-01-09 07:47
adwaita-icon-theme doesn't pull in gtk-update-icon-cache... and gtk3 is only mark as build dependency for it..

**Comment by Biswa96** [comment] 2023-03-10 09:07
Duplicate of https://github.com/msys2/MINGW-packages/issues/7611

**Closed by Biswa96** 2023-03-10 09:07 UTC
