### ISSUE TITLE
Missing API-MS-WIN-CORE-*.DLLs

### ISSUE THREAD

**Issue by william-lohan** [msys2/MINGW-packages#8871] opened 2021-06-11 05:16 UTC
The following program on my Windows 10 fails to run and exits without error (exits with 0). 

```cpp
#include <iostream>

extern "C"
{
#include <libavutil/opt.h>
#include <libavutil/avutil.h>
#include <libavcodec/avcodec.h>
#include <libavformat/avformat.h>
}

int main(int, char **)
{
  AVFormatContext *format = avformat_alloc_context();

  std::cout << "Hello, world!" << std::endl;

  return 0;
}
```

If I debug the debugger returns c0000135 suggesting missing DLL.

>ERROR: Unable to start debugging. Unexpected GDB output from command "-exec-run". During startup program exited with code 0xc0000135.
>The program 'path\to\my\project\LibavPlayground.exe' has exited with code 0 (0x00000000).

Dependency Walker shows  dozens of missing API-MS-WIN-CORE-*.DLL files. https://social.msdn.microsoft.com/Forums/en-US/a28331ae-19a3-4a34-b3ba-1e8fd4430375/missing-apimswincore-dlls suggests I can't just acquire those DLLs

![image](https://user-images.githubusercontent.com/8146733/121634592-aed3e100-ca39-11eb-9155-83737a7dae76.png)

I didn't do anything special/non-standard, I installed msys2 and pacman installed the mingw64 86_64 toolchain cmake and ffmpeg

https://stackoverflow.com/questions/67882783/slient-crash-when-calls-to-ffmpegs-libav-exist

**Comment by Biswa96** [comment] 2021-06-11 05:27
Are you using UCRT? UCRT is available in any Windows 10 system. Those api-ms-win-* dlls are resolved from [Windows API sets][1] at runtime (generally).

BTW, try to use [Dependencies][2] instead of old Dependency walker.

[1]: https://docs.microsoft.com/en-us/windows/win32/apiindex/windows-apisets
[2]: https://github.com/lucasg/Dependencies

**Comment by lazka** [comment] 2021-06-11 06:23
I think "depends.exe" was never updated to handle these DLLs. So, as Biswa96 said, use "Dependencies" instead.

**Comment by william-lohan** [comment] 2021-06-11 07:26
@Biswa96 should I be? I honestly don't know what that is. I'm using mingw-w64-x86_64-toolchain (ie mingw-w64-x86_64-gcc and mingw-w64-x86_64-cmake).

**Comment by william-lohan** [comment] 2021-06-11 07:28
@Biswa96 & @lazka Thankyou for the help. Ok got Dependencies it shows now only `api-ms-win-core-comm-l1-1-0.dll` `api-ms-win-core-xstate-l2-1-1.dll` and `ext-ms-win-oobe-query-l1-1-0.dll` missing.

**Comment by Biswa96** [comment] 2021-06-11 07:41
I don't know what the cause is but your provided DLLs are different than mine. Here are my results:

* mingw64:

![mingw64](https://user-images.githubusercontent.com/31443074/121649633-63134d00-cab6-11eb-8d3f-84d669135ae6.PNG)

* ucrt64:

![ucrt64](https://user-images.githubusercontent.com/31443074/121649677-6dcde200-cab6-11eb-8e18-9b3f7ffa16c1.PNG)

**Comment by lazka** [comment] 2021-06-11 07:45
> As you are using mingw-w64-x86_64-toolchain, it should never link to UCRT nor those apiset DLLs.

msvcrt links to apiset DLLs I think

**Comment by Biswa96** [comment] 2021-06-11 07:57
Are you mixing any Visual Studio or MSVC libraries with MinGW libraries? Or is there anything in `$PATH` or `%PATH%` which can collide with MinGW libraries?

**Comment by william-lohan** [comment] 2021-06-11 08:02
I don't think so I've never done C/C++ development with Visual Studio only C# asp.net stuff.
![image](https://user-images.githubusercontent.com/8146733/121652679-bfdc1c80-ca50-11eb-8184-60b415fcf377.png)

**Comment by mati865** [comment] 2021-06-11 15:45
All `api-ms*` libraries should be resolved by the system but the tools cannot see how so they either guess or show missing DLL.
If you run your executable from `cmd.exe` does it show anything?

**Comment by william-lohan** [comment] 2021-06-11 17:12
@mati865 it would show nothing.

>D:\path\to\build>LibavPlayground.exe
>D:\path\to\build>

**Comment by mati865** [comment] 2021-06-11 18:32
I think there might be external DLL picked in place of the correct one. Could you install `mingw-w64-x86_64-ntldd`, run `ntldd -R <your_binary>` and paste the whole output?

**Comment by shithappens2016** [comment] 2021-06-12 10:03
May be it's just his system(windows 10) some how missing few of  Dlls(api-ms-*.dll) that msvcrt.dll needed.

**Comment by revelator** [comment] 2021-06-13 00:15
my own win10 shows a few missing ucrt dll's as well when a program is linked to msvcrt the programs work just fine though so im not sure if it is a bug in dependencies.

**Comment by revelator** [comment] 2021-06-13 00:17
possible explanation here https://social.msdn.microsoft.com/Forums/aspnet/en-US/a28331ae-19a3-4a34-b3ba-1e8fd4430375/missing-apimswincore-dlls?forum=windowsgeneraldevelopmentissues

**Closed** 2023-08-30 14:38 UTC
