### ISSUE TITLE
SDL2_image static linking seems to be broken

### ISSUE THREAD

**Issue by mechakotik** [msys2/MINGW-packages#19538] opened 2023-12-24 15:50 UTC
### Description / Steps to reproduce the issue

Trying to statically link SDL2_image to my project. I am using Meson build system and including SDL2_image in the following way:
```
sdl2_image_dep = dependency('sdl2_image', static: true)
```

### Expected behavior

It compiles fine (the same project compiled fine until recent MSYS update).

### Actual behavior

Linker gives a bunch of libavif related errors:
```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib/libavif.a(reformat_libyuv.c.obj):(.text+0x17d2): undefined reference to `Convert16To8Plane'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib/libavif.a(reformat_libyuv.c.obj):(.text+0x1b13): undefined reference to `ARGBAttenuate'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib/libavif.a(reformat_libyuv.c.obj):(.text+0x1b73): undefined reference to `ARGBUnattenuate'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib/libavif.a(reformat_libyuv.c.obj):(.text+0x1bef): undefined reference to `HalfFloatPlane'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib/libavif.a(reformat_libyuv.c.obj):(.data+0x18): undefined reference to `RAWToI420'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib/libavif.a(reformat_libyuv.c.obj):(.data+0x40): undefined reference to `ABGRToI420'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib/libavif.a(reformat_libyuv.c.obj):(.data+0x68): undefined reference to `BGRAToI420'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib/libavif.a(reformat_libyuv.c.obj):(.data+0x90): undefined reference to `RGB24ToI420'
...
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment] 2023-12-24 16:21
Thank you for reporting the issue. I can reproduce the issue in my system. The libavif static library has been added recently. libavif pkgconfig file is missing the following two lines.

```ini
Cflags.private: -UAVIF_DLL
Requires.private: aom dav1d libsharpyuv libyuv rav1e SvtAv1Enc
```

I shall try to upstream the change sooner. It needs some changes in libavif cmake file.

**Comment by hessenfarmer** [comment] 2023-12-26 13:01
> Thank you for reporting the issue. I can reproduce the issue in my system. The libavif static library has been added recently. libavif pkgconfig file is missing the following two lines.
> 
> ```ini
> Cflags.private: -UAVIF_DLL
> Requires.private: aom dav1d libsharpyuv libyuv rav1e SvtAv1Enc
> ```

and here is the problem for mingw32 as SvtAv1Enc is only provided in 64 bit

**Comment by Biswa96** [comment] 2023-12-26 13:02
> and here is the problem for mingw32 as SvtAv1Enc is only provided in 64 bit

It is not required to add SvtAv1Enc in 32 bit mingw package.

**Comment by hessenfarmer** [comment] 2023-12-26 17:17
Btw: isn't this a duplicate of #19510 which has been fixed already

**Comment by Biswa96** [comment] 2023-12-26 17:46
> Btw: isn't this a duplicate of #19510 which has been fixed already

Yeah, somewhat. Previous issue as about adding static library and this one is for fixing it 🙂

**Comment by Biswa96** [comment] 2023-12-29 14:17
I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request?

**Closed** 2023-12-30 17:26 UTC
Labels: bug
