### ISSUE TITLE
`gRPC` package vendors in `abseil-cpp`

### ISSUE THREAD

**Issue by coryan** [msys2/MINGW-packages#11757] opened 2022-05-31 22:59 UTC
First time I am reading (or trying to use) msys2 packages, so I may have things wrong, apologies if I do. 

The gRPC package seems to be compiling and installing abseil-cpp as part of the build:

https://github.com/msys2/MINGW-packages/blob/c423229d681cc78f642310114d7b87b60bed1ea8/mingw-w64-grpc/PKGBUILD#L26

This is not needed as there is a perfectly good `abseil-cpp` package already:

https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-abseil-cpp

Seems like all that would be needed is to add `abseil-cpp` as a dependency, remove the steps to vendor it in, and then add `-DgRPC_ABSL_PROVIDER=package` to the gRPC configuration line.

**Comment by Biswa96** [comment] 2022-06-01 03:30
Duplicate of https://github.com/msys2/MINGW-packages/issues/11562.

Last time I checked, there were some linking error. Please follow the linked issue for any future update.

**Closed by Biswa96** 2022-06-01 03:30 UTC
