### ISSUE TITLE
zlib version/header mismatch in fmtutil (mingw-w64-x86_64-texlive-core)

### ISSUE THREAD

**Issue by reneparis** [msys2/MINGW-packages#20510] opened 2024-03-31 19:39 UTC
### Description / Steps to reproduce the issue

I'm currently unable to install `mingw-w64-x86_64-texlive-core`, because the post-transaction hook fails.

As far as I understand it, `fmtutil.exe` is the source.  Maybe recompiling it with zlib 1.3.1 will help, but I'm not really into this.
If there is anything I can do to narrow the issue further down, let me know.

### Expected behavior

Package installs without error.

### Actual behavior

```
Running post-transaction hooks...
(1/6) Updating fontconfig cache...
(2/6) Probing GDK-Pixbuf loader modules...
(3/6) Updating TeXLive filename database...
Running mktexlsr
Running mtxrun (this might take a while)
PANIC: unprotected error in call to Lua API (zlib library version does not match - header: 1.3, library: 1.3.1)
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

If I would know what to do, yes.

**Comment by Biswa96** [comment] 2024-03-31 19:42
Duplicate of #19981

**Closed by Biswa96** 2024-03-31 19:42 UTC
Labels: bug
