### ISSUE TITLE
Problems with texlive (tlmgr not working), then trying to reinstall [texlive-core] 

### ISSUE THREAD

**Issue by dieter-wilhelm** [msys2/MINGW-packages#20277] opened 2024-03-07 14:58 UTC
### Description / Steps to reproduce the issue

1. `pacman -Syu`
2. `pacman -S mingw-w64-x86_64-texlive-core`

### Expected behavior

reinstalling texlive-core 2023.20230404-1

### Actual behavior

**error message about zlib version:**
perl: warning: Falling back to the standard locale ("C").
PANIC: unprotected error in call to Lua API (zlib library version does not match - header: 1.3, library: 1.3.1)
error: command (/usr/share/libalpm/scripts/mingw-w64-x86_64-texlive-fmtutil.script /usr/share/libalpm/scripts/mingw-w64-x86_64-texlive-fmtutil.script ) failed to execute correctly
(4/4) Updating TeXLive font maps...
>>> Running updmap (this might take a while)
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LC_ALL = "en_US.utf8",
        (possibly more locale environment variables)
        LANG = "C"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
PANIC: unprotected error in call to Lua API (zlib library version does not match - header: 1.3, library: 1.3.1)
error: command (/usr/share/libalpm/scripts/mingw-w64-x86_64-texlive-updmap.script /usr/share/libalpm/scripts/mingw-w64-x86_64-texlive-updmap.script ) failed to execute correctly

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22000 (on Win11)

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment] 2024-03-07 15:10
Duplicate of #19981

**Closed by Biswa96** 2024-03-07 15:10 UTC
Labels: bug

**Comment by dieter-wilhelm** [comment] 2024-03-07 16:46
@Biswa96 I'm sorry for the redundant report.  I interpreted  the "closed" stati of the other bug reports as "solved" since the first report came already in August 2023 (https://github.com/msys2/msys2-texlive/issues/21).  And it said just update with `pacman -Syyu` and it's solved but isn't in my case!?

**Comment by Biswa96** [comment] 2024-03-07 17:45
No worries, duplicate issues happen some time. In that old issue, the texlive package was rebuilt. We now need another rebuild of texlive for zlib update.

**Comment by dieter-wilhelm** [comment] 2024-03-08 20:52
> We now need another rebuild of texlive for zlib update.

That means doing `pacmn -Suy` now and then and hoping for the best? I assume 😊

**Comment by Biswa96** [comment] 2024-03-09 04:28
No, texlive has not been rebuilt. Please subscribe to the linked issue. You'll get notified.

**Comment by dieter-wilhelm** [comment] 2024-03-09 09:54
> No, texlive has not been rebuilt. Please subscribe to the linked issue. You'll get notified.

I see, thank you for the hint!
