### ISSUE TITLE
gcc: fatal error: cannot execute ‘cc1’: spawn: No such file or directory

### ISSUE THREAD

**Issue by yuki-kimoto** [msys2/MINGW-packages#8107] opened 2021-03-10 07:23 UTC
I want to create Windows Application by msys2 MinGW 64bit.

I try this.

```
$ gcc -Wall -O3 -o message.o -c message.c

gcc: fatal error: cannot execute ‘cc1’: spawn: No such file or directory
compilation terminated.
```

I think gcc can't find cc1 program.

```
$ which gcc
/mingw64/bin/gcc
```

```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
Target: x86_64-pc-msys
Configured with: /c/_/S/gcc/src/gcc-10.2.0/configure --build=x86_64-pc-msys --prefix=/usr --libexecdir=/usr/lib --enable-bootstrap --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --with-arch=x86-64 --with-tune=generic --disable-multilib --enable-__cxa_atexit --with-dwarf2 --enable-languages=c,c++,fortran,lto --enable-graphite --enable-threads=posix --enable-libatomic --enable-libgomp --disable-libitm --enable-libquadmath --enable-libquadmath-support --disable-libssp --disable-win32-registry --disable-symvers --with-gnu-ld --with-gnu-as --disable-isl-version-check --enable-checking=release --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible --enable-libstdcxx-filesystem-ts
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 10.2.0 (GCC)
```

```
$ gcc -print-search-dirs
install: /mingw64/bin/../lib/gcc/x86_64-pc-msys/10.2.0/
programs: =/mingw64/bin/../lib/gcc/x86_64-pc-msys/10.2.0/:/mingw64/bin/../lib/gcc/:/mingw64/bin/../lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/x86_64-pc-msys/10.2.0/:/mingw64/bin/../lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/
libraries: =/mingw64/bin/../lib/gcc/x86_64-pc-msys/10.2.0/:/mingw64/bin/../lib/gcc/:/mingw64/bin/../lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/lib/x86_64-pc-msys/10.2.0/:/mingw64/bin/../lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/lib/../lib/:/mingw64/bin/../lib/gcc/x86_64-pc-msys/10.2.0/../../../x86_64-pc-msys/10.2.0/:/mingw64/bin/../lib/gcc/x86_64-pc-msys/10.2.0/../../../../lib/:/lib/x86_64-pc-msys/10.2.0/:/lib/../lib/:/usr/lib/x86_64-pc-msys/10.2.0/:/usr/lib/../lib/:/mingw64/bin/../lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/lib/:/mingw64/bin/../lib/gcc/x86_64-pc-msys/10.2.0/../../../:/lib/:/usr/lib/
```

I found cc1 in the following directory

```
C:\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\10.2.0\cc1.exe
```

cc1 is not contained in the following path. 

```
/mingw64/bin/../lib/gcc/x86_64-pc-msys/10.2.0
```

Can you help me?

Is discussion is good about this topic?

**Comment by revelator** [comment] 2021-03-10 08:38
last path is gcc's internal lookup path you cannot use that as such try executing /mingw64/bin/lib/gcc/x86_64-pc-msys/10.2.0/cc1 instead, looks like you might be missing either libwinpthread-1.dll or libgmp-10.dll in which case cc1 would not run.

**Comment by mati865** [comment] 2021-03-10 10:00
```
$ gcc -print-search-dirs
install: /mingw64/bin/../lib/gcc/x86_64-pc-msys/10.2.0/
```
It's totally wrong, seems like you have copied `/usr/bin/gcc` to `/mingw64/bin/`.
Please reinstall GCC with `pacman -S mingw-w64-x86_64-gcc` and try again.

**Comment by revelator** [comment] 2021-03-10 22:57
Doh i totally missed that one :facepalm:

**Comment by yuki-kimoto** [comment] 2021-03-11 04:52
thank you.

I reinstalled "pacman -S mingw-w64-x86_64-gcc".

problem is fixex.

**Comment by oscarfv** [comment] 2021-07-03 00:09
@yuki-kimoto : as the problem is fixed, please close this issue. Thanks.

**Closed** 2021-07-03 09:02 UTC

**Comment by amaner3112** [comment] 2022-03-11 01:52
thanks for sharing this info is helpful.
