### ISSUE TITLE
Add native version(s) of texinfo and info.exe

### ISSUE THREAD

**Issue by dr-scsi** [msys2/MINGW-packages#16588] opened 2023-04-02 07:53 UTC
### Package name

texinfo / info

### Brief description of package

Utilities to work with and produce manuals, ASCII text, and on-line documentation from a single source file

### URL for package's homepage

https://www.gnu.org/software/texinfo/

### Provide a basic test case to validate the package's functionality.

MSYS2 provides a Base Package [texinfo](https://packages.msys2.org/base/texinfo) which is a msys application.  Is it possible to provide also a native version of `info.exe` and friends, i.e., for MINGW64 et al.?  It would make it easier to run info.exe from other native programs (Emacs is one of them).

### MINGW environments where you need the package

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment] 2024-06-05 04:43
Duplicate of #631
Fixed by #20665

**Closed by Biswa96** 2024-06-05 04:43 UTC
Labels: package-request
