### ISSUE TITLE
Random meson failures

### ISSUE THREAD

**Issue by kmilos** [msys2/MINGW-packages#16308] opened 2023-03-20 11:48 UTC
### Description / Steps to reproduce the issue

LittleCMS2 CI matrix would intermittently fail on `meson" "--internal" "symbolextractor"`. Latest example: https://github.com/mm2/Little-CMS/actions/runs/4440155149

This is regardless of MSYS2 environment or static vs shared build.

As a consequence, [the maintainer decided to remove MSYS2 from CI and supported platforms.](https://github.com/mm2/Little-CMS/commit/2a751a618eaa3ff3b181c67755120fa5142a2630) 

### Expected behavior

Every meson run is successful.

### Actual behavior

Random failure, seemingly without any pattern.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW32_NT-10.0-20348

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

No

**Comment by lazka** [comment] 2023-03-20 12:32
This is https://github.com/mesonbuild/meson/commit/e945f35cd72402d0d204ff10870e2a95c59b6192

**Comment by Biswa96** [comment] 2023-03-20 13:09
Duplicate of https://github.com/msys2/MINGW-packages/issues/11864

**Closed by Biswa96** 2023-03-20 13:09 UTC
Labels: bug
