### ISSUE TITLE
PyQtWebEngine @ Msys2 Mingw x64 POSIX platform

### ISSUE THREAD

**Issue by el07694** [msys2/MINGW-packages#12039] opened 2022-07-14 04:22 UTC
Hello,

Is there any plan to replace QtWebKit (either in PyQt5 or PyQt6) with PyQtWebEngine?

PyQtWebEngine build is depended in Visual Studio?

QtWebKit doesn't have so many features (javascript interaction from python method, comunication between javascript function and python method using QWebChannel, WebRTC {RTCPEERCONNECTION} and so more...)

**Comment by ZachBacon** [comment] 2022-07-14 05:25
So qtwebengine which is based off of chromium, has currently a hard requirement for visual studio. It would need upstream development at least in chromium first to get it to work with the mingw compiler stack. So most likely we won't be seeing qtwebengine anytime soon

**Comment by el07694** [comment] 2022-07-14 05:48
Any alternative?

Selenium may be an alternative:

1. Run javascript after page loaded from python: [here](https://stackoverflow.com/questions/5585343/getting-the-return-value-of-javascript-code-in-selenium/5585345#5585345)
2.  (the oposite) call python method from javascript: ???
Maybe with setInterval from python to check when javascript data is ready or javascript event is fired

**Comment by MehdiChinoune** [comment] 2022-08-16 12:50
duplicate of #8444

**Closed by MehdiChinoune** 2022-08-16 12:50 UTC
Labels: duplicate
