### ISSUE TITLE
Qt5 shared and windeployqt

### ISSUE THREAD

**Issue by alekseysidorov** [msys2/MINGW-packages#221] opened 2014-09-23 10:59 UTC
When i try to use windeployqt with mingw-w64-x86_64-qt5-5.3.2-1 i have a problem with icu deploying.

``` bash
Sidorov@Nastya /c/develop/cleverCNC/sources
$ windeployqt.exe qt5-mingw32-i686-debug/install-root/bin/
C:\develop\cleverCNC\sources\qt5-mingw32-i686-debug\install-root\bin\cleverCNC.exe 32 bit, debug executable [QML]
Unable to locate ICU library icudt53.dll
```

How i can deploy application with msys2 qt5 and windeployqt?

**Comment by donbright** [comment] 2015-10-31 00:50
I have been able to build and deploy using a kludge:

       cd /mingw64/bin
       for i in lib*dll ; do ln -s $i `echo $i  | sed s/^lib//g -` ; done

it is not a good solution, because the final package had duplicate copies of an ICU dll file, one with the 'lib' prefix and one without.

**Comment by petteyg** [comment] 2016-03-11 16:54
The ln command could simply be `ln -s $i ${i#lib}` without calling sed. Any chance of a real fix in the near future?

**Comment by mingwandroid** [comment] 2016-03-11 18:02
No idea, it's unlikely to fix itself though.

**Comment by ajneu** [comment] 2016-03-14 20:54
The code for `windeployqt` is here: http://code.qt.io/cgit/qt/qttools.git/tree/src/windeployqt

```bash
git clone https://code.qt.io/qt/qttools.git
cd qttools
git checkout v5.5.1    ## checkout a specific branch
cd src/windeployqt
```

**Comment by ajneu** [comment] 2016-03-14 21:13
I don't currently have access to a windows machine, but if the comment above by alekseysidorov is still relevant...
> Windeployqt always looking for `icudtxx.dll` instead `libicudtxx.dll`
> I think it should also looking for `libicudtxx.dll`.

then the relevant lines might be
http://code.qt.io/cgit/qt/qttools.git/tree/src/windeployqt/main.cpp?h=5.5#n1111 (in Qt5.5 - line 1111)
http://code.qt.io/cgit/qt/qttools.git/tree/src/windeployqt/main.cpp?h=5.6#n1214 (in Qt5.6 - line 1214)

and the current warning
> `Unable to locate ICU library icudt53.dll`

generated 6 lines lower.

**Comment by Krakonos** [comment] 2016-06-02 09:51
I can confirm this problem. Windeployqt does not only copy link dependencies, but also plugins. This tool makes it easy, though currently it needs some kind of hack about icudt (I make a copy, and delete it from distribution afterwards).

I'd really like to see it fixed, though I'm not sure if it's MSYS2-only problem or should it be reported to upstream.

**Comment by parched** [comment] 2016-06-22 21:56
Hi @Alexpux or @mingwandroid I have a patch here that fixes windeployqt for us https://github.com/parched/qttools/commit/fccfcf6e3b023ef392e1a199a14459ae30a6b44f

Can you apply it to the next qt release? Or would you like me to try and submit a PR? (I'm just not sure how all the patch numbering works for qt5)

Note, it's not a complete solution because it only does the Qt deps (and not its deps like icu and the others that msys2 adds like zlib etc) so it needs to be used with another tool (I'm using ldd) but this makes it usable for the qt plugins which ldd can't do.

**Comment by mingwandroid** [comment] 2016-06-23 18:44
Please submit a PR.

**Comment by parched** [comment] 2016-06-25 11:20
PR submitted here https://github.com/Alexpux/MINGW-packages/pull/1504 I will submit matching for qt5-static once I know its fine

**Comment by Ralith** [comment] 2016-07-31 07:16
Am I correct in judging that this change has been merged and made it into the package repos? [I still seem to be experiencing the issue](https://ci.appveyor.com/project/Ralith/nachat/build/0.0.0.20-appveyor/job/ix9fev7wiyf35lap#L1013).

**Comment by parched** [comment] 2016-07-31 07:37
@Ralith yes,  but you need to pass `--no-libraries` and use another tool (e.g., `ldd`) for the libs.

**Comment by Ralith** [comment] 2016-07-31 08:05
@parched [That option had no visible effect](https://ci.appveyor.com/project/Ralith/nachat/build/job/keu56i3a6onerlnr).

**Closed** 2022-08-16 06:11 UTC
Labels: qt5

**Comment by MehdiChinoune** [comment] 2022-08-16 06:14
Fixed long time ago by https://github.com/msys2/MINGW-packages/commit/b335093755e2bfe55189047db6724e940a04e728
