### ISSUE TITLE
windres problem in mingw64 gcc-10

### ISSUE THREAD

**Issue by gerard-durand** [msys2/MINGW-packages#6558] opened 2020-06-05 17:21 UTC
When triing to compile wxWidgets 3.1.4 with the last version of gcc/g++ installed yesterday (version 10.1) through pacman, I have a problem when the makefile uses windres. Though the path to find a wx/version.h file is correctly set with a correct --inlude-dir ../../include, windres does not find it. I have simply replaced windres.exe by the previous version distributed with gcc 9.3, and like that it works.

**Comment by PBfordev** [comment] 2020-07-13 14:40
I can confirm the issue, FWIW, here is the error log
```
windres --use-temp-file -i../../src/msw/version.rc -ogcc10_mswuddll\basedll_version_rc.o  --include-dir ../../src/zlib --include-dir ../../src/regex --include-dir ../../src/expat/expat/lib   --define wxUSE_DPI_AWARE_MANIFEST=2 --define __WXMSW__       --define _UNICODE --include-dir ..\..\lib\gcc10_dll\mswud --include-dir ../../include  --define WXBUILDING --define WXDLLNAME=wxbase314ud_gcc_custom --define wxUSE_GUI=0 --define WXMAKINGDLL_BASE --define wxUSE_BASE=1
../../src/msw/version.rc:11:10: fatal error: wx/version.h: No such file or directory
   11 | #include "wx/version.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
windres: gcc exited with status 1
mingw32-make: *** [makefile.gcc:11878: gcc10_mswuddll\basedll_version_rc.o] Error 1
```

File `wx/version.h` is where it is supposed to be (i.e., in `..\..\lib\gcc10_dll\mswud`), building works with exactly same parameters with older version (in my case mingw-w64 with GCC 8.1.0).

Unfortunately, I do not know much about GCC or MinGW but I did notice that the include path for the supposedly missing file uses backslashes instead of slashes. The other include paths use slashes. 

So I am not sure whether the issue is really with MinGW or with wxWidgets makefile. I will ask wxWidgets developers.

**Comment by vadz** [comment] 2020-07-13 19:10
@PBfordev Thanks for investigating this, we can remove `--use-temp-file` from wxWidgets makefiles, this shouldn't be needed on any system from this millennium anyhow.

**Comment by gerard-durand** [comment] 2020-07-14 16:55
So, what is the best solution ?
- modifying my config.gcc (or will this file will be modified in a future commit ?)
- adding in my build command for generating wxWidgets WINDRES=windres to avoid the predefined WINDRES ?= windres --use-temp-file option.

**Comment by PBfordev** [comment] 2020-07-14 17:34
@gerard-durand , as you can see from the mention above your post referencing a wxWidgets PR, the option is going to be removed from the wxWidgets master and hence from soon-to-be-released wxWidgets 3.1.4.

With older versions, I would personally prefer your second workaround, i.e., not modify any wxWidgets file to prevent possible future conflicts.

**Comment by gerard-durand** [comment] 2020-07-15 08:16
OK. Thanks all

**Comment by MehdiChinoune** [comment] 2022-08-28 06:34
Seems to be fixed in upstream

**Closed by MehdiChinoune** 2022-08-28 06:34 UTC
