### ISSUE TITLE
PyQtWebEngine

### ISSUE THREAD

**Issue by iahung3** [msys2/MINGW-packages#20098] opened 2024-02-18 10:57 UTC
### Package name

PyQtWebEngine

### Brief description of package

PyQtWebEngine is a set of Python bindings for The Qt Company’s Qt WebEngine framework.

### URL for package's homepage

https://www.riverbankcomputing.com/software/pyqtwebengine/

### Provide a basic test case to validate the package's functionality.

https://www.riverbankcomputing.com/software/pyqtwebengine/

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

### Are you willing to submit a PR?

No

**Comment by iahung3** [comment] 2024-02-18 11:01
I know this is impossible. But let's make an issue to track it. Maybe in the distant future, this will become a reality!

**Comment by MehdiChinoune** [comment] 2024-02-18 11:19
duplicate of #8444

**Closed by MehdiChinoune** 2024-02-18 11:19 UTC
Labels: package-request
