### ISSUE TITLE
Add [mingw-w64-rustup]

### ISSUE THREAD

**Issue by 500-internal-server-error** [msys2/MINGW-packages#20897] opened 2024-05-14 03:23 UTC
### Package name

mingw-w64-rustup

### Brief description of package

The Rust toolchain installer

### URL for package's homepage

https://github.com/rust-lang/rustup.rs

### Provide a basic test case to validate the package's functionality.

Installing rustup should functionally be the same as installing distro-provided rust (e.g., for the purposes of building packages, satisfying runtime dependencies, etc.), which is the way it works on Arch.

### MINGW environments where you need the package

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

[PKGBUILD](https://github.com/500-internal-server-error/aur-msys2/blob/main/mingw-w64-rustup/PKGBUILD), mostly taken from Arch with some modifications to better fit in MSYS2 (notably replacing symlinks to multicall binaries with hardlinks, to maintain the small package size without requiring modifications to a stock Win8+ install).

**Comment by ognevny** [comment] 2024-05-14 03:23
duplicate of https://github.com/msys2/MINGW-packages/issues/16145

**Comment by lazka** [comment] 2024-05-14 05:41
duplicate of https://github.com/msys2/MINGW-packages/issues/16145

**Closed by lazka** 2024-05-14 05:41 UTC
Labels: package-request
