### ISSUE TITLE
KF5 adventures - zombie processes + qt plugin install dir

### ISSUE THREAD

**Issue by naksyl** [msys2/MINGW-packages#10158] opened 2021-11-21 23:46 UTC
Windows 11 breaks main menus in Qt applications so I decided to compile breeze - this leads me to some issues. Here is [PKGBUILD](https://github.com/naksyl/MINGW-kde/blob/master/mingw-w64-breeze-qt5/PKGBUILD) if somebody wants check it. 

### KF5 zombie processes
Discovered when playing with breeze, but it is not related. Probably all apps that links to some kf5 lib are affected - cant figure out which one. Even qt apps (designer, assistant) running in breeze style are affected. Steps to reproduce:
```sh
# launch couple of kwrite/kate processes - it doesnt matter if launched from console or gui
for i in {1..3}; do kwrite & done
# or simply run as kwrite - you dont see the prompt after window is closed and CTRL-C isnt working
# close all windows by clicking 'x'
# verify that processes still exists
ps -W | grep kwrite
```
I cannot kill those by bashes kill, cmd taskkill, or powershell Stop-Process only stopping process from GUI task list works. They are listed as background processes, but still eats resources? Correct me if I am wrong.

Following KF5 tutorials [THIS](https://techbase.kde.org/Development/Tutorials/Using_KActions/KF5) is the first affected application - it introduces toolbar through xmlgui - shoud be installed with `ninja install`. I found old issue  #6217 which suggest that dbus is guilty.

### Some qt/kf5 packages install libs in wrong directory
`qtdiag.exe | grep plugin` reports `$PREFIX/share/qt5/plugins` directory but:
```sh
$ ls /mingw64/lib/plugins/*/*.dll
/mingw64/lib/plugins/designer/kcompletion5widgets.dll*
/mingw64/lib/plugins/designer/ktextwidgets5widgets.dll*
/mingw64/lib/plugins/designer/kdewebkit5widgets.dll*
/mingw64/lib/plugins/designer/kwidgetsaddons5widgets.dll*
/mingw64/lib/plugins/designer/kiconthemes5widgets.dll*
/mingw64/lib/plugins/designer/kxmlgui5widgets.dll*
/mingw64/lib/plugins/designer/kitemviews5widgets.dll*
/mingw64/lib/plugins/iconengines/KIconEnginePlugin.dll*
/mingw64/lib/plugins/designer/kplotting5widgets.dll*
```
Those are probably designer plugins (there should be plenty of kf5 widgets but ther are only few) only, but still... Some proposal to fix this one:
- move `cmake` invocation to kde-frameworks5 from `PKGBUILD-common`
- this should handle those static/dynamic variants (PKGUILDS are harder to read)
- make sure all kf5 package uses kde-frameworks5
- think about building documention too - qch files are not so big
- maybe autodoc solution that moves `share/{doc,info,man,html}` to `pkg-doc` subpackage - is this possible?

```sh
# kde-frameworks5 FARGMENT DRAFT
_kde_f5_invoke_cmake() {
    _kde_f5_build_env
      ${MINGW_PREFIX}/bin/cmake.exe \
    -G "Ninja" \
    -DCMAKE_BUILD_TYPE=$(_kde_f5_CMAKE_BUILD_TYPE) \
    "${_kde_f5_KDE_INSTALL_DIRS[@]}" \
    -DBUILD_QCH=ON \
    -DBUILD_TESTING=OFF \
    -DECM_DIR=${MINGW_PREFIX}/share/ECM \
    "$@" \
    ../${_basename}-${pkgver}
}

# PKGBUILD FRAGMENT
build() {
    ...

    _kde_f5_invoke_cmake \
    -PLEASE_ADD_THIS_OPTION

    ${MINGW_PREFIX}/bin/cmake.exe --build ./
}
```
This way we can ensure that all kf5 packages are configured in unified way.

### SEMI-HIDPI screens
I have one of those piece of ... screen - 15.4" 1920x10800 on my lenovo laptop. On linux (kde) I use 120 font DPI and scale=1, which works best in my case. On windows every app lives each own live, there are no central place to set theme or so as in plasma (systemsettings) 

I think the best what can be done is to write/port Qt platform plugin and overwrite windows default font - this could be supported by systemsettings5-like app where user can adjust and unify settings for all qt apps. Probably the best chance for this comes with plasma. Please let me know if you have a solution for this. Some screenshot:

![screenshot](https://user-images.githubusercontent.com/17428477/142783127-8e5f8608-ee75-498c-9ae3-c775e3d41e17.png)

The best looking app is probably Qt designer - assistant render font to small, kwrite oversizes menus and scale icons which becomes blury, vlc in native LAF fonts to small. It would be nice to:
```sh
export QT_QPA_PLATFORMTHEME=Breeze
export QT_STYLE_OVERRIDE=Breeze
export QT_FONT_DPI=96
export QT_SCALE_FACTOR=1
```
and adjust font in systemsettins. Uff  it was a bit long 🥲

**Comment by revelator** [comment] 2021-12-05 01:55
the zombies are caused by dbus, sadly while it works to some extent on windows it lacks certain control mechanisms for closing connected running apps. if you try processhacker you will instantly notice dbus running in the background keeping these apps open, killing dbus also allows closing kate / kwrite

**Comment by naksyl** [comment] 2022-05-03 17:27
Patching qt-base with [qdbus-manager-quit-5.7.patch](https://raw.githubusercontent.com/KDE/craft-blueprints-kde/master/libs/qt5/qtbase/qdbus-manager-quit-5.7.patch) close this issue. Just built and test on mingw64. Application exits by the book.

**Closed** 2022-12-09 05:58 UTC
Labels: bug
