### ISSUE TITLE
binutils 2.35 broken [relocation truncated to fit]

### ISSUE THREAD

**Issue by rmottola** [msys2/MINGW-packages#6986] opened 2020-09-14 22:22 UTC
When compiling gnustep base (directly from git source repository, something I am doing since years) I recently fail after a big msys upgrade.

I suppose binutils, given the error:

```
 Linking library libgnustep-base ...
obj/libgnustep-base.obj/NSObject.m.o:C:\msys64\home\multix\code\libs-base\Source/NSObject.m:605:(.text+0xa3): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `object_getRetainCount_np'
obj/libgnustep-base.obj/NSObject.m.o:C:\msys64\home\multix\code\libs-base\Source/NSObject.m:574:(.text+0xd12): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `objc_release_fast_np'
obj/libgnustep-base.obj/NSObject.m.o:C:\msys64\home\multix\code\libs-base\Source/NSObject.m:552:(.text+0xd33): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `objc_release_fast_no_destroy_np'
obj/libgnustep-base.obj/NSObject.m.o: in function `release_fast_no_destroy':
C:\msys64\home\multix\code\libs-base\Source/NSObject.m:554:(.text+0xd3d): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `objc_release_fast_no_destroy_np'
obj/libgnustep-base.obj/NSObject.m.o:C:\msys64\home\multix\code\libs-base\Source/NSObject.m:702:(.text+0x2c83): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `objc_retain_fast_np'
obj/libgnustep-base.obj/NSObject.m.o:C:\msys64\home\multix\code\libs-base\Source/NSObject.m:552:(.text+0x2d93): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `objc_release_fast_no_destroy_np'
obj/libgnustep-base.obj/NSObject.m.o:C:\msys64\home\multix\code\libs-base\Source/NSObject.m:605:(.text+0x2dc3): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `object_getRetainCount_np'
obj/libgnustep-base.obj/NSObject.m.o:C:\msys64\home\multix\code\libs-base\Source/NSObject.m:605:(.text+0x2dfb): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `object_getRetainCount_np'
obj/libgnustep-base.obj/NSObject.m.o: in function `getRetainCount':
C:\msys64\home\multix\code\libs-base\Source/NSObject.m:607:(.text+0x2e05): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `object_getRetainCount_np'
obj/libgnustep-base.obj/NSObject.m.o:C:\msys64\home\multix\code\libs-base\Source/NSObject.m:702:(.text+0x2e33): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `objc_retain_fast_np'
obj/libgnustep-base.obj/NSObject.m.o: in function `getRetainCount':
C:\msys64\home\multix\code\libs-base\Source/NSObject.m:607:(.text+0xad): additional relocation overflows omitted from the output
collect2.exe: error: ld returned 1 exit status
```

**Comment by rmottola** [comment] 2020-09-14 22:24
I wanted to double-check downgrade binutils and retry with the latest version I had in cache:

`$ pacman -U /var/cache/pacman/pkg/binutils-2.34-3-x86_64.pkg.tar.zst`

the command completes, but "ld --version" still shows 2.35 and I still have the same error

**Comment by jeremyd2019** [comment] 2020-09-14 22:51
that's the msys binutils, not mingw-w64-{i686,x86_64}-binutils.

These relocation truncated to fit messages are probably from the change in default image base, but a better question would be why these symbols are undefined in the first place.

**Comment by jeremyd2019** [comment] 2020-09-14 23:39
@mati865 is this another case of runtime pseudo-relocations?  Because I thought that DLLs couldn't link if they had undefined symbols

**Comment by mati865** [comment] 2020-09-15 06:40
@jeremyd2019 if linking dynamic libraries and dllimport was not used, LLD first looks if there is dllimport symbol it could pick. If there is none then it looks for the the symbol without dllimport to use pseudo reloc. Eventually errors if the symbol cannot be found.

**Comment by rmottola** [comment] 2020-09-15 08:59
> that's the msys binutils, not mingw-w64-{i686,x86_64}-binutils.

Do you mean I "downgraded" the wrong package or that "ld" is executing the other binutils? I am a little bit confused of having two binutils and which one is being used then.

> 
> These relocation truncated to fit messages are probably from the change in default image base, but a better question would be why these symbols are undefined in the first place.

In the source code I compiled, nothing changed. I tried
1) clean build with unupgraded mingw64, worked
2) upgrade with "pacman -Syu"
3) problem as above comes out (reproduced by other persons)

I tried to selective identify the package but failed

**Comment by mati865** [comment] 2020-09-15 09:25
@jeremyd2019 sorry I have confused the issues.

Relocations cannot use undefined symbols. I suspect the build system didn't detect something and doesn't pass missing lib to the linker via `-l<lib>`.

**Comment by rmottola** [comment] 2020-09-15 12:31
given the hint of @jeremyd2019, I did downgrade not only msys binutils but also `mingw-w64-x86_64-binutils (2.35-6 => 2.34-3)`

Now everything links & compiles... I did not even reconfigure, so no different "detection". @mati865 is this possibly a clue?

If running ldd or something on the libraries helps, just tell me.

**Comment by mati865** [comment] 2020-09-15 12:57
@rmottola I've looked at the code and it's probably bug with gnustep base.

With newer binutils package you can try to workaround it by passing `-Wl,--disable-dynamicbase,--default-image-base-low` to the linker (`LDFLAGS="-Wl,--default-image-base-low` for most of the build systems) to disable ASLR.

---


About the bug:
Look at this line https://github.com/gnustep/libs-base/blob/fc0c0da188eb4ee2800ab9643394aa16660ef6bd/Headers/GNUstepBase/GSVersionMacros.h#L383:
```
# if defined(__MINGW__)
  /* On Mingw, the compiler will export all symbols automatically, so
   * __declspec(dllexport) is not needed.
   */
```
No, the compiler won't export all the symbols. The linker would export all symbols **if** `--export-all-symbols` was passed to it but that doesn't seem to happen anywhere in `libs-base` code.
So what really happens is the linker will use it's heuristic to **guess** which symbols should be exported.
New binutils package enables high entropy ASLR by default which breaks incorrect assumptions like that.

You should try removing those lines so it looks like this:
```C
#if BUILD_libgnustep_base_DLL
#  define GS_EXPORT  __declspec(dllexport)
#  define GS_DECLARE __declspec(dllexport)
#else
#  define GS_EXPORT  extern __declspec(dllimport)
#  define GS_DECLARE __declspec(dllimport)
#endif
```

**Comment by jeremyd2019** [comment] 2020-09-15 17:27
@mati865  thanks for looking at this. 

> So what really happens is the linker will use it's heuristic to **guess** which symbols should be exported.
> New binutils package enables high entropy ASLR by default which breaks incorrect assumptions like that.

That's an intriguing statement.  

I just noticed this:
```C
/* platforms which do not support weak */
#if (__GNUC__ == 3) && defined (__WIN32)
#define WEAK_ATTRIBUTE
#undef SUPPORT_WEAK
#else
/* all platforms which support weak */
#define WEAK_ATTRIBUTE __attribute__((weak))
#define SUPPORT_WEAK 1
#endif
```
and
```C
/*
 * These symbols are provided by newer versions of the GNUstep Objective-C
 * runtime.  When linked against an older version, we will use our internal
 * versions.
 */
WEAK_ATTRIBUTE
BOOL objc_release_fast_no_destroy_np(id anObject);

WEAK_ATTRIBUTE
void objc_release_fast_np(id anObject);

WEAK_ATTRIBUTE
size_t object_getRetainCount_np(id anObject);

WEAK_ATTRIBUTE
id objc_retain_fast_np(id anObject);
```

That kind of explains how the symbols could be undefined.  But again, I was under the impression that [the Windows loader doesn't support weak symbols](https://devblogs.microsoft.com/oldnewthing/20160317-00/?p=93173).  More magic I guess.

**Comment by mati865** [comment] 2020-09-15 17:44
> That kind of explains how the symbols could be undefined. But again, I was under the impression that [the Windows loader doesn't support weak symbols](https://devblogs.microsoft.com/oldnewthing/20160317-00/?p=93173). More magic I guess.

AFAIK MSVC linker does not support weak symbols and it doesn't even support any of `__attribute__`.
Mingw-w64 GCC+LD can use weak symbols but they are buggy. AFAICT they work correctly when used within single object but when the same weak symbols are used by multiple objects it often fails with undefined references and multiple definition errors.
Clang up to version 10t did not support weak symbols at all for mingw-64. Clang 11 supports them though but it requires more testing.

**Comment by rmottola** [comment] 2020-09-16 22:18
> 
> 
> @mati865 thanks for looking at this.
> 
> > So what really happens is the linker will use it's heuristic to **guess** which symbols should be exported.
> > New binutils package enables high entropy ASLR by default which breaks incorrect assumptions like that.
> 
> That's an intriguing statement.
> 
> I just noticed this:
> 
> ```c
> /* platforms which do not support weak */
> #if (__GNUC__ == 3) && defined (__WIN32)
> #define WEAK_ATTRIBUTE
> #undef SUPPORT_WEAK
> #else
> /* all platforms which support weak */
> #define WEAK_ATTRIBUTE __attribute__((weak))
> #define SUPPORT_WEAK 1
> #endif
> ```
> 
> and
> 
> ```c

> 
> That kind of explains how the symbols could be undefined. But again, I was under the impression that [the Windows loader doesn't support weak symbols](https://devblogs.microsoft.com/oldnewthing/20160317-00/?p=93173). More magic I guess.

That's an interesting hint. WEAK was disabled for Mingw "1" with gcc 3.x since it simply failed to compiled. For newer GCC it compiles and works fine even on MINGW1 as well as MING64 - up to new binutils.
Perhaps indeed it is a matter of exporting all symbols ? should perhaps an LD flag be added?
However if weak is really not supported - then why  just force it disabled, even if the compiler does not bark on it?
I tried removing the GNUC = 3 test above and everything compiles and links with latest gcc10 and binutils 2.35 . Sounds reasonable with your impression

**Comment by jeremyd2019** [comment] 2020-09-21 18:07
> That's an interesting hint. WEAK was disabled for Mingw "1" with gcc 3.x since it simply failed to compiled. For newer GCC it compiles and works fine even on MINGW1 as well as MING64 - up to new binutils.
> Perhaps indeed it is a matter of exporting all symbols ? should perhaps an LD flag be added?
> However if weak is really not supported - then why just force it disabled, even if the compiler does not bark on it?
> I tried removing the GNUC = 3 test above and everything compiles and links with latest gcc10 and binutils 2.35 . Sounds reasonable with your impression

That seems to indicate the issue is with the weak linking, not the heuristics.

My understanding:
Weak linking is not supported on native Windows.  However, binutils and mingw-w64 runtime code seem to have teamed up to implement some linking behavior that is more familiar from the *nix/elf world, such as weak symbols and the auto import heuristic.  It appears that some of this "magic" is not working when the module base address is greater than 4GB.  Technically, it seems to use 32-bit relative relocations, so if relocation could result in addresses being more than +/- 2GB apart it would fail.  In this undefined weak symbol case, the address in question is '0', so taking full advantage of the 64-bit address space is problematic :wink:

**Comment by jeremyd2019** [comment] 2020-09-23 20:32
https://sourceware.org/bugzilla/show_bug.cgi?id=26659

**Comment by mati865** [comment] 2020-09-25 11:21
@jeremyd2019 I have confirmed there are 2 bugs here: one in GCC and other one in BFD.
Weak symbols don't work reliably in GCC/BFD combination but appear to work fine in Clang/BFD and GCC/LLD combinations.

I have attached reproducer based on https://en.wikipedia.org/wiki/Weak_symbol#Shared_example:
```
$ ./build.sh
/d/tmp/weak/shared-wiki/build-lld /d/tmp/weak/shared-wiki


Building with gcc and linking with lld
main: user_hook()
power3() = 27
main: user_hook()
power3() = 27
power3() = 27
power_slow: user_hook()
power3() = 27
/d/tmp/weak/shared-wiki
/d/tmp/weak/shared-wiki/build-bfd /d/tmp/weak/shared-wiki


Building with gcc and linking with bfd
power_slow.po: in function `power2':
D:\tmp\weak\shared-wiki\build-bfd/../power_slow.c:15:(.text+0x18): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `user_hook'
collect2.exe: error: ld returned 1 exit status
Failed at 25: "${CC}" -fuse-ld="${linker}" -shared -o libpowerslow.dll -Wl,--out-implib=libpowerslow.dll.a power_slow.po

$ CC=clang ./build.sh
/d/tmp/weak/shared-wiki/build-lld /d/tmp/weak/shared-wiki


Building with clang and linking with lld
main: user_hook()
power3() = 27
main: user_hook()
power3() = 27
power3() = 27
power_slow: user_hook()
power3() = 27
/d/tmp/weak/shared-wiki
/d/tmp/weak/shared-wiki/build-bfd /d/tmp/weak/shared-wiki


Building with clang and linking with bfd
main: user_hook()
power3() = 27
main: user_hook()
power3() = 27
power3() = 27
power_slow: user_hook()
power3() = 27
/d/tmp/weak/shared-wiki

$ clang -v
clang version 11.0.0 (https://github.com/mati865/MINGW-packages.git 582829b76f2d5dfdc1d972002420a4be513d9c9b)
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: D:\msys64\mingw64\bin
```
[shared.zip](https://github.com/msys2/MINGW-packages/files/5282355/shared.zip)

Clang <=10 doesn't support weak symbols on Windows so I have used Clang 11 rc3 for this test.
BFD version was 2.35, LLD tested versions include 10 and 11 (neither of them reported errors).

**Comment by jeremyd2019** [comment] 2020-09-25 18:31
> @jeremyd2019 I have confirmed there are 2 bugs here: one in GCC and other one in BFD.
> Weak symbols don't work reliably in GCC/BFD combination but appear to work fine in Clang/BFD, Clang/LLD and GCC/LLD combinations.
> 
> I have attached reproducer based on https://en.wikipedia.org/wiki/Weak_symbol#Shared_example:
> 

That'd probably be a good thing to add to the upstream bug report.  I can do that if you don't want to for some reason.  Also interesting would be any sort of assembly, objdump, etc output that shows the difference between what works and what doesn't.  I'll try poking at it a bit, but last time I looked at installing clang/lld it wanted more disk space than I had available for my test VM.

**Comment by mati865** [comment] 2020-09-25 19:06
I can post it in the bug report next week with more details.

**Comment by jeremyd2019** [comment] 2020-09-25 19:41
From GCC
```
$ objdump -r power_slow.po
 
power_slow.po:     file format pe-x86-64
 
RELOCATION RECORDS FOR [.text]:
OFFSET           TYPE              VALUE
000000000000000e R_X86_64_PC32     .refptr.user_hook
0000000000000018 R_X86_64_PC32     user_hook
0000000000000037 R_X86_64_PC32     power2
 
...
 
RELOCATION RECORDS FOR [.rdata$.refptr.user_hook]:
OFFSET           TYPE              VALUE
0000000000000000 R_X86_64_64       user_hook
 
...
```

I tried using objdump on the LLD dll and BFD dll with --default-image-base-low, but I didn't get it to say anything as recognizable as that.

**Comment by mati865** [comment] 2020-09-25 23:14
When I loaded `power_slow.po` from both compilers in Ghidra, library made by Clang exports `weak.power2.default.power3` and `power3` but library made by GCC exports only `power3`. But BFD fails with different thing so lets leave it for now.

Back to the BFD error.
<details>
<summary>Clang symbols:</summary>

```
$ llvm-readobj.exe -r clang/power_slow.po

File: clang/power_slow.po
Format: COFF-x86-64
Arch: x86_64
AddressSize: 64bit
Relocations [
  Section (1) .text {
    0xB IMAGE_REL_AMD64_REL32 .refptr.user_hook (10)
    0x1F IMAGE_REL_AMD64_REL32 .refptr.user_hook (10)
    0x4D IMAGE_REL_AMD64_REL32 power2 (24)
  }
  Section (5) .rdata$.refptr.user_hook {
    0x0 IMAGE_REL_AMD64_ADDR64 user_hook (28)
  }

$ llvm-readobj.exe -t clang/power_slow.po

File: clang/power_slow.po
Format: COFF-x86-64
Arch: x86_64
AddressSize: 64bit
Symbols [

...

  Symbol {
    Name: .rdata$.refptr.user_hook
    Value: 0
    Section: .rdata$.refptr.user_hook (5)
    BaseType: Null (0x0)
    ComplexType: Null (0x0)
    StorageClass: Static (0x3)
    AuxSymbolCount: 1
    AuxSectionDef {
      Length: 8
      RelocationCount: 1
      LineNumberCount: 0
      Checksum: 0x0
      Number: 5
      Selection: Any (0x2)
    }
  }
  Symbol {
    Name: .refptr.user_hook
    Value: 0
    Section: .rdata$.refptr.user_hook (5)
    BaseType: Null (0x0)
    ComplexType: Null (0x0)
    StorageClass: External (0x2)
    AuxSymbolCount: 0
  }

...

  Symbol {
    Name: power2
    Value: 0
    Section: IMAGE_SYM_UNDEFINED (0)
    BaseType: Null (0x0)
    ComplexType: Null (0x0)
    StorageClass: WeakExternal (0x69)
    AuxSymbolCount: 1
    AuxWeakExternal {
      Linked: .weak.power2.default.power3 (26)
      Search: Alias (0x3)
    }
  }
  Symbol {
    Name: .weak.power2.default.power3
    Value: 0
    Section: .text (1)
    BaseType: Null (0x0)
    ComplexType: Function (0x2)
    StorageClass: External (0x2)
    AuxSymbolCount: 0
  }
  Symbol {
    Name: power3
    Value: 64
    Section: .text (1)
    BaseType: Null (0x0)
    ComplexType: Function (0x2)
    StorageClass: External (0x2)
    AuxSymbolCount: 0
  }
  Symbol {
    Name: user_hook
    Value: 0
    Section: IMAGE_SYM_UNDEFINED (0)
    BaseType: Null (0x0)
    ComplexType: Null (0x0)
    StorageClass: WeakExternal (0x69)
    AuxSymbolCount: 1
    AuxWeakExternal {
      Linked: .weak.user_hook.default.power3 (30)
      Search: Alias (0x3)
    }
  }
  Symbol {
    Name: .weak.user_hook.default.power3
    Value: 0
    Section: IMAGE_SYM_ABSOLUTE (-1)
    BaseType: Null (0x0)
    ComplexType: Null (0x0)
    StorageClass: External (0x2)
    AuxSymbolCount: 0
  }

...

]
```

</details>

<details>
<summary>GCC symbols:</summary>

```
$ llvm-readobj.exe -r gcc/power_slow.po

File: gcc/power_slow.po
Format: COFF-x86-64
Arch: x86_64
AddressSize: 64bit
Relocations [
  Section (1) .text {
    0xE IMAGE_REL_AMD64_REL32 .refptr.user_hook (29)
    0x18 IMAGE_REL_AMD64_REL32 user_hook (33)
    0x37 IMAGE_REL_AMD64_REL32 power2 (31)
  }

...

  Section (12) .rdata$.refptr.user_hook {
    0x0 IMAGE_REL_AMD64_ADDR64 user_hook (33)
  }

$ llvm-readobj.exe -t gcc/power_slow.po

File: gcc/power_slow.po
Format: COFF-x86-64
Arch: x86_64
AddressSize: 64bit
Symbols [

...

  Symbol {
    Name: .rdata$.refptr.user_hook
    Value: 0
    Section: .rdata$.refptr.user_hook (12)
    BaseType: Null (0x0)
    ComplexType: Null (0x0)
    StorageClass: Static (0x3)
    AuxSymbolCount: 1
    AuxSectionDef {
      Length: 8
      RelocationCount: 1
      LineNumberCount: 0
      Checksum: 0x0
      Number: 0
      Selection: Any (0x2)
    }
  }
  Symbol {
    Name: power3
    Value: 40
    Section: .text (1)
    BaseType: Null (0x0)
    ComplexType: Function (0x2)
    StorageClass: External (0x2)
    AuxSymbolCount: 1
    AuxFunctionDef {
      TagIndex: 0
      TotalSize: 0
      PointerToLineNumber: 0x0
      PointerToNextFunction: 0x0
    }
  }

...

  Symbol {
    Name: .weak.power2.power3
    Value: 0
    Section: .text (1)
    BaseType: Null (0x0)
    ComplexType: Null (0x0)
    StorageClass: External (0x2)
    AuxSymbolCount: 0
  }
  Symbol {
    Name: .refptr.user_hook
    Value: 0
    Section: .rdata$.refptr.user_hook (12)
    BaseType: Null (0x0)
    ComplexType: Null (0x0)
    StorageClass: External (0x2)
    AuxSymbolCount: 0
  }
  Symbol {
    Name: .weak.user_hook.power3
    Value: 0
    Section: IMAGE_SYM_ABSOLUTE (-1)
    BaseType: Null (0x0)
    ComplexType: Null (0x0)
    StorageClass: External (0x2)
    AuxSymbolCount: 0
  }
  Symbol {
    Name: power2
    Value: 0
    Section: IMAGE_SYM_UNDEFINED (0)
    BaseType: Null (0x0)
    ComplexType: Function (0x2)
    StorageClass: WeakExternal (0x69)
    AuxSymbolCount: 1
    AuxWeakExternal {
      Linked: .weak.power2.power3 (28)
      Search: NoLibrary (0x1)
    }
  }
  Symbol {
    Name: user_hook
    Value: 0
    Section: IMAGE_SYM_UNDEFINED (0)
    BaseType: Null (0x0)
    ComplexType: Function (0x2)
    StorageClass: WeakExternal (0x69)
    AuxSymbolCount: 1
    AuxWeakExternal {
      Linked: .weak.user_hook.power3 (30)
      Search: NoLibrary (0x1)
    }
  }
]
```

</details>

Especially this seems interesting:
```
Clang:
  Section (1) .text {
    0xB IMAGE_REL_AMD64_REL32 .refptr.user_hook (10)
    0x1F IMAGE_REL_AMD64_REL32 .refptr.user_hook (10)
    0x4D IMAGE_REL_AMD64_REL32 power2 (24)
  }

GCC:
  Section (1) .text {
    0xE IMAGE_REL_AMD64_REL32 .refptr.user_hook (29)
    0x18 IMAGE_REL_AMD64_REL32 user_hook (33)
    0x37 IMAGE_REL_AMD64_REL32 power2 (31)
  }
```
So apparently GCC (AS?) creates relocation for `user_hook` but this symbol has no section allocated.
Also Clang creates `.weak.user_hook.default.power3` while GCC creates `.weak.user_hook.power3`.

Here are assembly and objects if you want to play with it until I can do something more:
[objects.zip](https://github.com/msys2/MINGW-packages/files/5285759/objects.zip)

**Comment by jeremyd2019** [comment] 2021-04-01 18:08
This should be fixed by #8259 as well.

**Comment by lazka** [comment] 2021-04-01 21:00
The fix is in the repo now.

**Comment by lazka** [comment] 2021-04-23 14:12
Assuming this is fixed. If not we can re-open this.

**Closed by lazka** 2021-04-23 14:12 UTC
