### ISSUE TITLE
GTK app crash when pasting from clipboard

### ISSUE THREAD

**Issue by Adriatic1** [msys2/MINGW-packages#13282] opened 2022-09-29 13:05 UTC
### Description

I have a program built using GTK 3.x library, using Msys2/Mingw64 for Windows build.
Everything worked OK so far until 3 days ago when I updated all Mingw64 packages and rebuilt the program.

Now I get the following crash when I try to paste any text into any edit widget within the program:
14:34:18.816 00007FF7B4CEF7C7 (notecase): (filename not available): atexit
14:34:18.887 00007FF7B4CE3EA9 (notecase): (filename not available): atexit
14:34:18.968 00007FF7B4CE3ACF (notecase): (filename not available): atexit
14:34:19.038 00007FF7B4CE3B17 (notecase): (filename not available): atexit
14:34:19.069 00007FF7B4DAE922 (notecase): (filename not available): __p__fmode
14:34:19.069 00007FFECA4C7FF8 (msvcrt): (filename not available): _C_specific_handler
14:34:19.069 00007FFECAA5235F (ntdll): (filename not available): _chkstk
14:34:19.069 00007FFECAA014A4 (ntdll): (filename not available): RtlRaiseException
14:34:19.069 00007FFECAA50E8E (ntdll): (filename not available): KiUserExceptionDispatcher
14:34:19.069 00007FFE7AC48FA7 (libglib-2.0-0): (filename not available): g_hash_table_lookup
14:34:19.069 00007FFE7A6186AD (libgdk-3-0): (filename not available): gdk_win32_screen_get_type
14:34:19.069 00007FFE7A619EB5 (libgdk-3-0): (filename not available): gdk_win32_screen_get_type
14:34:19.069 00007FFE7A5DBBF7 (libgdk-3-0): (filename not available): gdk_selection_convert
14:34:19.069 00007FFE79D4705B (libgtk-3-0): (filename not available): gtk_selection_convert
14:34:19.372 00007FF7B49A409E (notecase): (filename not available): atexit
14:34:19.372 00007FFE9BD27C5C (libgobject-2.0-0): (filename not available): g_closure_invoke
14:34:19.372 00007FFE9BD3AB14 (libgobject-2.0-0): (filename not available): g_param_spec_variant
14:34:19.372 00007FFE9BD40D4C (libgobject-2.0-0): (filename not available): g_signal_emit_valist
14:34:19.372 00007FFE9BD40E98 (libgobject-2.0-0): (filename not available): g_signal_emit
14:34:19.372 00007FFE79E05CAF (libgtk-3-0): (filename not available): gtk_widget_can_activate_accel
14:34:19.372 00007FFE9BD27C5C (libgobject-2.0-0): (filename not available): g_closure_invoke
14:34:19.372 00007FFE9BD3AB14 (libgobject-2.0-0): (filename not available): g_param_spec_variant
14:34:19.372 00007FFE9BD40748 (libgobject-2.0-0): (filename not available): g_signal_emit_valist
14:34:19.372 00007FFE9BD40E98 (libgobject-2.0-0): (filename not available): g_signal_emit
14:34:19.372 00007FFE79B7AA73 (libgtk-3-0): (filename not available): gtk_accel_group_activate
14:34:19.372 00007FFE79B7C0F2 (libgtk-3-0): (filename not available): gtk_accel_groups_activate
14:34:19.372 00007FFE79E28F63 (libgtk-3-0): (filename not available): gtk_window_activate_key
14:34:19.372 00007FFE79E29201 (libgtk-3-0): (filename not available): gtk_window_activate_key
14:34:19.372 00007FFE79B62D03 (libgtk-3-0): (filename not available): (function-name not available)
14:34:19.372 00007FFE9BD27E74 (libgobject-2.0-0): (filename not available): g_closure_invoke
14:34:19.372 00007FFE9BD403D7 (libgobject-2.0-0): (filename not available): g_signal_emit_valist
14:34:19.372 00007FFE9BD40E98 (libgobject-2.0-0): (filename not available): g_signal_emit
14:34:19.372 00007FFE79E03E65 (libgtk-3-0): (filename not available): gtk_requisition_copy
14:34:19.372 00007FFE79CB9E6F (libgtk-3-0): (filename not available): gtk_lock_button_set_permission
14:34:19.372 00007FFE79CBBA27 (libgtk-3-0): (filename not available): gtk_main_do_event
14:34:19.372 00007FFE7A5CF139 (libgdk-3-0): (filename not available): gdk_event_free
14:34:19.372 00007FFE7A607EB0 (libgdk-3-0): (filename not available): gdk_win32_drag_context_get_type
14:34:19.372 00007FFE7AC58783 (libglib-2.0-0): (filename not available): g_clear_list
14:34:19.372 00007FFE7AC5B828 (libglib-2.0-0): (filename not available): g_main_context_check
14:34:19.372 00007FFE7AC5BCF0 (libglib-2.0-0): (filename not available): g_main_loop_run
14:34:19.372 00007FFE79CBAC6D (libgtk-3-0): (filename not available): gtk_main
14:34:19.534 00007FF7B4B66381 (notecase): (filename not available): atexit
14:34:19.534 00007FF7B4E1793A (notecase): (filename not available): __DTOR_LIST__
14:34:19.534 C:\_\M\mingw-w64-crt-git\src\mingw-w64\mingw-w64-crt\crt\crtexe.c (321): __tmainCRTStartup
14:34:19.534 C:\_\M\mingw-w64-crt-git\src\mingw-w64\mingw-w64-crt\crt\crtexe.c (178): WinMainCRTStartup
14:34:19.534 00007FFEC99A7034 (KERNEL32): (filename not available): BaseThreadInitThunk
14:34:19.534 00007FFECAA026A1 (ntdll): (filename not available): RtlUserThreadStart

This worked OK with the previous set of packages, new package versions are:
mingw64/mingw-w64-x86_64-gtk3 3.24.34+87+g8bbc24c165-3 [installed]
mingw64/mingw-w64-x86_64-glib2 2.74.0-1 [installed]

Interesting thing, if I do a clipboard copy action from within the same program, then subsequent paste actions will work OK.
Anyway, since this worked before the package update, I suspect this to be a bug in the new package.

Does anyone have similar issues? Any tips ?
Thanks!

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 10.0.19044.2006]

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

Program should not crash on paste.

### Actual behavior

Crash on paste, see backtrace above.

### Repro steps

Steps:
1. download and install the program from: https://notecase.sourceforge.net/temp/notecase_pro-4.6.7_mingw64_gtk3_pre3.exe
2. copy (to clipboard) some text in any other program
3. start the test program, try to paste to any edit box
4. crash

**Comment by Biswa96** [comment] 2022-09-29 13:09
Duplicate of https://github.com/msys2/MINGW-packages/issues/13258.

**Closed by Biswa96** 2022-09-29 13:09 UTC
Labels: bug
