### ISSUE TITLE
Program using Magick++ is broken after going through the last imagemagick upgrade.

### ISSUE THREAD

**Issue by shithappens2016** [msys2/MINGW-packages#13537] opened 2022-10-12 04:46 UTC
### Description

The program uses imagemagick's modules including filters and coders.

This should be related to several recent merges.

#13499

#13287

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

win10

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment] 2022-10-12 04:49
Please provide steps to reproduce the issue.

**Comment by shithappens2016** [comment] 2022-10-12 04:57
@Biswa96

What I can tell you is that the problem goes away after rolling back to an older version of imagemagick and the program uses imagemagick's modules including filers and coders.

**Comment by Biswa96** [comment] 2022-10-12 05:03
But in those both pull requests @kmilos verified that Darktable works without any issue. It would be helpful to reproduce the issue with any project or minimal example code.

**Comment by shithappens2016** [comment] 2022-10-12 05:09
@Biswa96 
It should be related to MAGICK_CODER_MODULE_PATH.

**Comment by Biswa96** [comment] 2022-10-12 05:10
Without steps to reproduce the issue, it is not possible to help in any way.

**Comment by shithappens2016** [comment] 2022-10-12 05:23
@Biswa96 
I suggest you withdraw the recent merge. Solving ridiculous problems like `magick -list format not working` increases the chances of creating more serious problems.

**Comment by Biswa96** [comment] 2022-10-12 05:30
`magick -list format` not showing any output is a valid and serious issue. The empty output means the program can not find and scan the coders directory.

**Comment by shithappens2016** [comment] 2022-10-12 05:37
@Biswa96 
Maybe a safer way to solve the problem of `magick -list format not working` is just to set the environment variable (MAGICK_CODER_MODULE_PATH).

**Comment by Biswa96** [comment] 2022-10-12 05:39
> Your patch obviously creates more terrible problems.

Proof?

**Comment by shithappens2016** [comment] 2022-10-12 05:54
> But in those both pull requests @kmilos verified that Darktable works without any issue.

Oh, they just haven't released a new version yet. Give it a little time.

**Comment by kmilos** [comment] 2022-10-12 09:39
> Oh, they just haven't released a new version yet. Give it a little time.

Just built darktable 4.1.0+493~geab9af732 master (again) w/ mingw-w64-ucrt-x86_64-imagemagick-7.1.0.50-1.

Works for me (e.g. PAM import not supported natively by dt). Note that dt uses only the MagickWand API; also, I run from the UCRT64 bash terminal (no relocation).

**Comment by MehdiChinoune** [comment] 2022-10-15 19:58
Shouldn't we close this issue because of the missing reproducer?

**Comment by Biswa96** [comment] 2022-10-16 13:08
I'm waiting if someone can provide any code to reproduce the issue.

**Comment by kmilos** [comment] 2022-12-26 15:45
@Biswa96 @MehdiChinoune Actually there might be something to this - I just tried on a new install and hit the issue described with a darktable build. It turns out I had `C:\msys64\ucrt64\bin` in my `PATH` before, which made it (falsely) work, so I guess it's some shared object missing somewhere?

Please reopen, and I'll try to provide a reproducer...

**Comment by kmilos** [comment] 2022-12-26 16:11
Turns out when you're doing the relocation it only works if you have the both coder `.la` file as well next to the coder DLL (not sure why?), and all the shared libs in the current binary directory that the coder depends on obviously.

**Comment by Biswa96** [comment] 2022-12-27 14:29
Do you mean you want to use imagmagick without those libtool files? But I think that it is required for the modules. In the configure.ac file, it is specified that "libltdl is required for modules and OpenCL builds". That defines MAGICKCORE_LTDL_DELEGATE macro and enables the `.la` requirement (see MagickCore/module.c).

**Comment by kmilos** [comment] 2022-12-27 14:34
> Do you mean you want to use imagmagick without those libtool files?

No, I just didn't expect them to be required - e.g. GraphicsMagick seems to find and load modules fine with just the `.dll`s when relocated, and I also think they use `dlopen`...

In any case, not really an issue for me any longer - dt uses MagickWand (not Magick++), and with the `.la` + `.dll` modules, and the other required shared libraries those modules depend on somewhere in the `PATH`, everything seems to be working out.

**Comment by Biswa96** [comment] 2022-12-27 14:43
It is possible to modify the configure.ac and module.c file to change the behavior. But that would change the expected behavior in many ways. In the whole project, MAGICKCORE_LTDL_DELEGATE and MAGICKCORE_WINDOWS_SUPPORT are kind of mutually exclusive. If the later one is enabled the logic will search for different modules DLL names. That kind of DLL names are set using Visual Studio projects.

So, I guess it is not an issue, right?

**Comment by kmilos** [comment] 2022-12-27 14:46
> So, I guess it is not an issue, right?

I guess not, thanks.

**Closed** 2022-12-27 14:46 UTC
Labels: bug
