### ISSUE TITLE
build cpprestsdk failed

### ISSUE THREAD

**Issue by 19504643** [msys2/MINGW-packages#7348] opened 2020-11-29 02:08 UTC
The C++ REST SDK is a Microsoft project for cloud-based client-server communication in native code using a modern asynchronous C++ API design
[https://github.com/microsoft/cpprestsdk](url)
but it built failed with MingW64,
![image](https://user-images.githubusercontent.com/4372492/100530258-b7e22b00-322a-11eb-85ee-1470c7ffd54e.png)

could you please make a package of this lib, thanks

**Comment by Biswa96** [comment] 2020-11-29 03:38
Please provide steps to reproduce your issue.

**Comment by 19504643** [comment] 2020-11-29 15:47
@Biswa96 
Steps are as follows:
1. git clone https://github.com/Microsoft/cpprestsdk.git
2. cd cpprestsdk
3. git checkout v2.10.16
4. git submodule update --init
5. mkdir build
6. cd build
7. cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
8. mingw32-make.exe
and the errors come

**Comment by Biswa96** [comment] 2020-11-29 16:23
Related to upstream issue https://github.com/microsoft/cpprestsdk/issues/798. If that will be fixed add `-DWERROR=OFF` in CMake command. Microsoft don't care about GCC unless there is a profit 🤑

**Comment by 19504643** [comment] 2020-11-30 12:55
@Biswa96 
Tks, still some errors:
![image](https://user-images.githubusercontent.com/4372492/100612715-616e0d00-334e-11eb-8609-2ff5c7c15563.png)

**Comment by Ruben22Inigo** [comment] 2023-06-21 19:05
Have you solved this errors?
I'm exactly on the same situation.
Thx,

**Comment by Biswa96** [comment] 2023-06-21 19:37
It seems that the project does not support mingw toolchain. Fixing one compiler error would not be enough. Also the project is in maintenance mode and do not recommend its use in new projects.

**Closed by Biswa96** 2023-06-21 19:37 UTC

**Comment by Soufianeelkabil** [comment] 2023-06-22 11:58
Please have you solve this problem, because I am in the same error?

**Comment by Biswa96** [comment] 2023-06-22 12:20
The project has to be modified in many places to port it for mingw toolchain.

**Comment by Soufianeelkabil** [comment] 2023-06-22 12:26
Can you please provide more details

**Comment by Biswa96** [comment] 2023-06-22 12:30
Many macros in that project are for MSVC. So, you have to port that to some standard ones which can be compiled with mingw toolchain.
