### ISSUE TITLE
mingw gcc-12 cannot compile c++20 modules with mapper file

### ISSUE THREAD

**Issue by waruqi** [msys2/MINGW-packages#12797] opened 2022-08-25 06:09 UTC
It does not work when I use gcc 12 to build c++ modules with mapper file.

```console
ruki@ruki-PC MINGW64 /z/personal/xmake/tests/projects/c++/modules/hello
$ cat src/hello.mpp
module;
#include <cstdio>

export module hello;

export namespace hello {
    void say(const char* str) {
        printf("%s\n", str);
    }
}

ruki@ruki-PC MINGW64 /z/personal/xmake/tests/projects/c++/modules/hello
$ cat build/mapper.txt
hello build/hello.gcm

ruki@ruki-PC MINGW64 /z/personal/xmake/tests/projects/c++/modules/hello
$ x86_64-w64-mingw32-g++ -m64 -std=c++20 -fmodules-ts -fmodule-mapper=build/mapper.txt -D_GLIBCXX_USE_CXX11_ABI=0 -x c++ -o build/.objs/hello/mingw/x86_64/release/src/hello.mpp.obj -c src/hello.mpp
src/hello.mpp:4:8: error: unknown Compiled Module Interface: no such module
    4 | export module hello;
      |        ^~~~~~
src/hello.mpp:4:8: warning: not writing module 'hello' due to errors
```

But it works if I remove `-fmodule-mapper=build/mapper.txt ` argument.

```console
ruki@ruki-PC MINGW64 /z/personal/xmake/tests/projects/c++/modules/hello
$ x86_64-w64-mingw32-g++ -m64 -std=c++20 -fmodules-ts -D_GLIBCXX_USE_CXX11_ABI=0 -x c++ -o build/.objs/hello/mingw/x86_64/release/src/hello.mpp.obj -c src/hello.mpp
```

When I use gcc-11 on my ubuntu, It always work for me. 

```console
$ gcc --version
gcc (Ubuntu 11.3.0-5ubuntu1) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ gcc -m64 -std=c++20 -fmodules-ts -fmodule-mapper=build/mapper.txt -D_GLIBCXX_USE_CXX11_ABI=0 -x c++ -o build/.objs/hello/mingw/x86_64/release/src/hello.mpp.obj -c src/hello.mpp
```

There seems to be a difference in the support for c++20 modules between mingw gcc-12 and linux gcc-12.

see https://github.com/xmake-io/xmake/issues/2716#event-7255383218

**Comment by MehdiChinoune** [comment] 2022-08-25 06:25
You are comparing gcc-11 on Ubuntu with gcc-12 on MSYS2, Please test gcc-12 on Ubuntu.

**Comment by waruqi** [comment] 2022-08-25 06:37
> You are comparing gcc-11 on Ubuntu with gcc-12 on MSYS2, Please test gcc-12 on Ubuntu.

It also works for gcc12 on ubuntu

```console
$ gcc-12 -m64 -std=c++20 -fmodules-ts -fmodule-mapper=build/mapper.txt -D_GLIBCXX_USE_CXX11_ABI=0 -x c++ -o build/.objs/hello/mingw/x86_64/release/src/hello.mpp.obj -c src/hello.mpp
```

**Comment by Biswa96** [comment] 2022-08-25 06:43
The gcc command itself is working fine in mingw environment.

**Comment by waruqi** [comment] 2022-08-25 06:46
> The gcc command itself is working fine in mingw environment.

right, but there are only some differences in the support for mapper files and c++ modules.

**Comment by mati865** [comment] 2022-08-27 11:42
Sounds like something that should be reported to GGC developers.

**Comment by waruqi** [comment] 2022-08-27 12:42
Is it a bug of gcc?

**Comment by mati865** [comment] 2022-08-27 12:55
Well, you have confirmed it works with GCC on Linux but doesn't work on Windows (with our patches). Although using unpatched GCC on Windows could be more meaning ful there is no easy way to do it.
So it's either one of MSYS2 patches or GCC itself.

**Comment by revelator** [comment] 2022-09-27 10:40
path problem maybe ? would not be the first time ...
does it work if you use windows or mixed mode paths ?.

**Comment by MehdiChinoune** [comment] 2023-05-14 08:11
It seems to be fixed with GCC-13
```
g++ -std=c++20 -fmodules-ts -fmodule-mapper=mapper.txt -D_GLIBCXX_USE_CXX11_ABI=0 -x c++ -o hello.o -c hello.mpp
```
works for me
@waruqi could you confirm

**Comment by waruqi** [comment] 2023-05-14 14:12
> It seems to be fixed with GCC-13
> 
> ```
> g++ -std=c++20 -fmodules-ts -fmodule-mapper=mapper.txt -D_GLIBCXX_USE_CXX11_ABI=0 -x c++ -o hello.o -c hello.mpp
> ```
> 
> works for me @waruqi could you confirm

It does not work for me.

```console
ruki@RUKI052A MINGW64 /y/personal/xmake/tests/projects/c++/modules/hello
$ cat build/hello/mapper.txt
hello build/hello.gcm

ruki@RUKI052A MINGW64 /y/personal/xmake/tests/projects/c++/modules/hello
$ x86_64-w64-mingw32-g++ -c -x c++ -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++20 -fmodules-ts -fmodule-mapper=build/hello/mapper.txt -D_GLIBCXX_USE_CXX11_ABI=0 -DNDEBUG -o build/.objs/hello/mingw/x86_64/release/src/hello.mpp.obj src/hello.mpp
src/hello.mpp:4:8: error: unknown Compiled Module Interface: no such module
    4 | export module hello;
      |        ^~~~~~
src/hello.mpp:4:8: warning: not writing module 'hello' due to errors

ruki@RUKI052A MINGW64 /y/personal/xmake/tests/projects/c++/modules/hello
$ x86_64-w64-mingw32-g++  --version
x86_64-w64-mingw32-g++.exe (Rev5, Built by MSYS2 project) 13.1.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by MehdiChinoune** [comment] 2023-05-14 14:58
Could you use less compile flags and try again
BTW `-m64` doesn't do nothing on MSYS2 GCC.

**Comment by MehdiChinoune** [comment] 2023-05-14 15:07
@Biswa96 Could you test it to confirm.

**Comment by Biswa96** [comment] 2023-05-14 17:39
>  g++ -c -x c++ -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++20 -fmodules-ts -fmodule-mapper=build/hello/mapper.txt -D_GLIBCXX_USE_CXX11_ABI=0 -DNDEBUG src/hello.mpp

Yup, it worked.

**Closed** 2023-05-14 18:29 UTC

**Comment by waruqi** [comment] 2023-05-15 01:57
> 


> Could you use less compile flags and try again BTW `-m64` doesn't do nothing on MSYS2 GCC.
> 
> Edit: It works here with your flags
> 
> ```
> $ tree
> .
> |-- build
> |   `-- hello
> |       `-- mapper.txt
> `-- src
>     `-- hello.mpp
> 
> 3 directories, 2 files
> 
> $ cat src/hello.mpp
> module;
> #include <cstdio>
> 
> export module hello;
> 
> export namespace hello {
>     void say(const char* str) {
>         printf("%s\n", str);
>     }
> }
> 
> $ cat build/hello/mapper.txt
> hello build/hello/hello.gcm
> 
> $ x86_64-w64-mingw32-g++ -c -x c++ -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++20 -fmodules-ts -fmodule-mapper=build/hello/mapper.txt -D_GLIBCXX_USE_CXX11_ABI=0 -DNDEBUG -o build/.objs/hello/mingw/x86_64/release/src/hello.mpp.obj src/hello.mpp
> ```

But it still does not work for me.

**Comment by waruqi** [comment] 2023-05-15 02:04
> > g++ -c -x c++ -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++20 -fmodules-ts -fmodule-mapper=build/hello/mapper.txt -D_GLIBCXX_USE_CXX11_ABI=0 -DNDEBUG src/hello.mpp
> 
> Yup, it worked.
> 
> ```
> $ gcc --version
> gcc.exe (Rev5, Built by MSYS2 project) 13.1.0
> Copyright (C) 2023 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 
> $ which gcc
> /ucrt64/bin/gcc
> ```

I use `x86_64-w64-mingw32-g++` in /mingw64/bin. not ucrt64 gcc

**Comment by revelator** [comment] 2023-05-15 04:57
might still be some incompatibilities with ucrt and c++20 both are pretty recent additions.
