### ISSUE TITLE
lld --allow-multiple-definition

### ISSUE THREAD

**Issue by smf-** [msys2/MINGW-packages#6855] opened 2020-08-22 17:18 UTC
I'm trying to link a project to lld because it's substantially faster & it works fine with g++, but not clang++
I've attached some source which highlights the issue.

clang++ t.cpp -fuse-ld=lld --static
fails with errors like:
lld-link: error: duplicate symbol: typeinfo name for std::exception
>>> defined at C:\Users\....\AppData\Local\Temp\t-c0fb17.o
>>> defined at libstdc++.a(eh_alloc.o)

Normally with clang++ we use --allow-multiple-definition but it isn't supported
clang++ t.cpp -fuse-ld=lld --static -Wl,--allow-multiple-definition
lld: error: unknown argument: --allow-multiple-definition

I've tried using libc++ and while it works for this test
clang++ t.cpp -fuse-ld=lld --static -stdlib=libc++

It's not compatible with the project due to other errors (which I've so far failed to create a test case for)
lld-link: error: undefined symbol: std::basic_streambuf<char, std::char_traits<char> >::imbue(std::locale const&)
lld-link: error: undefined symbol: std::ostream::put(char)

Any help would be appreciated.

#include &lt;stdexcept&gt;

int main(int argc, char *argv[])
{
	try
	{
		throw std::runtime_error("error");
	}
	catch(...)
	{
	}
}

**Comment by mstorsjo** [comment] 2020-08-23 20:43
In general, it should be straightforward to add the `--allow-multiple-definition` option in the lld mingw frontend. But in most cases, I'd recommend against using it, as one normally really should resolve those issues.

I'll see if I can reproduce the issues myself somewhere, but in the meantime, a general hunch: So this is when linking a gcc-built static libstdc++ with clang-built object files, using either lld or ld.bfd? That's weird. It sounds like a case where clang and gcc do things vaguely differently, and this explodes when linking statically, as there might be functions/data sections, that are included in multiple object files (e.g. like inline functions), but they're expected to be identical in all object files. That's a bit tricky.

I'll see (later) if I can reproduce it and give a more informed comment...

**Comment by mati865** [comment] 2020-08-24 12:36
> So this is when linking a gcc-built static libstdc++ with clang-built object files, using either lld or ld.bfd?

Exactly.

**Comment by mstorsjo** [comment] 2020-08-26 12:51
So, I had a closer look at this, and here's a braindump of the issue - I don't have a finished solution yet (but forcing it with that flag, `--allow-multiple-definition` in current git, or `-Xlink=-force:multiple` in existing versions, coupled with the usual `-Wl,`, should work for this issue, but that also masks many other issues). [By the time I had finished typing this, I have a patch at least.]

The issue is that the symbol `_ZTSSt9exception` gets emitted in multiple object files, both within libstdc++ and the clang-built user code object file. It's emitted as a so-called comdat, that allows multiple objects to provide the same thing, without conflicts (e.g. for things like inline functions, or C++ typeinfo like this is).

For each comdat, there's a selection field that says how conflicts are to be resolved, `IMAGE_COMDAT_SELECT_ANY` that says just discard all definitions but one, doesn't matter much if they differ, `IMAGE_COMDAT_SELECT_EXACT_MATCH` that allows multiple definitions provided that they're exact matches of each other, and `IMAGE_COMDAT_SELECT_SAME_SIZE` that allows multiple definitions, don't look at the contents but require them to be the same size.

In this case, clang emits `_ZTSSt9exception` as `IMAGE_COMDAT_SELECT_ANY`, while gcc/binutils emits it as `IMAGE_COMDAT_SELECT_SAME_SIZE`.

Normally, a linker would flat out reject this situation, if the selection types don't match, then they can't substitute each other. But lld has an exception for mingw interop between clang and gcc; `IMAGE_COMDAT_SELECT_SAME_SIZE` and `IMAGE_COMDAT_SELECT_ANY` can interoperate as if both were `IMAGE_COMDAT_SELECT_SAME_SIZE`, see https://github.com/llvm/llvm-project/commit/9dbc1ab23268abce5db98ad9a1e3aef89c371524. I'm not sure, but it might the case that linking with ld.bfd fails at this issue.

The next issue, when linking with lld, is that binutils seems to pad its section size to a multiple of 4, while llvm doesn't. So for the clang built object file, the comdat section holding `_ZTSSt9exception` is 13 bytes, while the gcc built one is 16 bytes.

```
$ obj2yaml clang.o
[...]
  - Name:            '.rdata$_ZTSSt9exception'
    Characteristics: [ IMAGE_SCN_CNT_INITIALIZED_DATA, IMAGE_SCN_LNK_COMDAT, IMAGE_SCN_MEM_READ ]
    Alignment:       1
    SectionData:     537439657863657074696F6E00
[...]
  - Name:            '.rdata$_ZTSSt9exception'
    Value:           0
    SectionNumber:   7
    SimpleType:      IMAGE_SYM_TYPE_NULL
    ComplexType:     IMAGE_SYM_DTYPE_NULL
    StorageClass:    IMAGE_SYM_CLASS_STATIC
    SectionDefinition:
      Length:          13
      NumberOfRelocations: 0
      NumberOfLinenumbers: 0
      CheckSum:        3269445437
      Number:          7
      Selection:       IMAGE_COMDAT_SELECT_ANY
[...]
$ obj2yaml gcc.o
[...]
  - Name:            '.rdata$_ZTSSt9exception' 
    Characteristics: [ IMAGE_SCN_CNT_INITIALIZED_DATA, IMAGE_SCN_LNK_COMDAT, IMAGE_SCN_MEM_READ ]
    Alignment:       16
    SectionData:     537439657863657074696F6E00000000
[...]
  - Name:            '.rdata$_ZTSSt9exception'
    Value:           0
    SectionNumber:   10
    SimpleType:      IMAGE_SYM_TYPE_NULL
    ComplexType:     IMAGE_SYM_DTYPE_NULL
    StorageClass:    IMAGE_SYM_CLASS_STATIC
    SectionDefinition:
      Length:          13
      NumberOfRelocations: 0
      NumberOfLinenumbers: 0
      CheckSum:        0
      Number:          0
      Selection:       IMAGE_COMDAT_SELECT_SAME_SIZE
```

Now the thing is that the binutils provided object files does contain the real, non-padded size in the SectionDefinition (`coff_aux_section_definition` in lld), but we don't always have this struct readily available when checking for comdat collisions in lld. Or more precisely, when parsing a new object file, we do have the `coff_aux_section_definition` for that object file, but we don't easily have the `coff_aux_section_definition` of the previously parsed object file.

So to fix it, at https://github.com/llvm/llvm-project/blob/e524daa7e8719f4b43e6ebcf25fd4e7d74c5d1c4/lld/COFF/InputFiles.cpp#L660 we can easily pass `def` to `handleComdatSelection`, but at https://github.com/llvm/llvm-project/blob/e524daa7e8719f4b43e6ebcf25fd4e7d74c5d1c4/lld/COFF/InputFiles.cpp#L543 we'd also need the `coff_aux_section_definition` associated with `leaderChunk`, and compare the sizes between those, instead of checking the sizes of the `SectionChunk`s. Or maybe store the size from the original def in a new field in `SectionChunk` around https://github.com/llvm/llvm-project/blob/e524daa7e8719f4b43e6ebcf25fd4e7d74c5d1c4/lld/COFF/InputFiles.cpp#L273-L275. That does increase the size of `SectionChunk` (and a nontrivial effort has gone into keeping these objects as small as possible, so new fields shouldn't be added lightly there).

The latter actually wasn't too hard to implement, so with https://martin.st/temp/0001-LLD-COFF-Check-the-aux-section-definition-size-for-I.patch, linking does seem to succeed for me. (The patch is missing a testcase before it can be sent upstream.)

**Comment by mati865** [comment] 2020-08-26 14:23
Thanks for this wonderful analysis.

Sounds like this ideally should be fixed in GCC by emitting `IMAGE_COMDAT_SELECT_ANY`.

**Comment by sphoto** [comment] 2021-01-14 09:44
Any news on this topic? I am fighting with the same issue...

**Comment by mstorsjo** [comment] 2021-01-14 10:11
The fix to LLD was made in https://reviews.llvm.org/D86659, so it will become part of the LLVM 12 release which is due in a couple months. If you have an opportunity to backport the patch to an existing release and build it yourself, or build the latest git version of lld, you should be able to grab the fix right now. (I don't have a recent enough build of lld for windows myself right now.)

**Comment by Biswa96** [comment] 2021-05-06 06:11
This issue block postgresql build with clang:

```
lld-link: error: duplicate symbol: getopt
>>> defined at libpgport.a(getopt.o)
>>> defined at C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/misc/getopt.c:524
>>>            libmingwex.a(lib64_libmingwex_a-getopt.o)
```

**Comment by mstorsjo** [comment] 2021-05-06 06:26
> This issue block postgresql build with clang:
> 
> ```
> lld-link: error: duplicate symbol: getopt
> >>> defined at libpgport.a(getopt.o)
> >>> defined at C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/misc/getopt.c:524
> >>>            libmingwex.a(lib64_libmingwex_a-getopt.o)
> ```

No, resorting to `--allow-multiple-definition` is wrong as the first step. It should be the very last step after the full issue is completely understood and it's clear that there aren't any other solutions.

The very first question is - why doesn't this happen when building with GCC/ld.bfd? ld.bfd also errors out on multiple definitions, so it's not a case where we should make lld tolerate something that ld.bfd tolerates.

First you need to figure out why this is happening. If another object file uses the symbol `getopt`, it should load either lib64_libmingwex_a-getopt.o from libmingwex.a or getopt.o from libpgport.a, but not both.

Based on the error message, libmingwex.a(lib64_libmingwex_a-getopt.o) gets pulled in first. Then something else pulls in libpgport.a(getopt.o). Why does that object file get pulled in - if we already have the getopt symbol included. Is it because of some other function in libpgport.a(getopt.o) which is needed (but not needed when building with GCC/ld.bfd)? Does the project have ifdefs that cause an extra getopt to be included when building with clang but not with GCC? Is libpgport.a included with `--whole-archive`? Then the same error also should appear when building with GCC/ld.bfd.

Once you have a project which willingly does use `--allow-multiple-definition` with GCC/ld.bfd and can't be built without it, then we can consider adding it to lld. But until that, we should figure out what makes the actual error appear when it's not there when building with GCC/ld.bfd.

**Comment by mati865** [comment] 2021-08-01 11:44
Fixed in https://reviews.llvm.org/D86512

**Closed by mati865** 2021-08-01 11:44 UTC
