### ISSUE TITLE
[emacs] can`t load tree-sitter library after mingw-w64-x86_64-libtree-sitter updated

### ISSUE THREAD

**Issue by jidibinlin** [msys2/MINGW-packages#22518] opened 2024-11-13 08:24 UTC
### Description / Steps to reproduce the issue

1. upgrade mingw64 to latest
2. emacs -Q
3. emacs will fire a warning about loading tree-sitter library
> Warning (treesit): Cannot activate tree-sitter, because tree-sitter library is not available or failed to load

### Expected behavior

emacs loads tree-sitter properly.

### Actual behavior

I updated mingw64 through "pacman -Syu" and i noticed mingw-w64-x86_64-tree-sitter upgraded.
Then I launched emacs and got this warning.
> Warning (treesit): Cannot activate tree-sitter, because tree-sitter library is not available or failed to loaWarning (treesit): Cannot activate tree-sitter, because tree-sitter library is not available or failed to load

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANGARM64

**Comment by ognevny** [comment] 2024-11-13 08:52
fixed emacs is already available in repo. are you sure that you have installed latest version of package? please, show full version on it (`pacman -Q | grep emacs`) can help you

**Comment by jidibinlin** [comment] 2024-11-13 09:17
@ognevny mingw-w64-x86_64-emacs 29.4-2

**Comment by Biswa96** [comment] 2024-11-13 09:21
The new emacs package is in the staging repository https://packages.msys2.org/queue , please wait some time.

* Duplicate of #22508

**Closed by Biswa96** 2024-11-13 09:21 UTC
Labels: bug

**Comment by ognevny** [comment] 2024-11-13 10:20
> The new emacs package is in the staging repository https://packages.msys2.org/queue , please wait some time.

oh, I thought it's not in queue... sorry for confusion
