### ISSUE TITLE
 mingw-w64-clang-x86_64-armadillo  ld.lld: error: undefined symbol: wrapper2_* error

### ISSUE THREAD

**Issue by bmiyuan** [msys2/MINGW-packages#10556] opened 2022-01-16 12:58 UTC
I use  mingw-w64-clang-x86_64-armadillo to there's a lot of errors when link
refrence link: https://packages.msys2.org/package/mingw-w64-clang-x86_64-armadillo?repo=clang64

ld.lld: error: undefined symbol: wrapper2_dgeev_
ld.lld: error: undefined symbol: wrapper2_dgeqrf_
ld.lld: error: undefined symbol: wrapper2_dorgqr_
ld.lld: error: undefined symbol: wrapper2_dgesdd_
ld.lld: error: undefined symbol: wrapper2_dgesvd_
ld.lld: error: undefined symbol: wrapper2_dlansy_
ld.lld: error: undefined symbol: wrapper2_dpotrf_
ld.lld: error: undefined symbol: wrapper2_dpotri_
ld.lld: error: undefined symbol: wrapper2_dpocon_
ld.lld: error: undefined symbol: wrapper2_ilaenv_
ld.lld: error: undefined symbol: wrapper2_dgelsd_
ld.lld: error: undefined symbol: wrapper2_dtrtrs_
ld.lld: error: undefined symbol: wrapper2_dgesv_
ld.lld: error: undefined symbol: wrapper2_dgbsvx_
ld.lld: error: undefined symbol: wrapper2_dposvx_
ld.lld: error: undefined symbol: wrapper2_dgesvx_
ld.lld: error: undefined symbol: wrapper2_dpotrs_
ld.lld: error: undefined symbol: wrapper2_dlange_
ld.lld: error: undefined symbol: wrapper2_dgetrf_
ld.lld: error: undefined symbol: wrapper2_dgetrs_

it seems there indeed no such symbols in  libarmadillo.dll.a, only below symbols
wrapper2_cgemm_
wrapper2_cgemv_
wrapper2_cherk_
wrapper2_dasum_
wrapper2_ddot_
wrapper2_dgemm_
wrapper2_dgemv_
wrapper2_dnrm2_
wrapper2_dsyrk_
wrapper2_sasum_
wrapper2_sdot_
wrapper2_sgemm_
wrapper2_sgemv_
wrapper2_snrm2_
wrapper2_ssyrk_
wrapper2_zgemm_
wrapper2_zgemv_
wrapper2_zherk_
wrapper_cgemm_
wrapper_cgemv_
wrapper_cherk_
wrapper_dasum_
wrapper_ddot_
wrapper_dgemm_
wrapper_dgemv_
wrapper_dnrm2_
wrapper_dsyrk_
wrapper_sasum_
wrapper_sdot_
wrapper_sgemm_
wrapper_sgemv_
wrapper_snrm2_
wrapper_ssyrk_
wrapper_zgemm_
wrapper_zgemv_

**Comment by Biswa96** [comment] 2022-01-16 13:04
Thank you for reporting this issue. Please provide any minimal sample code and build command to reproduce it.

**Comment by bmiyuan** [comment] 2022-01-16 14:13
> Thank you for reporting this issue. Please provide any minimal sample code and build command to reproduce it.

it compiles successfully after disable ARMA_USE_WRAPPER and add more lib dependency of blas and lapack......

**Comment by Biswa96** [comment] 2022-01-16 15:47
The clang armadillo packages were built with different option due to unavailability of a Fortran compiler in LLVM. I am not sure if that option should be disabled. @mmuetzel may provide some information.

**Comment by bmiyuan** [comment] 2022-01-17 03:10
> The clang armadillo packages were built with different option due to unavailability of a Fortran compiler in LLVM. I am not sure if that option should be disabled. @mmuetzel may provide some information.
> 
> The build command used for armadillo can be found here https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-armadillo/PKGBUILD

yes, there's indeed an issue for load function.
if I use Debug mode to compile below test code ,it works fine, but if use release mode to compile, load can't read data.....

`  arma::mat test;
  test.load("test.txt");
  std::cout<<"test.size="<<test.size()<<std::endl;`

**test.txt data:**
[test.txt](https://github.com/msys2/MINGW-packages/files/7878752/test.txt)

**Debug Mode Result:**
test.size=182745

**Release Mode Result**
test.size=0

**Comment by mmuetzel** [comment] 2022-01-17 05:40
Sorry. I know close up nothing about armadillo. How can I help with this?

**Comment by bmiyuan** [comment] 2022-01-17 06:48
> mingw-w64-clang-x86_64-armadillo

hi Markus, do you know who creates this package mingw-w64-clang-x86_64-armadillo ? mybe he can provide us some soultions to this problem. I've no idea why load function doesn't work on release mode.....

**Comment by mmuetzel** [comment] 2022-01-17 07:25
Unfortunately, I don't have more than the publicly available information. So, I can give only very generic advice.
IIUC, armadillo is developed on GitLab. Maybe, you could ask the developers there what might be the issue:
https://gitlab.com/conradsnicta/armadillo-code

**Comment by bmiyuan** [comment] 2022-01-17 07:47
> generic

thanks Markus

**Comment by Biswa96** [comment] 2022-01-17 09:01
As armadillo does not enable arpackin clang, it shows this warning at build time:

```
ARPACK_FOUND = NO
Looking for SuperLU version 5
Could not find SuperLU
SuperLU_FOUND = NO

WARNING: Use of LAPACK is not enabled, as no LAPACK compatible library has been found.
WARNING: This will materially degrade the available functionality in Armadillo.

NOTE: OpenBLAS found but LAPACK not found.
NOTE: OpenBLAS may have been built without LAPACK functions,
NOTE: so cannot assume that LAPACK functions are available.
NOTE: To forcefully assume that OpenBLAS provides LAPACK functions,
NOTE: rerun cmake with the OPENBLAS_PROVIDES_LAPACK option enabled:
NOTE: cmake -D OPENBLAS_PROVIDES_LAPACK=true .
```

So, this may be kind of our packaging issue. Also the config.hpp says:

```c
/* #undef ARMA_USE_WRAPPER */
//// Comment out the above line if you're getting linking errors when compiling your programs,
//// or if you prefer to directly link with LAPACK, BLAS + etc instead of the Armadillo runtime library.
//// You will then need to link your programs directly with -llapack -lblas instead of -larmadillo
```

So, disabling `ARMA_USE_WRAPPER` from code may be the only option, as Yuan did above https://github.com/msys2/MINGW-packages/issues/10556#issuecomment-1013883729

**Comment by mmuetzel** [comment] 2022-01-17 10:29
Not sure if I understand correctly.
This might be a packaging issue. Or maybe armadillo shouldn't provide wrappers for functions that don't exist? But maybe they assume that even if the functions aren't available at compile time, they'll need these wrappers in case the corresponding libraries are available at run time?

Can we use `mingw-w64-f2cblaslapack` for the clang builds?

**Comment by mmuetzel** [comment] 2022-01-17 17:43
I tried depending on `f2cblaslapack` for the clang builds. With that, the warnings @Biswa96 showed disappeared.

@bmiyuan: Could you please check if you still see the "undefined symbol" errors with the artifact from that PR?
https://github.com/msys2/MINGW-packages/suites/4964714495/artifacts/144526634

**Comment by mmuetzel** [comment] 2022-01-17 17:48
Looking at this: Would it make sense to build OpenBLAS for the clang environments with the LAPACK from `f2cblaslapack`.
That version of LAPACK is old (version 3.4), probably slower than the optimized Fortran version in OpenBLAS (and might be buggy?). But it might be better having those LAPACK functions in OpenBLAS instead of none. At least as long as there is no Fortran compiler for the clang environments...
Would that even be possible?

**Comment by mmuetzel** [comment] 2022-01-18 16:24
I updated the PR so that armadillo's wrapper library should be using the OpenBLAS functions that we have in the clang environment and the remaining LAPACK functions from `f2cblaslapack`. (At least, I hope that lld does what I think it does...)

@bmiyuan: Could you please check with the updated artifact from that PR?
You can download the `clang64` artifact from here:
https://github.com/msys2/MINGW-packages/actions/runs/1713702135
Unzip it and install the test package with:
`pacman -U mingw-w64-clang-x86_64-armadillo-10.8.0-2-any.pkg.tar.zst`
Do you still see the "undefined symbol" errors with that version of armadillo?

**Comment by bmiyuan** [comment] 2022-01-20 06:28
> I updated the PR so that armadillo's wrapper library should be using the OpenBLAS functions that we have in the clang environment and the remaining LAPACK functions from `f2cblaslapack`. (At least, I hope that lld does what I think it does...)
> 
> @bmiyuan: Could you please check with the updated artifact from that PR? You can download the `clang64` artifact from here: https://github.com/msys2/MINGW-packages/actions/runs/1713702135 Unzip it and install the test package with: `pacman -U mingw-w64-clang-x86_64-armadillo-10.8.0-2-any.pkg.tar.zst` Do you still see the "undefined symbol" errors with that version of armadillo?

Hi Markus,  I can compile without disable wrap*, great job! thanks again!

**Comment by bmiyuan** [comment] 2022-01-20 06:30
Hi Markus, by the way ,when can we donwload the latest vertion by pacman?

**Comment by Biswa96** [comment] 2022-01-20 07:27
The workflow is like this. PR merged > build in [queue][1] > added in [repo][2] after some days. If you want to test the packages in queue scroll down to the very end of the [page][1] to see the instructions.

[1]: https://packages.msys2.org/queue
[2]: https://packages.msys2.org/updates

**Comment by mmuetzel** [comment] 2022-01-20 09:02
@bmiyuan: Thanks for testing! 👍

**Comment by mmuetzel** [comment] 2022-02-04 13:27
@bmiyuan: Sorry for coming back to you again.
After some feedback from the upstream developers and others, I no longer think that the approach taken in #10566 is good. That was the one that you tested before.
Could you please update your MSYS2 and test with the `clang64` artifact from a different PR? You could download the newer artifact from here and install it using the same procedure like the other one:
https://github.com/msys2/MINGW-packages/actions/runs/1795103354

**Closed** 2022-02-04 14:02 UTC
Labels: clang64
