### ISSUE TITLE
mingw-w64-x86_64-apr 1.6.5-2 : define APR_SIZE_T_FMT error in apr.h

### ISSUE THREAD

**Issue by Virgil-Zu** [msys2/MINGW-packages#6886] opened 2020-08-28 04:00 UTC
file: /msys64/mingw64/include/apr-1/apr.h
line: 537

```
/* And APR_SIZE_T_FMT */
#define APR_SIZE_T_FMT "lld"
```

but in apache source code <apr.h> line: 583
`#define APR_SIZE_T_FMT           "I64u"`

so ,some code use APR_SIZE_T_FMT
example : library apr_util, apr_redis.c, this code use APR_SIZE_T_FMT printf string like 
`len = apr_snprintf(keysize_str, LILBUFF_SIZE, "$%" APR_SIZE_T_FMT "\r\n", klen);`
this code never gave the correct result on windows x64 because "%lld"

library libapr-1.dll, libaprutil-1.dll,  compile with #define APR_SIZE_T_FMT "lld"

**Comment by Alexpux** [comment] 2020-08-28 05:27
@Virgil-Zu mingw.org not related to this project. We use mingw-w64

**Comment by Virgil-Zu** [comment] 2020-08-28 05:49
@Alexpux thank you, I'll change my description
packages:
mingw64 mingw-w64-x86_64-apr 1.6.5-2
mingw64 mingw-w64-x86_64-apr-util 1.6.1-1
gcc version 10.2.0 (Rev1, Built by MSYS2 project)

gcc:

**Comment by Biswa96** [comment] 2020-08-28 06:32
Would you like to provide a simple *printf example that can reproduce your issue?

**Comment by Virgil-Zu** [comment] 2020-08-28 07:02
@Biswa96 sure

main.c
`#include <stdio.h>
#include <apr-1/apr_strings.h>

int main(void)
{
	setvbuf(stdout, 0, _IONBF, 0);

	printf("printf [%lld]\n", 1234);

	char data[64]={0};
	sprintf(data, "%lld", 1234);
	printf("sprintf [%s]\r\n", data);

	apr_snprintf(data, sizeof(data), "%" APR_SIZE_T_FMT, 1234);
	printf("apr_snprintf APR_SIZE_T_FMT [%s]\r\n", data);

	apr_snprintf(data, sizeof(data), "%lld", 1234);
	printf("apr_snprintf lld [%s]\r\n", data);

	apr_snprintf(data, sizeof(data), "%I64d", 1234);
	printf("apr_snprintf I64d [%s]\r\n", data);
}`


make 
`gcc -o main.exe main.c -lapr-1`
same echo as
`gcc -o main.exe main.c -lapr-1 -std=c99`

echo
`printf [1234]
sprintf [1234]
apr_snprintf APR_SIZE_T_FMT [$%ld]
apr_snprintf lld [%ld]
apr_snprintf I64d [1234]
`

**Comment by lazka** [comment] 2020-08-28 09:44
Looking at the print code it looks like it expects APR_INT64_T_FMT and APR_SIZE_T_FMT to be the same thing. https://github.com/apache/apr/blob/ea4a9ea7c715e1f6ea233a4c4f60e2d5df8321f4/strings/apr_snprintf.c#L811 But their configure script is broken..

**Comment by Virgil-Zu** [comment] 2020-08-31 02:59
for example: 

APR Redis Client Routines

apr_redis_getp
apr_redis_set
apr_redis_setex
apr_redis_delete

these functions use apr_snprintf with APR_SIZE_T_FMT and they are not working correctly 

It means that MSYS2 APR Library Redis Client Routines can not use in windows

thanks all

**Comment by lazka** [comment] 2020-09-07 17:16
Is this fixed now?

**Comment by Virgil-Zu** [comment] 2020-09-08 01:10
not yet,  `mingw-w64-x86_64-apr 1.6.5-2` is okey , `mingw-w64-x86_64-apr-util 1.6.1-1` should be rebuild too,  I'm trying to fix [https://github.com/msys2/MINGW-packages/issues/6631], then rebuild `mingw-w64-x86_64-apr-util`, I am trying to expedite the process

**Closed** 2020-09-19 15:08 UTC
