### ISSUE TITLE
[qt6-static] Some bugs about this package

### ISSUE THREAD

**Issue by youngbe** [msys2/MINGW-packages#11656] opened 2022-05-13 18:45 UTC
I have tried to use qt6-static to build qt projects these days, and finally succeed.

I think there are some small bugs about the package `mingw-w64-qt6-static`.

I have tried both `mingw-w64-ucrt-x86_64-qt6-static` and `mingw-w64-x86_64-qt6-static`. I will use ucrt version to talk about it.

All the errors occurr during linking, compile time has no error.

### 1. missing dependences jasper and libb2
When building, gcc can't find `-lb2` and `-ljasper`.

Fix:
```bash
pacman --needed -S ucrt64/mingw-w64-ucrt-x86_64-jasper ucrt64/mingw-w64-ucrt-x86_64-libb2
```
### 2. wrong linker flags
There are some missing in the flags and the order is wrong, so there are a lot of error about "undefined symbols xxx".

Fix: add following to the qmake .pro file.
```
QMAKE_LIBS *= -lbz2 -lharfbuzz -lfreetype -lgraphite2 -lgdi32 -lzstd -ldeflate -llzma -llerc -ljbig -llcms2 -l:libjasper.dll.a -lmincore -ljpeg
```
### 3. link to dynamic libjasper
After fix 1 and fix 2, I can successfully build now, however, the output exe file still need `libjasper-4.dll` and `libjpeg-8.dll` to run. I found that it dynamically link to libjasper with flag `-l:libjasper.dll.a`. However, if don't add this flag, the build will failed with a lot of undefined `__imp_jas_xxx`.

I found that the libjasper packages provides `/ucrt64/lib/libjasper.dll.a` and `/ucrt64/lib/libjasper.a`, I use `nm` to check them and found that `/ucrt64/lib/libjasper.a` contains a log of `jas_xxx` and `/ucrt64/lib/libjasper.dll.a` contains a log of `__imp_jas_xxx`. Normally, it should be link to `/ucrt64/lib/libjasper.a` with flag `-ljasper`, however, some of the static qt .a file use `__imp_jas_xxx`.

So I try to use objcopy to rename the symbols to make a static jasper library with `__imp_` prefix. I write a script to do this.
```bash
#!/bin/bash
temp=($(nm /ucrt64/lib/libjasper.a | awk '{print $NF}' | grep "^jas" |grep -v ':' | sort | uniq))
for ((i=0;i<${#temp[@]};i++))
do
    temp[$i]="--redefine-sym ${temp[$i]}=__imp_${temp[$i]}"
done
echo objcopy ${temp[@]} /ucrt64/lib/libjasper.a /ucrt64/lib/libjasper_fix.a
objcopy ${temp[@]} /ucrt64/lib/libjasper.a /ucrt64/lib/libjasper_fix.a
```

This script generate `libjasper_fix.a`.

Finally, change the link flag `-l:libjasper.dll.a` to `-llibjasper_fix.a` and successfully build static qt6 application.

**Comment by Biswa96** [comment] 2022-05-13 18:50
Duplicate of https://github.com/msys2/MINGW-packages/issues/10306

**Closed by Biswa96** 2022-05-13 18:50 UTC
