### ISSUE TITLE
[zed] Package doesn't exist

### ISSUE THREAD

**Issue by MidnightStallion** [msys2/MINGW-packages#22129] opened 2024-10-06 23:13 UTC
### Description / Steps to reproduce the issue

1. Follow instructions from zed to install zed in msys2

pacman -Syu
pacman -S $MINGW_PACKAGE_PREFIX-zed

### Expected behavior

zed package should install.

### Actual behavior

error: target not found: mingw-w64-x86_64-zed

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [x] CLANG64
- [ ] CLANGARM64

### Are you willing to submit a PR?

No

**Comment by MidnightStallion** [comment] 2024-10-06 23:37
Update:

The UART64 version doesn't exist. The CLANG64 version does,  but it fails to start:

$ zed.exe
[2024-10-06T18:35:24-05:00 ERROR fs.rs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-06T18:35:25-05:00 ERROR fs.rs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-06T18:35:25-05:00 ERROR fs.rs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
Zed failed to open a window: NoSupportedDeviceFound. See https://zed.dev/docs/linux for troubleshooting steps.

**Comment by Biswa96** [comment] 2024-10-07 04:02
Duplicate of #21767

**Comment by ognevny** [comment] 2024-10-07 04:08
Zed is NOT provided for MINGW64. UCRT64 version is disabled due to keyboard issue

**Comment by ognevny** [comment] 2024-11-09 05:20
Zed is now available in MINGW64 repository of MSYS2. you can download it now with `pacman -Sy mingw-w64-x86_64-zed`

**Closed** 2024-11-09 05:21 UTC
Labels: bug, duplicate

**Comment by ognevny** [comment] 2025-08-14 05:39
Zed will be dropped for MINGW64 environment in https://github.com/msys2/MINGW-packages/pull/25178 because the editor now links function from `ucrtbase.dll` via Zed's dependency. please, consider switching to UCRT64 version
