### ISSUE TITLE
Qt Location QML Map example program freezes

### ISSUE THREAD

**Issue by ferkulat** [msys2/MINGW-packages#11859] opened 2022-06-16 06:12 UTC
When compiling the example app

https://doc.qt.io/qt-5/qtlocation-minimal-map-example.html

with current msys2 mingw64 and qtcreator using qt5, the program starts, but you can not move the map with the mouse.
The program seems to be frozen.
If the same example is compiled with mingw64 qt5, shipped with current Qt community edition, it works.
You can grab the map and move it around.

**Comment by Biswa96** [comment] 2022-06-19 08:43
Can you provide how to compile the example code with simple commands and without qtcreator?

**Comment by ferkulat** [comment] 2022-06-20 14:11
I created a cmake project for that:
https://github.com/ferkulat/qtlocation_qml_cmake_example

**Comment by Biswa96** [comment] 2022-06-20 14:51
Affirmative. I can reproduce the issue in my system. But I can not help to debug this issue. Please wait for others to comment on this topic.

**Comment by MehdiChinoune** [comment] 2022-06-20 15:09
> If the same example is compiled with mingw64 qt5, shipped with current Qt community edition, it works. You can grab the map and move it around.

Which version? Is it 5.15.2?

I have tried your example with both Qt5 5.15.3 and 5.15.5. It looks like the issue was fixed in 5.15.5

**Comment by MehdiChinoune** [comment] 2022-06-20 15:22
> The example was compiled with qt5.15.3.

I asked about the one from Qt.

**Comment by ferkulat** [comment] 2022-06-20 15:30
qtcreator shipped with 
- qt-5.15.2
- mingw-8.1.0

**Comment by ferkulat** [comment] 2022-07-04 06:37
Someone commented on this issue, that it might be solved by updating to 5.15.5.
Because on his/her local 5.15.5 build it worked.
Unfortunately  his/her comments got deleted one day later.

Is there a chance the qt5 packages will get updated to 5.15.5?

**Closed** 2022-08-16 04:27 UTC
Labels: bug

**Comment by PiBosch** [comment] 2023-01-23 08:14
@ferkulat Could you find the solution to this issue?, I tried with Qt 5.15.10 and got the same issue. When running it with the mapboxgl provider the map works fine
