### ISSUE TITLE
undefined references with boost program_options

### ISSUE THREAD

**Issue by mkaut** [msys2/MINGW-packages#5045] opened 2019-03-12 10:23 UTC
I cannot build even a simple example using boost program_options. For example, compiling [real.cpp](https://www.boost.org/doc/libs/1_69_0/libs/program_options/example/real.cpp) with `g++ -c real.cpp -I /mingw64/include` works fine, but linking as `g++ -g real.o -L/mingw64/lib -lboost_program_options-mt` fails with the following errors:
```
real.o:real.cpp:(.text+0xa3b): undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
real.o:real.cpp:(.text+0xa3b): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
real.o:real.cpp:(.text$_ZNK5boost15program_options13variables_mapixERKSs[_ZNK5boost15program_options13variables_mapixERKSs]+0x1c): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
real.o:real.cpp:(.text$_ZNK5boost15program_options13variables_mapixERKSs[_ZNK5boost15program_options13variables_mapixERKSs]+0x1c): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
real.o:real.cpp:(.text$_ZN5boost15program_options25basic_command_line_parserIcEC1EiPKPKc[_ZN5boost15program_options25basic_command_line_parserIcEC1EiPKPKc]+0x74): undefined reference to `boost::program_options::detail::cmdline::cmdline(std::vector<std::string, std::allocator<std::string> > const&)'
real.o:real.cpp:(.text$_ZN5boost15program_options25basic_command_line_parserIcEC1EiPKPKc[_ZN5boost15program_options25basic_command_line_parserIcEC1EiPKPKc]+0x74): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `boost::program_options::detail::cmdline::cmdline(std::vector<std::string, std::allocator<std::string> > const&)'
real.o:real.cpp:(.text$_ZN5boost15program_options25basic_command_line_parserIcE12extra_parserENS_9function1ISt4pairISsSsERKSsEE[_ZN5boost15program_options25basic_command_line_parserIcE12extra_parserENS_9function1ISt4pairISsSsERKSsEE]+0x35): undefined reference to `boost::program_options::detail::cmdline::set_additional_parser(boost::function1<std::pair<std::string, std::string>, std::string const&>)'
real.o:real.cpp:(.text$_ZN5boost15program_options25basic_command_line_parserIcE12extra_parserENS_9function1ISt4pairISsSsERKSsEE[_ZN5boost15program_options25basic_command_line_parserIcE12extra_parserENS_9function1ISt4pairISsSsERKSsEE]+0x35): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `boost::program_options::detail::cmdline::set_additional_parser(boost::function1<std::pair<std::string, std::string>, std::string const&>)'
real.o:real.cpp:(.text$_ZN5boost15program_options11to_internalISsEESt6vectorISsSaISsEERKS2_IT_SaIS5_EE[_ZN5boost15program_options11to_internalISsEESt6vectorISsSaISsEERKS2_IT_SaIS5_EE]+0x59): undefined reference to `boost::program_options::to_internal(std::string const&)'
real.o:real.cpp:(.text$_ZN5boost15program_options11to_internalISsEESt6vectorISsSaISsEERKS2_IT_SaIS5_EE[_ZN5boost15program_options11to_internalISsEESt6vectorISsSaISsEERKS2_IT_SaIS5_EE]+0x59): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `boost::program_options::to_internal(std::string const&)'
real.o:real.cpp:(.rdata$_ZTVN5boost15program_options11typed_valueISscEE[_ZTVN5boost15program_options11typed_valueISscEE]+0x38): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
real.o:real.cpp:(.text$_ZNK5boost15program_options11typed_valueISscE6xparseERNS_3anyERKSt6vectorISsSaISsEE[_ZNK5boost15program_options11typed_valueISscE6xparseERNS_3anyERKSt6vectorISsSaISsEE]+0x79): undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, std::string*, int)'
real.o:real.cpp:(.text$_ZNK5boost15program_options11typed_valueISscE6xparseERNS_3anyERKSt6vectorISsSaISsEE[_ZNK5boost15program_options11typed_valueISscE6xparseERNS_3anyERKSt6vectorISsSaISsEE]+0x79): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `boost::program_options::validate(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, std::string*, int)'
real.o:real.cpp:(.rdata$.refptr._ZN5boost15program_options3argE[.refptr._ZN5boost15program_options3argE]+0x0): undefined reference to `boost::program_options::arg'
collect2: error: ld returned 1 exit status
```

I am on Windows 10, with fully updated msys2 (according to `pacman -Syuu`).
I have reinstalled boost, but it did not help; `pacman -Ss | grep boost` returns
```
mingw32/mingw-w64-i686-boost 1.69.0-2
mingw64/mingw-w64-x86_64-boost 1.69.0-2 [installed]
```

Is this a bug, or am I just doing something wrong?

**Comment by oscarfv** [comment] 2019-03-12 17:08
I cannot reproduce the problem here, with all packages up to date.

Why do you need to specify the include and library paths? The compiler already knows those. Unless you are using the wrong `g++`, of course, like using the 32 bit compiler instead of the 64 bits one. What's the output of `which g++` on the same shell?

**Comment by mkaut** [comment] 2019-03-13 11:29
> I cannot reproduce the problem here, with all packages up to date.
> 
> Why do you need to specify the include and library paths? The compiler already knows those. Unless you are using the wrong `g++`, of course, like using the 32 bit compiler instead of the 64 bits one. What's the output of `which g++` on the same shell?

Thanks for the help. You were right, it turned out I my gcc consisted of a mixture of msys and mingw64 parts:
```
$ pacman -Ss | grep gcc
mingw32/mingw-w64-i686-gcc 7.4.0-1 (mingw-w64-i686-toolchain)
mingw32/mingw-w64-i686-gcc-ada 7.4.0-1 (mingw-w64-i686-toolchain)
mingw32/mingw-w64-i686-gcc-fortran 7.4.0-1 (mingw-w64-i686-toolchain)
mingw32/mingw-w64-i686-gcc-libgfortran 7.4.0-1 (mingw-w64-i686-toolchain)
mingw32/mingw-w64-i686-gcc-libs 7.4.0-1 (mingw-w64-i686-toolchain)
mingw32/mingw-w64-i686-gcc-objc 7.4.0-1 (mingw-w64-i686-toolchain)
mingw64/mingw-w64-x86_64-gcc 8.3.0-2 (mingw-w64-x86_64-toolchain)
mingw64/mingw-w64-x86_64-gcc-ada 8.3.0-2 (mingw-w64-x86_64-toolchain)
mingw64/mingw-w64-x86_64-gcc-fortran 8.3.0-2 (mingw-w64-x86_64-toolchain)
mingw64/mingw-w64-x86_64-gcc-libgfortran 8.3.0-2 (mingw-w64-x86_64-toolchain) [installed]
mingw64/mingw-w64-x86_64-gcc-libs 8.3.0-2 (mingw-w64-x86_64-toolchain) [installed]
mingw64/mingw-w64-x86_64-gcc-objc 8.3.0-2 (mingw-w64-x86_64-toolchain)
msys/gcc 7.4.0-1 (msys2-devel) [installed]
msys/gcc-fortran 7.4.0-1 (msys2-devel) [installed]
msys/gcc-libs 7.4.0-1 (base) [installed]
msys/mingw-w64-cross-gcc 7.3.0-2 (mingw-w64-cross-toolchain mingw-w64-cross)
```
I have replaced the msys-versions with mingw64 ones and it works as it should.
Now I am worried that I might have installed wrong versions of other packages as well, so I guess my safest option is to uninstall the whole msys2 from Windows and start from scratch?

Anyway, since this turned out to be my problem, no msys2 error, is it possible to delete the whole issue, or should I just close it?

**Comment by oscarfv** [comment] 2019-03-13 15:17
As long as `PATH` is correctly set depending on the gcc flavor you want to use (mingw-i686, mingw-x86_64, msys) and you don't introduce parameters that confuse gcc (such as wrong system include and library paths) there should be no problem.

You can remove packages with `pacman -R gcc` (for msys gcc, for instance). There is no need to start from scratch.

As far as I know reporters can't delete issues. Just close this.

**Closed** 2019-03-14 07:33 UTC
