### ISSUE TITLE
 build cpprestsdk failed 

### ISSUE THREAD

**Issue by Soufianeelkabil** [msys2/MINGW-packages#17611] opened 2023-06-22 12:16 UTC
### Description / Steps to reproduce the issue

The C++ REST SDK is a Microsoft project for cloud-based client-server communication in native code using a modern asynchronous C++ API design
[https://github.com/microsoft/cpprestsdk](https://github.com/msys2/MINGW-packages/issues/url)
but it built failed with  mingw32-make,

the setups are :
Steps are as follows:

    git clone https://github.com/Microsoft/cpprestsdk.git
    cd cpprestsdk
    git checkout v2.10.18
    git submodule update --init
    mkdir build
    cd build
    cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
    mingw32-make.exe

Can someone help me ?
[
<img width="947" alt="Screenshot 2023-06-22 140414" src="https://github.com/msys2/MINGW-packages/assets/117685430/b64654b9-12e2-47f4-a520-b78684c7ddc7">
](url)

### Expected behavior

I expect to build make.exe

### Actual behavior

could you please make a package of this lib, thanks

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [ ] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment] 2023-06-22 12:21
Duplicate of https://github.com/msys2/MINGW-packages/issues/17611

**Closed by Biswa96** 2023-06-22 12:21 UTC
Labels: bug
