### ISSUE TITLE
g++in /mingw64/bin gives incorrect value for %z in strftime.

### ISSUE THREAD

**Issue by justinmcgrath** [msys2/MINGW-packages#17496] opened 2023-06-11 05:39 UTC
### Description / Steps to reproduce the issue

This uses the following cpp program.

```
#include <time.h>
#include <iostream>
#include <chrono>

int main()
{
        time_t rawtime;
        struct tm * timeinfo;
        char buffer[80];

        time(&rawtime);
        timeinfo = localtime(&rawtime);
        strftime(buffer, 80, "The offset is %z.", timeinfo);
        std::cout << buffer << '\n';

        return 0;
}
```

Run this command from a MSYS2 MINGW64 environment, which will use `/mingw65/bin/g++`.

`g++ main.cpp`

Executing `a.exe` gives the following incorrect output.

"The offset is Central Daylight Time."

The specific output depends on the locale, but it should give the offset as a numeric value, not the name of the time zone.

If the program is compiled using this command, the output is correct.

`/usr/bin/g++ main.cpp`

The output is this.

"The offset is -0500."

Everything is up to date. `g++ --version` gives this:
"g++.exe (Rev6, Built by MSYS2 project) 13.1.0
Copyright (C) 2023 Free Software Foundation, Inc."

`/usr/bin/g++ --version` gives this:
"g++ (GCC) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc."

### Expected behavior

The output should be "The offset is -0500."

### Actual behavior

The output is "The offset is Central Daylight Time.".

The timezone name is what "%Z" should give, not what "%z" should.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-6.1-7601

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

I don't think I have the ability.

**Comment by Biswa96** [comment] 2023-06-11 05:45
The issue can not be reproduced with UCRT64. This seems to be an limitation in msvcrt, not sure though.

> MINGW64_NT-6.1-7601

MSYS2 requires 64 bit Windows 8.1 or newer. Windows 7 support was dropped https://www.msys2.org/news/#2023-01-15-dropping-support-for-windows-7-and-80

**Comment by justinmcgrath** [comment] 2023-06-11 06:12
It works properly with UCRT64. It only doesn't work with mingw64.

**Comment by Biswa96** [comment] 2023-06-11 07:13
Please use UCRT64. This issue with msvcrt (here mingw64) can only be fixed with a custom implementation of that API in mingw-w64.

**Closed by Biswa96** 2023-06-11 07:13 UTC
Labels: bug
