### ISSUE TITLE
create poppler-qt6 (qt5) with -DENABLE_RELOCATABLE=ON 

### ISSUE THREAD

**Issue by sunderme** [msys2/MINGW-packages#10487] opened 2022-01-06 16:02 UTC
## Describe the issue

poppler has recently integrated a patch for windows (see poppler release notes), so that it searches for fonts relative to the dll.
This is especially important if msys2 is used to build an installer where only the dlls are copied.
For the function to work, poppler needs to be build with the option ```-DENABLE_RELOCATABLE=ON```
This is a feature request.

## Steps to Reproduce the Problem

see https://gitlab.freedesktop.org/poppler/poppler/-/merge_requests/979

**Comment by Biswa96** [comment] 2022-01-06 16:11
Is it possible to know if the issue is fixed in the package? Just to verify.

**Comment by sunderme** [comment] 2022-01-06 17:42
it is a tad complicated. Basically you see it if there is a local font which is needed in the pdf, see https://github.com/texstudio-org/texstudio/issues/1812
But for this you need to build a viewer app, move the dlls, add the font directory.
I did this for upstreaming the patch as it is basically testing against texstudio.

**Comment by Biswa96** [comment] 2022-01-06 19:38
I have added a pull request to fix this issue. Would you like to test the packages from GitHub actions artifacts? here https://github.com/msys2/MINGW-packages/actions/runs/1664471136

**Comment by sunderme** [comment] 2022-01-06 21:08
looks, like the package is using poppler 21.11. The change was introduced only with 22.01 ...

**Comment by sunderme** [comment] 2022-01-06 21:23
To be clear, the flag is also fine for 21.11, it just does not influence font finding

**Comment by Biswa96** [comment] 2022-01-07 04:01
Alright. I have updated the package in that pull request. Here are the test packages from GitHub Actions artifacts https://github.com/msys2/MINGW-packages/actions/runs/1665993077. Please test them.

**Comment by sunderme** [comment] 2022-01-07 08:45
I can confirm that it works.

**Closed** 2022-01-07 12:42 UTC
Labels: reported-upstream

**Comment by Biswa96** [comment] 2022-01-08 05:17
There will be some delay with poppler update. poppler uses std::optional in public headers. So, the dependencies has to be built with c++17 standard. But some of those packages need c++17 support from upstream.
