### ISSUE TITLE
can't link my app anymore

### ISSUE THREAD

**Issue by hbenrico** [msys2/MINGW-packages#14891] opened 2023-01-03 08:12 UTC
### Description / Steps to reproduce the issue

After upgrading libpsl through msys2 packages upgrade

[mingw-w64-clang-x86_64-libpsl] (https://packages.msys2.org/package/mingw-w64-clang-x86_64-libpsl?repo=clang64)

I am not able to link my app anymore:

ld.lld: error: undefined symbol: __declspec(dllimport) uninorm_nfkc
>>> referenced by libpsl.a(psl.c.obj):(psl_str_to_utf8lower)
>>> referenced by libpsl.a(psl.c.obj):(psl_str_to_utf8lower)

Cant post the steps to reproduce the error because I'm using an higher level language (harbour)

thanks in advance 

### Expected behavior

.

### Actual behavior

.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment] 2023-01-03 08:28
duplicate of #14882

**Closed by MehdiChinoune** 2023-01-03 08:28 UTC
Labels: bug
