### ISSUE TITLE
pdcurses and ncurses are in conflict

### ISSUE THREAD

**Issue by sdbbs** [msys2/MINGW-packages#5437] opened 2019-05-29 06:44 UTC
Just today, on a Windows 10 machine - first I did `pacman -Syu`, which updated `pacman` itself, and here I closed the terminal as recommended.

Then I ran it again:

```
$ pacman -Syu
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
:: Replace mingw-w64-x86_64-ncurses with mingw64/mingw-w64-x86_64-pdcurses? [Y/n] n
:: Replace mingw-w64-x86_64-termcap with mingw64/mingw-w64-x86_64-pdcurses? [Y/n] n
resolving dependencies...
looking for conflicting packages...
:: mingw-w64-x86_64-pdcurses and mingw-w64-x86_64-ncurses are in conflict. Remove mingw-w64-x86_64-ncurses? [Y/n] n
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: mingw-w64-x86_64-pdcurses and mingw-w64-x86_64-ncurses are in conflict
```

Not sure what to do here - can I remove this pdcurses package? (not sure how it even got installed - I know I've used ncurses to compile programs before, so it must have been me that installed it, but I'm not familiar with pdcurses)

**Comment by Alexpux** [comment] 2019-05-29 07:59
@sdbbs you need agree with pacman and it will replace ncurses with pdcurses

**Comment by fabiangreffrath** [comment] 2019-05-29 08:31
@Alexpux What is the reason for the switch from ncurses to pdcurses?

**Comment by Alexpux** [comment] 2019-05-29 08:37
@fabiangreffrath In any cases ncurses mostly broken for mingw, so there are no reason to stay on it. PDcurses is less huge as ncurses.
See PDCurses website - [https://www.projectpluto.com/win32a.htm](https://www.projectpluto.com/win32a.htm)

**Comment by fabiangreffrath** [comment] 2019-05-29 09:43
So, if it doesn't work properly anyway, we can just as well choose the smaller implementation?

**Comment by Alexpux** [comment] 2019-05-29 09:47
No, if something really broken for use it’s better to not use at all

**Comment by mingwandroid** [comment] 2019-05-29 10:37
Hey @Alexpux, if you can point me to some issues I promise to try to fix them. 
Many years ago I preferred pdcurses to nurses on Windows but now I done think pdcurses is really very good or compatible? It is also missing many features AFAIR. If I'm wrong then fair enough, but I'd like to fix nurses here..

**Comment by Alexpux** [comment] 2019-05-29 10:45
@mingwandroid maybe you will try first pdcurses provided here? As I see there are no much packages depends on curses library. Mostly we need it here for libreadline and python{2,3} module.

**Comment by lazka** [comment] 2019-05-29 18:20
The official Python2/3 is built without curses support, so we could also remove it.

**Comment by clinton-r** [comment] 2019-06-09 03:22
Hello, I hope someone can help me with this problem.  I'm trying to allow pacman to replace ncurses with pdcurses as suggested above, but I get some other conflicts:

> $ pacman -Syuu
> :: Synchronising package databases...
>  mingw32 is up to date
>  mingw64 is up to date
>  msys is up to date
> :: Starting core system upgrade...
>  there is nothing to do
> :: Starting full system upgrade...
> :: Replace mingw-w64-x86_64-ncurses with mingw64/mingw-w64-x86_64-pdcurses? [Y/n] Y
> :: Replace mingw-w64-x86_64-termcap with mingw64/mingw-w64-x86_64-pdcurses? [Y/n] Y
> resolving dependencies...
> looking for conflicting packages...
> error: failed to prepare transaction (could not satisfy dependencies)
> :: installing mingw-w64-x86_64-gcc (9.1.0-2) breaks dependency 'mingw-w64-x86_64-gcc=8.3.0-2' required by mingw-w64-x86_64-gcc-ada
> :: installing mingw-w64-x86_64-gcc (9.1.0-2) breaks dependency 'mingw-w64-x86_64-gcc=8.3.0-2' required by mingw-w64-x86_64-gcc-objc
> 

This also seems to be preventing me from installing python2:

> $ pacman -S mingw-w64-x86_64-python2
> resolving dependencies...
> looking for conflicting packages...
> :: mingw-w64-x86_64-pdcurses and mingw-w64-x86_64-ncurses are in conflict. Remove mingw-w64-x86_64-ncurses? [Y/n] n
> error: unresolvable package conflicts detected
> error: failed to prepare transaction (conflicting dependencies)
> :: mingw-w64-x86_64-pdcurses and mingw-w64-x86_64-ncurses are in conflict
>

**Comment by totaam** [comment] 2019-06-09 03:55
I hit the same gcc issue and "fixed" it by removing `mingw-w64-x86_64-gcc-ada` and `mingw-w64-x86_64-gcc-objc` which I don't need.

**Comment by clinton-r** [comment] 2019-06-11 02:36
Thanks totaam, I didn't need those either.  Update succeeded.  Python2 installed.

**Comment by Diapolo** [comment] 2019-06-12 19:11
I also needed to remove these two for the upgrade to work:
mingw-w64-x86_64-gcc-ada
mingw-w64-x86_64-gcc-objc

Thanks!

**Comment by fabiangreffrath** [comment] 2019-06-12 19:28
Couldn't the most recent gcc packages simply declare conflicts against those two?

**Comment by lazka** [comment] 2019-06-13 07:30
> Couldn't the most recent gcc packages simply declare conflicts against those two?

#5523

**Comment by lhmouse** [comment] 2019-06-13 15:27
With **PDCurses** now, switching **GDB** to TUI mode (by using the `layout` command or pressing `Ctrl-X Ctrl-A`) results in a popup window, which usually hangs, but sometimes works without echoing any key strokes (so it is completely unusable now). **ncurses** didn't have this issue.

**Comment by GyanD** [comment] 2019-06-18 13:19
This appears to have created an issue with ffmpeg when run in Cmder or mintty. I can't reproduce it in cmd directly. I'm on Windows 7 SP1.

ffmpeg will randomly appear to freeze once in 7-8 runs - in actuality, the main transcode loop is still running, since it will quit when 3 or more SIGINTs are received. However, regular keypresses aren't acted upon (e.g. 'q' to quit or '?' to show help ). Most importantly, the actual data processing has stopped.

If I get ffmpeg to generate a report file (this flushes the log to a file in realtime without redirecting stderr), I can see in the report file ffmpeg acknowledging receiving `signal 0` when Ctrl+C is pressed. However, it doesn't acknowledge keypresses. Those keypresses are echoed at the prompt once I force-quit ffmpeg. Note that ffmpeg hasn't been told to ignore stdin.

I cannot reproduce this behaviour when run inside gdb.

The replacement of curses provider seems to be the prime candidate for this behaviour which I first noticed 2-3 weeks ago.

I would like to confirm by reinstalling ncurses/termcap but those packages are removed. Can I get copies of the last versions from somewhere?

Thanks.

**Comment by lhmouse** [comment] 2019-06-18 14:11
You may build **ncurses** yourself using the script at <https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-ncurses>, but installing it would break dependencies (e.g. python) so you have to uninstall and rebuild other packages thereafter.

**Comment by jwt27** [comment] 2019-06-27 21:02
Line editing in gdb (backspace, arrow left/right, home/end) is broken now, this happened after ncurses/termcap were removed.
Additionally, I now have to build gdb with --disable-tui, seems it required one of those libraries.

**Comment by GyanD** [comment] 2019-06-29 15:09
This was due to winpthreads, not curses library. See update in thread I linked above.

**Comment by lhmouse** [comment] 2019-06-30 03:00
Is it? https://github.com/mingw-w64/mingw-w64/commit/b2302cd60b94a6d68a0e18b3f886b82f4b7f22b7

**Comment by GyanD** [comment] 2019-06-30 04:47
Is what? Is that the offending commit? I haven't debugged why, or bisected to the offending commit. I do know the decode call for video wasn't returning when this happened. I can confirm the issue is resolved by downgrading (lib)winpthreads. If you can provide a winpthread package archive of b2302cd and b2320cd~, I can confirm.

**Comment by lhmouse** [comment] 2019-06-30 08:13
You can always build your own using PKGBUILD from <https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-winpthreads-git>.

**Closed** 2019-07-08 06:00 UTC
