### ISSUE TITLE
qtcreator segmentation fault in clang64 environment

### ISSUE THREAD

**Issue by askondro** [msys2/MINGW-packages#14963] opened 2023-01-07 14:18 UTC
### Description / Steps to reproduce the issue

Open the clang64 console environment.

`Run: qtcreator`

### Expected behavior

Opens the qtcreator GUI.

### Actual behavior

$ qtcreator
```
$ 5a18:err:d3d:wined3d_caps_gl_ctx_create Failed to find a suitable pixel format.
5a18:err:d3d:wined3d_adapter_init Failed to get a GL context for adapter 0000022789f9d9e0.
```

Result (gdb qtcreator): 

```
Type "apropos word" to search for commands related to "word"...
Reading symbols from qtcreator...
(No debugging symbols found in qtcreator)
(gdb) r
Starting program: C:\msys64\clang64\bin\qtcreator.exe
[New Thread 21752.0x210]
[New Thread 21752.0x8b7c]
[New Thread 21752.0x5104]
[New Thread 21752.0x7f24]
[New Thread 21752.0x7238]
[New Thread 21752.0x5584]
[Thread 21752.0x5584 exited with code 0]
[New Thread 21752.0x2bfc]
[New Thread 21752.0x2914]
[New Thread 21752.0x3e20]
[New Thread 21752.0x7510]
[New Thread 21752.0x2358]
[New Thread 21752.0x7774]
[New Thread 21752.0x505c]
[New Thread 21752.0xe74]
[New Thread 21752.0x6a9c]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ff94b9fc26e in libgallium_wgl!_glapi_new_nop_table () from C:\msys64\clang64\bin\libgallium_wgl.dll
(gdb) bt
#0  0x00007ff94b9fc26e in libgallium_wgl!_glapi_new_nop_table () from C:\msys64\clang64\bin\libgallium_wgl.dll
msys2/MSYS2-packages#1  0x00007ff94b5d3046 in libgallium_wgl!_glapi_get_dispatch () from C:\msys64\clang64\bin\libgallium_wgl.dll
msys2/MSYS2-packages#2  0x00007ff94b5d5476 in libgallium_wgl!_glapi_get_dispatch () from C:\msys64\clang64\bin\libgallium_wgl.dll
msys2/MSYS2-packages#3  0x00007ff94b9fc3e4 in libgallium_wgl!_glapi_new_nop_table () from C:\msys64\clang64\bin\libgallium_wgl.dll
msys2/MSYS2-packages#4  0x00007ff94b5d3046 in libgallium_wgl!_glapi_get_dispatch () from C:\msys64\clang64\bin\libgallium_wgl.dll
msys2/MSYS2-packages#5  0x00007ff94b5d02ea in libgallium_wgl!_glapi_get_dispatch () from C:\msys64\clang64\bin\libgallium_wgl.dll
msys2/MSYS2-packages#6  0x00007ff94b5d1b2d in libgallium_wgl!_glapi_get_dispatch () from C:\msys64\clang64\bin\libgallium_wgl.dll
msys2/MSYS2-packages#7  0x00007ff94b5d1f00 in libgallium_wgl!_glapi_get_dispatch () from C:\msys64\clang64\bin\libgallium_wgl.dll
msys2/MSYS2-packages#8  0x00007ff94b5e00f8 in libgallium_wgl!_glapi_get_dispatch () from C:\msys64\clang64\bin\libgallium_wgl.dll
msys2/MSYS2-packages#9  0x00007ff94b5c1f4f in libgallium_wgl!_glapi_get_dispatch () from C:\msys64\clang64\bin\libgallium_wgl.dll
msys2/MSYS2-packages#10 0x00007ff94b3f3dd0 in stw_get_framebuffer_resource () from C:\msys64\clang64\bin\libgallium_wgl.dll
msys2/MSYS2-packages#11 0x00007ff94b3d19d2 in libgallium_wgl!DrvCreateLayerContext () from C:\msys64\clang64\bin\libgallium_wgl.dll
msys2/MSYS2-packages#12 0x00007ffa1f911423 in wglCreateContext () from C:\msys64\clang64\bin\opengl32.dll
msys2/MSYS2-packages#13 0x00007ff961df2858 in wined3d_init () from C:\msys64\clang64\bin\wined3d.dll
msys2/MSYS2-packages#14 0x00007ff961df0b94 in wined3d_init () from C:\msys64\clang64\bin\wined3d.dll
msys2/MSYS2-packages#15 0x00007ff961e6d501 in wined3d_create () from C:\msys64\clang64\bin\wined3d.dll
msys2/MSYS2-packages#16 0x00007ffa1daac418 in d3d9_init () from C:\msys64\clang64\bin\d3d9.dll
msys2/MSYS2-packages#17 0x00007ffa1daa2bde in Direct3DCreate9 () from C:\msys64\clang64\bin\d3d9.dll
msys2/MSYS2-packages#18 0x00007ff9624659f6 in GpuDescription::detect() () from C:\msys64\clang64\share\qt6\plugins\platforms\qwindows.dll
msys2/MSYS2-packages#19 0x00007ff96246864d in QWindowsOpenGLTester::supportedRenderers(QWindowsOpenGLTester::Renderer) () from C:\msys64\clang64\share\qt6\plugins\platforms\qwindows.dll
msys2/MSYS2-packages#20 0x00007ff962445867 in QWindowsStaticOpenGLContext::doCreate() () from C:\msys64\clang64\share\qt6\plugins\platforms\qwindows.dll
msys2/MSYS2-packages#21 0x00007ff962445b14 in QWindowsIntegration::createPlatformOpenGLContext(QOpenGLContext*) const () from C:\msys64\clang64\share\qt6\plugins\platforms\qwindows.dll
msys2/MSYS2-packages#22 0x00007ff962d9efd2 in QOpenGLContext::create() () from C:\msys64\clang64\bin\Qt6Gui.dll
msys2/MSYS2-packages#23 0x00007ff962a95863 in QGuiApplicationPrivate::init() () from C:\msys64\clang64\bin\Qt6Gui.dll
msys2/MSYS2-packages#24 0x00007ff9630d2756 in QApplicationPrivate::init() () from C:\msys64\clang64\bin\Qt6Widgets.dll
msys2/MSYS2-packages#25 0x00007ff601f8d538 in SharedTools::QtSingleApplication::QtSingleApplication(QString const&, int&, char**) ()
msys2/MSYS2-packages#26 0x00007ff601f8370d in main ()
(gdb)
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22623

**Comment by lazka** [comment] 2023-01-07 15:17
@pal1000 should we report something like this upstream?

**Comment by pal1000** [comment] 2023-01-07 16:06
A debug build may be needed for more complete backtrace.

**Comment by lazka** [comment] 2023-01-08 12:03
I noticed that there is also wine3d in there, which also gives me the same error messages when I install it, but doesn't crash.

**Comment by lazka** [comment] 2023-01-12 08:07
Since I can't reproduce (and the whole setup is quite uncommon) it's unlikely we'll get a better stack trace, so closing.

**Closed by lazka** 2023-01-12 08:07 UTC
Labels: bug
