### ISSUE TITLE
installing mingw-w64-i686-adwaita-icon-theme report error

### ISSUE THREAD

**Issue by lygstate** [msys2/MINGW-packages#8986] opened 2021-06-24 05:35 UTC
(274/302) installing mingw-w64-i686-adwaita-icon-theme                   [#######################################] 100%
error: command (/usr/bin/bash /usr/bin/bash -c . /tmp/alpm_Tonjol/.INSTALL; post_install 40.0-1 ) failed to execute correctly

**Comment by Biswa96** [comment] 2021-06-30 07:23
Closing as duplicate of https://github.com/msys2/MINGW-packages/issues/7611

**Closed by Biswa96** 2021-06-30 07:23 UTC
Labels: duplicate
