### ISSUE TITLE
MinGW64 GCC 11.2.0 exe files quarantined by ms defender antivirus

### ISSUE THREAD

**Issue by fawltylanguage** [msys2/MINGW-packages#10295] opened 2021-12-08 21:23 UTC
mingw64 cc1.exe, cc1plus.exe, f951.exe and lto1.exe were quarantined after the last update. I hope this is a false positive.

[cc1plus.exe on virustotal](https://www.virustotal.com/gui/file/aac45d0be8ce928c86e4746cfa945d91cf33b1e4f4bad6b2f5aa1bef1adcd614)

**Comment by k-takata** [comment] 2021-12-09 01:18
ucrt64's cc1obj.exe, cc1objplus.exe, f951.exe, and lto1.exe are also quarantined.

**Comment by Biswa96** [comment] 2021-12-09 05:46
This should be reported to Microsoft. As a temporary solution, try to exclude msys2 installation folder in Windows Defender. Or as a permanent solution, remove Windows Defender :)

**Comment by lazka** [comment] 2021-12-09 06:23
I've triggered a rebuild, maybe that helps

**Comment by chdka** [comment] 2021-12-09 09:39
> This should be reported to Microsoft. As a temporary solution, try to exclude msys2 installation folder in Windows Defender. Or as a permanent solution, remove Windows Defender :)

ESET NOD32 detects also these files and removes them

﻿mingw64\lib\gcc\x86_64-w64-mingw32\11.2.0\cc1.exe; a variant of Generik.DTPJCSO
mingw64\lib\gcc\x86_64-w64-mingw32\11.2.0\lto1.exe; a variant of Generik.EOCEILG
mingw64\lib\gcc\x86_64-w64-mingw32\11.2.0\f951.exe; a variant of Generik.KNALBKA

**Comment by omichel** [comment] 2021-12-09 10:23
For me, the following files were quarantined:
```
/mingw64/lib/gcc/x86_64-w64-mingw32/11.2.0/cc1.exe
/mingw64/lib/gcc/x86_64-w64-mingw32/11.2.0/cc1plus.exe
/mingw64/lib/gcc/x86_64-w64-mingw32/11.2.0/lto1.exe
```
I had to explicitly allow them in Windows Defender Antivirus as they were reported as [VirTool:Win32/Obfuscator.IY](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=VirTool%3aWin32%2fObfuscator.IY&threatid=2147632459)

**Comment by lazka** [comment] 2021-12-09 10:57
> I've triggered a rebuild, maybe that helps

didn't help, same issue (yay for reproducible builds 😛)

**Comment by BFamzz** [comment] 2021-12-09 13:25
In addition to the list of programs mentioned by @fawltylanguage `gnat1.exe, cc1obj.exe & cc1objplus.exe` were also flagged.

**Comment by cwebdesign** [comment] 2021-12-09 13:49
For now I have switched back to the previous version, it's not worth the risk.

**Comment by lazka** [comment] 2021-12-09 14:11
(for anyone worried, our packages are built in GitHub Actions using the official image and never touch another Windows PC after that)

**Comment by Biswa96** [comment] 2021-12-09 14:15
@cwebdesign What type of risks are to be worried about when GitHub is compiling most of the binaries? I assume GitHub is trusted.

**Comment by cwebdesign** [comment] 2021-12-09 16:49
> (for anyone worried, our packages are built in GitHub Actions using the official image and never touch another Windows PC after that)

Thanks! That is very reassuring (I wasn't aware of that).

**Comment by pfusik** [comment] 2021-12-09 18:30
> For now I have switched back to the previous version, it's not worth the risk.

@cwebdesign What's the `pacman` command for that?

**Comment by cwebdesign** [comment] 2021-12-09 19:37
> > For now I have switched back to the previous version, it's not worth the risk.
> 
> @cwebdesign What's the `pacman` command for that?

@pfusik This is what I used.

`pacman -U /var/cache/pacman/pkg/gcc-11.2.0-1-x86_64.pkg.tar.zst /var/cache/pacman/pkg/gcc-libs-11.2.0-1-x86_64.pkg.tar.zst
`

**Comment by oscarfv** [comment] 2021-12-09 21:50
Which version of the definitions caused this? I have 1.355.2.0 ready to install and 1.353.2238.0 was installed yesterday.

**Comment by kjliew** [comment] 2021-12-09 22:55
The -2- are fine. For those who don't keep packages cache, this is the way to go back to -2- version.
`$ pacman -U https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-gcc-libs-11.2.0-2-any.pkg.tar.zst https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-gcc-11.2.0-2-any.pkg.tar.zst`

This got to be fixed. Even if GitHub machines are trusted, no one would be sure if those machines were indeed infected. Setting exclusion or disabling antivirus/malware prevention is unacceptable.

**Comment by oscarfv** [comment] 2021-12-09 23:26
> This got to be fixed. Even if GitHub machines are trusted, no one would be sure if those machines were indeed infected. Setting exclusion or disabling antivirus/malware prevention is unacceptable.

False positives happen, and this is not the first time MSYS2 is affected. It would be a mistake if every time an antivirus botches a definition database we start chasing previous releases. And please note that antivirus usually do updates automatically and regularly, while our users need to execute pacman explicitly and do that every now and then. This puts hard limits on the real impact of any action on our side.

The correct course of action is to report the issue to MS and wait for the next virus definition. Meanwhile, set up an exclusion (temporarily, if you wish.)

**Comment by jeremyd2019** [comment] 2021-12-10 01:07
MS's reporting site: https://www.microsoft.com/en-us/wdsi/filesubmission.  Unfortunately, they seem to require a Microsoft account to even get started.

**Comment by sgnn7** [comment] 2021-12-10 02:03
My [linked MSYS2 issue](https://github.com/msys2/MSYS2-packages/issues/2728) has the detected list from Defender but I'll copy/paste it here since I don't see a comprehensive one in the comments:

```
<root>\mingw64\lib\gcc\x86_64-w64-mingw32\11.2.0\cc1.exe
<root>\mingw64\lib\gcc\x86_64-w64-mingw32\11.2.0\cc1obj.exe
<root>\mingw64\lib\gcc\x86_64-w64-mingw32\11.2.0\cc1objplus.exe
<root>\mingw64\lib\gcc\x86_64-w64-mingw32\11.2.0\cc1plus.exe
<root>\mingw64\lib\gcc\x86_64-w64-mingw32\11.2.0\f951.exe
<root>\mingw64\lib\gcc\x86_64-w64-mingw32\11.2.0\gnat1.exe
<root>\mingw64\lib\gcc\x86_64-w64-mingw32\11.2.0\lto1.exe
```

**Comment by jeremyd2019** [comment] 2021-12-10 06:22
In case nobody else did, I have uploaded the detected files to Microsoft.  Even so, perhaps the more people who report it the more it will be on their radar to fix.  Extra points if you have a Software Assurance support entitlement, apparently: https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/submission-guide#how-does-microsoft-prioritize-submissions

**Comment by BFamzz** [comment] 2021-12-10 07:25
Thank you @jeremyd2019  I have also done the same. Hopefully it shouldn't take them so long to give a feedback on the issue.

**Comment by omichel** [comment] 2021-12-10 09:39
The problem appears to be fixed for me after I updated msys2 right now. I could remove the exclusion I had set-up in Microsoft Defender Antivirus. Everything seems back to normal.

**Comment by pfusik** [comment] 2021-12-10 09:56
@omichel I see no update.

	C:\>pacman -Syu
	:: Synchronizing package databases...
	 mingw32 is up to date
	 mingw64 is up to date
	 ucrt64 is up to date
	 clang64 is up to date
	 msys is up to date
	:: Starting core system upgrade...
	 there is nothing to do
	:: Starting full system upgrade...
	 there is nothing to do

**Comment by omichel** [comment] 2021-12-10 09:58
I used `pacman -Syuu` to enable downgrades, this may be the trick...

**Comment by pfusik** [comment] 2021-12-10 09:59
Nope.

	C:\>pacman -Syuu
	:: Synchronizing package databases...
	 mingw32 is up to date
	 mingw64 is up to date
	 ucrt64 is up to date
	 clang64 is up to date
	 msys is up to date
	:: Starting core system upgrade...
	 there is nothing to do
	:: Starting full system upgrade...
	 there is nothing to do

**Comment by omichel** [comment] 2021-12-10 10:14
Maybe you already updated MSYS2 and the fix comes from an update of Microsoft Defender Antivirus rather than from the MSYS2 packages. Did you try to update the Antivirus?

**Comment by pfusik** [comment] 2021-12-10 10:18
Just updated the Defender (`Version created on: 12/10/2021 5:41 AM`) and

	C:\>pacman -S mingw-w64-x86_64-gcc
	warning: mingw-w64-x86_64-gcc-11.2.0-4 is up to date -- reinstalling
	resolving dependencies...
	looking for conflicting packages...

	Packages (1) mingw-w64-x86_64-gcc-11.2.0-4

	Total Installed Size:  162.39 MiB
	Net Upgrade Size:        0.00 MiB

	:: Proceed with installation? [Y/n]
	(1/1) checking keys in keyring                                           [#######################################] 100%
	(1/1) checking package integrity                                         [#######################################] 100%
	(1/1) loading package files                                              [#######################################] 100%
	(1/1) checking for file conflicts                                        [#######################################] 100%
	(1/1) checking available disk space                                      [#######################################] 100%
	warning: could not get file information for mingw64/lib/gcc/x86_64-w64-mingw32/11.2.0/cc1.exe
	warning: could not get file information for mingw64/lib/gcc/x86_64-w64-mingw32/11.2.0/cc1plus.exe
	warning: could not get file information for mingw64/lib/gcc/x86_64-w64-mingw32/11.2.0/lto1.exe
	:: Processing package changes...
	(1/1) reinstalling mingw-w64-x86_64-gcc                                  [#######################################] 100%

and the executables got quarantined again.

**Comment by omichel** [comment] 2021-12-10 10:27
I am getting this:
```bash
$ pacman -S mingw-w64-x86_64-gcc
warning: mingw-w64-x86_64-gcc-11.2.0-4 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-x86_64-gcc-11.2.0-4

Total Installed Size:  162.39 MiB
Net Upgrade Size:        0.00 MiB

:: Proceed with installation? [Y/n]
(1/1) checking keys in keyring                     [#####################] 100%
(1/1) checking package integrity                   [#####################] 100%
(1/1) loading package files                        [#####################] 100%
(1/1) checking for file conflicts                  [#####################] 100%
(1/1) checking available disk space                [#####################] 100%
:: Processing package changes...
(1/1) reinstalling mingw-w64-x86_64-gcc            [#####################] 100%
```
And all the gcc binaries get installed properly.
Also I have no allowed threat:
![image](https://user-images.githubusercontent.com/1264964/145558591-0f5d3104-84c5-4c4d-ad4d-5114f0465dba.png)
![image](https://user-images.githubusercontent.com/1264964/145558805-9a780901-b4bb-4a09-b6a0-41168e8ed1d4.png)
![image](https://user-images.githubusercontent.com/1264964/145559225-76192e54-2283-4c09-bf40-4c1ce8f3aae5.png)

**Comment by jessehager** [comment] 2021-12-10 15:50
I just checked cc1.exe in VirusTotal and there are 7 security vendors reporting it as malware now:

https://www.virustotal.com/gui/file/cf64b01ba52568558d885cfe26bcf75431e971d03c19820fb4e2391f13a8aee0

**Comment by scivision** [comment] 2021-12-10 17:02
based on https://github.com/msys2/MINGW-packages/issues/10295#issuecomment-990376654 for those also using gfortran, I downgraded to gcc / gfortran 11.2.0-2 by:

```sh
pacman -U https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-gcc-libs-11.2.0-2-any.pkg.tar.zst https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-gcc-11.2.0-2-any.pkg.tar.zst https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-gcc-fortran-11.2.0-2-any.pkg.tar.zst https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-gcc-libgfortran-11.2.0-2-any.pkg.tar.zst
```

**Comment by jeremyd2019** [comment] 2021-12-10 18:17
I got the following response from Microsoft:

> Analyst comments:
> 
> 
> Our team is working on this submission. Meantime could you please help us in provide us the below mention information regarding file for further analysis.
> - Exact scenario present at customer end
> - Source of the file
> - Any other details which will be helpful in analysis.
> 
> More detailed information about the approach and criteria categories currently used by the Microsoft researchers are available here:
> https://www.microsoft.com/en-us/wdsi/antimalware-support/malware-and-unwanted-software-evaluation-criteria
> 
> Thank you for contacting Microsoft.

There's no obvious way to provide any more information though.  I did give a link to this issue in the original report, so hopefully whatever they want to know is here...

**Comment by ENTPRESTIGIOUS** [comment] 2021-12-10 19:49
Umm yeah I've just started getting GCC and coincidentally, I saw this thread yesterday which was open like a day before yesterday.

**Comment by lazka** [comment] 2021-12-10 20:28
Building gcc (I just rebuilt cc1.exe multiple times) with an older crt-git helped:

* OK: https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-crt-git-9.0.0.6327.f29c1101f-1-any.pkg.tar.zst
* NOT OK: https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-crt-git-9.0.0.6346.6cc97775a-1-any.pkg.tar.zst

The range of commits in there for crt (excluding the OK commit) is:

```
git log --oneline  f33e6affb08e..6cc97775a .
6cc97775a crt: Regenerate Makefile.in
f8aed76f3 crt: Add bits GUID library
978afe0d1 ksuser: Add KSCATEGORY_VIDEO_CAMERA declaration.
4f35b2180 crt: Regenerate Makefile.in
0fbc918f9 crt: Include windowscodecs.c in libuuid.a.
5e7b53ab3 crt: duplicate query.def in ntquery.def
10d6d4e84 crt: Regenerate Makefile.in
```

**Comment by jeremyd2019** [comment] 2021-12-10 20:34
Based on [your diff](https://gist.github.com/lazka/5149a3e90e6934a9975da16437ac81c9) I am curious if rebuilding the 'OK' crt version with an updated gcc would then render it 'NOT OK'.

**Comment by lazka** [comment] 2021-12-10 21:08
good point. rebuilding "OK" f29c1101f with the latest gcc, then building cc1.exe still results in "OK"

**Comment by lazka** [comment] 2021-12-10 21:19
aha, simply rebuilding the latest crt helps

**Comment by lazka** [comment] 2021-12-11 09:51
But not when I fully rebuild.. same issue again. I give up..

**Comment by carlkl** [comment] 2021-12-11 10:52
Is is possible, that gcc 11.2.0-4 is the first version build with a gcc version with the AVX patch applied?

**Comment by pfusik** [comment] 2021-12-11 10:56
11.2.0-3 also got quarantined.

**Comment by lazka** [comment] 2021-12-11 10:58
> Is is possible, that gcc 11.2.0-4 is the first version build with a gcc version with the AVX patch applied?

yes, good point, I'll try reverting that.

**Comment by carlkl** [comment] 2021-12-11 11:08
BTW, there is an alternative proposed AVX patch from @katietz:
https://github.com/msys2/MINGW-packages/pull/8317#issuecomment-824548411
https://gist.github.com/katietz/ff16cbc77ee4de28335a6d6f2e8a4c6b

**Comment by MehdiChinoune** [comment] 2021-12-11 11:32
> Is is possible, that gcc 11.2.0-4 is the first version build with a gcc version with the AVX patch applied?

I don't think so, the AVX patch was applied 5 weeks ago (11.2.0-2 https://github.com/msys2/MINGW-packages/commit/eb328862a77becf0ff33504446a1e30cd69b4d52) and we didn't see any reports about this issue.
The last rebuild (11.2.0-3 https://github.com/msys2/MINGW-packages/commit/4ac72566a4f0846ccefa5dd0f06c056a56084356) was to add g++-mapper-server.

**Comment by oscarfv** [comment] 2021-12-11 13:36
> I got the following response from Microsoft:
> 
> > Analyst comments:
> > Our team is working on this submission. Meantime could you please help us in provide us the below mention information regarding file for further analysis.
> > 
> > * Exact scenario present at customer end
> > * Source of the file
> > * Any other details which will be helpful in analysis.
> > 
> > More detailed information about the approach and criteria categories currently used by the Microsoft researchers are available here:
> > https://www.microsoft.com/en-us/wdsi/antimalware-support/malware-and-unwanted-software-evaluation-criteria
> > Thank you for contacting Microsoft.
> 
> There's no obvious way to provide any more information though. I did give a link to this issue in the original report, so hopefully whatever they want to know is here...

VirusTotal says that Microsoft no longer flags cc1.exe as malware:

https://www.virustotal.com/gui/file/cf64b01ba52568558d885cfe26bcf75431e971d03c19820fb4e2391f13a8aee0

That's the same cc1.exe file that was previously flagged and mentioned by @jessehager. Yesterday 14 vendors flagged that archive, today they are 12.

However, the file reported on the first message of this issue still is marked as malicious by Microsoft.

@jeremyd2019 : what is the SHA2 of the file you reported to MS?

**Comment by jeremyd2019** [comment] 2021-12-11 19:40
I'm not really sure, the webpage with the submission doesn't say.  I uploaded `{mingw,ucrt}64/lib/gcc/x86_64-w64-mingw32/11.2.0/*1*.exe`, I'm pretty sure from 11.2.0-4.

**Comment by carlkl** [comment] 2021-12-13 09:40
I updated my Msys2 (mingw32, mingw64, ucrt64) with gcc-11.2.0-5. No complains from defender up to now. I also tested UCRT64 cc1.exe with virustotal. Everything is green.

**Comment by pfusik** [comment] 2021-12-13 09:58
I confirm gcc-11.2.0-5 is fine with Defender 1.355.173.0 (12/13/2021 4:53 AM). Thank you!

**Comment by lazka** [comment] 2021-12-13 10:01
yesterday it was still red.. oh well. It's hard to figure out what it doesn't like with it constantly changing :(

**Comment by kmilos** [comment] 2021-12-13 10:32
> I confirm gcc-11.2.0-5 is fine with Defender 1.355.173.0

Same here, thanks.

**Comment by rnicolas** [comment] 2021-12-13 10:51
I also confirm gcc-11.2.0-5 is working again with Windows Defender 1.355.168.0 and 1.355.173.0

**Comment by barotto** [comment] 2021-12-13 16:12
cc1plus in gcc-11.2.0-5 is still quarantined with Windows Defender 1.355.187.0

**Comment by chdka** [comment] 2021-12-13 16:52
I also confirm all is fine now with ESET

**Comment by rnicolas** [comment] 2021-12-13 17:04
> cc1plus in gcc-11.2.0-5 is still quarantined with Windows Defender 1.355.187.0

I've updated my Windows Defender to your version, and it hasn't been quarantined. Can someone else check it?

**Comment by barotto** [comment] 2021-12-13 17:12
> > cc1plus in gcc-11.2.0-5 is still quarantined with Windows Defender 1.355.187.0
> 
> I've updated my Windows Defender to your version, and it hasn't been quarantined. Can someone else check it?

On my system (W10 2004) it's identified as `Trojan:Script/Sabsik.FL.A!ml`

**Comment by carlkl** [comment] 2021-12-13 18:23
@katietz, FYI: https://github.com/msys2/MINGW-packages/issues/10295#issuecomment-991602005 and https://github.com/lazka/MINGW-packages/commit/1a3db62374f14c4adead49ee628a64e3d084352d. 
It is not obvious however, why GCC with Stephen Kitt's [avx patch](https://github.com/msys2/MINGW-packages/pull/9998) causes these problems with antivirus detection.

**Comment by rnicolas** [comment] 2021-12-20 14:39
Should we consider this issue as resolved?

**Comment by lazka** [comment] 2022-01-07 08:16
Yeah. Did another rebuild today, and Defender is still happy.

**Closed by lazka** 2022-01-07 08:16 UTC

**Comment by kmilos** [comment] 2022-01-10 11:07
I'm afraid this is back for me w/ build 11.2.0-6 and definitions 1.355.1684.0

**Comment by lazka** [comment] 2022-01-10 11:43
hm, I checked all files to virtustotal before upload.

**Comment by carlkl** [comment] 2022-01-10 12:40
Hi, I checked the 64bit builds with virustotal right now:

- ucrt64 binaries are green
- mingw64 binaries: cc1.exe and cc1plus.exe are red, but only with Rising:

Rising: HackTool.Obfuscator!8.236. On the other had: all others are green.

**Comment by kmilos** [comment] 2022-01-10 12:47
Could've been just that particular Defender definitions version... Indeed, no problem w/ ucrt64 binaries and the updated 1.355.1690.0 definitions.

**Comment by kmilos** [comment] 2022-01-11 12:02
`C:\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\11.2.0\cc1.exe` quarantined again with 1.355.1736.0

**Comment by AlexandraTrifan** [comment] 2022-01-11 12:56
> I'm afraid this is back for me w/ build 11.2.0-6 and definitions 1.355.1684.0 (`Program:Win32/Uwamson.A!ml` this time)

Hi,

I also got the following warning : `Program:Win32/Uwamson.A!ml` for the following files:
```
C:\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\11.2.0\cc1.exe
C:\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\11.2.0\cc1plus.exe
```

Clean install of msys2; gcc build 11.2.0-6.

**Comment by carlkl** [comment] 2022-01-26 10:08
All green (Virustotal) for UCRT64 and MINGW64 `cc1.exe`, `cc1plus.exe`, `f951.exe`, `lto1.exe` 11.2.0-8

**Comment by kmilos** [comment] 2022-01-26 11:35
11.2.0-8 installed ok for me this time

**Comment by AlexandraTrifan** [comment] 2022-01-26 11:48
gcc 11.2.0-8 also works for me
thank you!

**Comment by carlkl** [comment] 2022-01-26 13:31
BTW I have the strange effect with Virustotal, that the same file uploaded to Virustotal is marked red with two scanners, whereas the same binary handed over as link is green. (And I don't think this is a problem with my computer)

https://github.com/LibreDWG/libredwg/releases/tag/0.12.4.4367 libredwg-0.12.4.4367-win64.zip

I guess these results can vary from day to day, depending the time Virustotal performes the scan.
