### ISSUE TITLE
About the new TeXLive packages

### ISSUE THREAD

**Issue by angelog0** [msys2/MINGW-packages#8500] opened 2021-04-28 22:29 UTC
Usually I install TeXLive on GNU/Linux, macOS, WSL[2] and Termux using the `install-tl` script (choosing `/opt/texlive' as installation directory, and all components...).

Can I install your product that way? How?

**Comment by naveen521kk** [comment] 2021-09-06 13:33
Duplicate of https://github.com/msys2/msys2-texlive/issues/8

**Closed by naveen521kk** 2021-09-06 13:33 UTC
