### ISSUE TITLE
mingw-w64-openssl missing the file: applink.c

### ISSUE THREAD

**Issue by taozuhong** [msys2/MINGW-packages#16081] opened 2023-03-07 03:18 UTC
### Description / Steps to reproduce the issue

1. pacman -S openssl
2. ls /ucrt64/include/openssl/*.c

### Expected behavior

1. pacman -S openssl
2. ls /ucrt64/include/openssl/applink.c

### Actual behavior

The openssl headers should contain the file: `applink.c`

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

**Comment by Biswa96** [comment] 2023-03-07 04:35
> The openssl headers should contain the file: applink.c

Why should a include directory contain a .c source file? Could you provide steps to reproduce the issue where applink.c is required?

**Comment by MehdiChinoune** [comment] 2023-03-07 04:56
duplicate of #15142

**Closed by MehdiChinoune** 2023-03-07 04:56 UTC
Labels: bug
