### ISSUE TITLE
[python-gmpy2] SystemError on import

### ISSUE THREAD

**Issue by yuriteixeira-arq-br** [msys2/MINGW-packages#6350] opened 2020-04-04 21:05 UTC
Hello,
I get this error and traceback when importing sympy.
Windows 10, all defaults, not fresh install but just updated. Let me know if you need more information.
I'm sorry for the trouble and thank you for your time.

```
$ python3
Python 3.8.2 (default, Feb 27 2020, 05:27:33)  [GCC 9.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:/msys64/mingw64/lib/python3.8/site-packages/sympy/__init__.py", line 57, in <module>
    from .core import *
  File "C:/msys64/mingw64/lib/python3.8/site-packages/sympy/core/__init__.py", line 4, in <module>
    from .sympify import sympify, SympifyError
  File "C:/msys64/mingw64/lib/python3.8/site-packages/sympy/core/sympify.py", line 8, in <module>
    from .compatibility import iterable, string_types, range
  File "C:/msys64/mingw64/lib/python3.8/site-packages/sympy/core/compatibility.py", line 744, in <module>
    gmpy = import_module('gmpy2', min_module_version='2.0.0',
  File "C:/msys64/mingw64/lib/python3.8/site-packages/sympy/external/importtools.py", line 133, in import_module
    mod = __import__(module, **__import__kwargs)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/gmpy2/__init__.py", line 1, in <module>
    from .gmpy2 import *
SystemError: Size of PY_LONG_LONG and mp_bitcnt_t not compatible (_WIN64 && MPIR)

```

**Comment by lazka** [comment] 2020-04-07 19:13
confirmed

**Comment by lazka** [comment] 2020-04-07 19:17
Duplicate of #6058

**Closed by lazka** 2020-04-07 19:17 UTC
