### ISSUE TITLE
python-cx-logging not conforming to our directory structure

### ISSUE THREAD

**Issue by elieux** [msys2/MINGW-packages#9279] opened 2021-08-03 09:50 UTC
> $ pacman -Fl mingw-w64-x86_64-python-cx-logging
> mingw-w64-x86_64-python-cx-logging mingw64/
> mingw-w64-x86_64-python-cx-logging mingw64/cx_Logging-doc/
> mingw-w64-x86_64-python-cx-logging mingw64/cx_Logging-doc/LICENSE.txt
> mingw-w64-x86_64-python-cx-logging mingw64/cx_Logging-doc/README.txt
> mingw-w64-x86_64-python-cx-logging mingw64/Include/
> mingw-w64-x86_64-python-cx-logging mingw64/Include/cx_Logging.h
> mingw-w64-x86_64-python-cx-logging mingw64/lib/
> mingw-w64-x86_64-python-cx-logging mingw64/lib/python3.9/
> mingw-w64-x86_64-python-cx-logging mingw64/lib/python3.9/site-packages/
> mingw-w64-x86_64-python-cx-logging mingw64/lib/python3.9/site-packages/cx_Logging-3.0-py3.9.egg-info/
> mingw-w64-x86_64-python-cx-logging mingw64/lib/python3.9/site-packages/cx_Logging-3.0-py3.9.egg-info/dependency_links.txt
> mingw-w64-x86_64-python-cx-logging mingw64/lib/python3.9/site-packages/cx_Logging-3.0-py3.9.egg-info/PKG-INFO
> mingw-w64-x86_64-python-cx-logging mingw64/lib/python3.9/site-packages/cx_Logging-3.0-py3.9.egg-info/SOURCES.txt
> mingw-w64-x86_64-python-cx-logging mingw64/lib/python3.9/site-packages/cx_Logging-3.0-py3.9.egg-info/top_level.txt
> mingw-w64-x86_64-python-cx-logging mingw64/lib/python3.9/site-packages/cx_Logging.cp39-mingw_x86_64.pyd
> mingw-w64-x86_64-python-cx-logging mingw64/Libs/
> mingw-w64-x86_64-python-cx-logging mingw64/Libs/libcx_Logging.a

Looks like it's half in MSVC mode.

**Comment by revelator** [comment] 2021-08-04 09:35
yep looks like it :/

**Comment by revelator** [comment] 2021-08-04 15:07
i have a small patch which hammers things into something a bit more in line with our setup here.
[0002-unix-like.zip](https://github.com/msys2/MINGW-packages/files/6932252/0002-unix-like.zip)

**Comment by Biswa96** [comment] 2021-08-05 15:46
@marcelotduarte Is it possible to fix this in upstream? I am thinking of like this

```py
if sys.platform == "win32":
    if self.compiler.compiler_type == "msvc":
        # Install in Libs, Include etc.
    else:
        # Install in lib, include, share etc.
```

**Comment by marcelotduarte** [comment] 2021-08-05 17:47
In the merged PR https://github.com/anthony-tuininga/cx_Logging/pull/5 I changed the way of distributing these files. No more data_files.

For the "Libs" directory change to "lib" the check for the compiler is not correct because I use, for example, python from python.org and gcc from mingw32/msys2 and this check breaks it.
But I'll think about this case and should suggest a PR and see if he accepts. The problem is that he's taking too long to release the version.

**Comment by Biswa96** [comment] 2021-08-05 19:01
> python from python.org and gcc from mingw32/msys2 and this check breaks it.

The combination is incompatible to begin with.

> The problem is that he's taking too long to release the version.

No problem, the patches can be imported here until next version is released.

**Comment by marcelotduarte** [comment] 2021-08-05 19:02
> > python from python.org and gcc from mingw32/msys2 and this check breaks it.
> 
> The combination is incompatible to begin with.

Isn't. I use this and works!

**Comment by revelator** [comment] 2021-08-06 09:16
i was wondering if the include file should not be located in include/python<version> instead of include ?

**Closed** 2022-11-17 07:43 UTC
