### ISSUE TITLE
ffmpeg 4.4-5 weird error

### ISSUE THREAD

**Issue by thesword53** [msys2/MINGW-packages#8983] opened 2021-06-23 15:27 UTC
`C:/msys64/mingw64/bin/ffmpeg.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory`

**Comment by lazka** [comment] 2021-06-23 15:28
should be fixed shortly

**Comment by Biswa96** [comment] 2021-06-23 15:34
Apology for the issue. CI is currently building it. You could see the progress here https://packages.msys2.org/queue. 

Duplicate of https://github.com/msys2/MINGW-packages/issues/8981

**Comment by Biswa96** [comment] 2021-06-23 20:43
Fixed package is in pacman repository now. Use `pacman -Syyu` to update those.

**Closed by Biswa96** 2021-06-23 20:43 UTC
Labels: duplicate

**Comment by lazka** [comment] 2021-06-23 20:50
thanks @Biswa96
