### ISSUE TITLE
pacman update: failed to commit transaction ... libuuid.a exists

### ISSUE THREAD

**Issue by sdbbs** [msys2/MINGW-packages#10764] opened 2022-02-16 14:41 UTC
Just tried to update today:

```none
$ pacman -Syu
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 ucrt64 is up to date
 clang64 is up to date
 msys is up to date
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (9) mingw-w64-ucrt-x86_64-libwinpthread-git-9.0.0.6373.5be8fcd83-2
             mingw-w64-x86_64-binutils-2.37-5
             mingw-w64-x86_64-crt-git-9.0.0.6373.5be8fcd83-2
             mingw-w64-x86_64-headers-git-9.0.0.6373.5be8fcd83-2
             mingw-w64-x86_64-libwinpthread-git-9.0.0.6373.5be8fcd83-2
             mingw-w64-x86_64-python-soupsieve-2.3.1-1
             mingw-w64-x86_64-windows-default-manifest-6.4-4
             mingw-w64-x86_64-winpthreads-git-9.0.0.6373.5be8fcd83-2
             mingw-w64-x86_64-winstorecompat-git-9.0.0.6373.5be8fcd83-2

Total Installed Size:  212.93 MiB
Net Upgrade Size:       -0.04 MiB

:: Proceed with installation? [Y/n] y
(9/9) checking keys in keyring                     [#####################] 100%
(9/9) checking package integrity                   [#####################] 100%
(9/9) loading package files                        [#####################] 100%
(9/9) checking for file conflicts                  [#####################] 100%
error: failed to commit transaction (conflicting files)
mingw-w64-x86_64-crt-git: /mingw64/lib/libuuid.a exists in filesystem
Errors occurred, no packages were upgraded.
```

Not sure if it is a good idea, but let's try renaming the conflicting file - yup, that makes the upgrade pass:

```none
$ mv /mingw64/lib/libuuid.a /mingw64/lib/old.libuuid.a

$ pacman -Syu
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 ucrt64 is up to date
 clang64 is up to date
 msys is up to date
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (9) mingw-w64-ucrt-x86_64-libwinpthread-git-9.0.0.6373.5be8fcd83-2
             mingw-w64-x86_64-binutils-2.37-5
             mingw-w64-x86_64-crt-git-9.0.0.6373.5be8fcd83-2
             mingw-w64-x86_64-headers-git-9.0.0.6373.5be8fcd83-2
             mingw-w64-x86_64-libwinpthread-git-9.0.0.6373.5be8fcd83-2
             mingw-w64-x86_64-python-soupsieve-2.3.1-1
             mingw-w64-x86_64-windows-default-manifest-6.4-4
             mingw-w64-x86_64-winpthreads-git-9.0.0.6373.5be8fcd83-2
             mingw-w64-x86_64-winstorecompat-git-9.0.0.6373.5be8fcd83-2

Total Installed Size:  212.93 MiB
Net Upgrade Size:       -0.04 MiB

:: Proceed with installation? [Y/n] y
(9/9) checking keys in keyring                     [#####################] 100%
(9/9) checking package integrity                   [#####################] 100%
(9/9) loading package files                        [#####################] 100%
(9/9) checking for file conflicts                  [#####################] 100%
(9/9) checking available disk space                [#####################] 100%
:: Processing package changes...
(1/9) upgrading mingw-w64-ucrt-x86_64-libwinpt...  [#####################] 100%
(2/9) upgrading mingw-w64-x86_64-binutils          [#####################] 100%
(3/9) upgrading mingw-w64-x86_64-headers-git       [#####################] 100%
(4/9) upgrading mingw-w64-x86_64-crt-git           [#####################] 100%
(5/9) upgrading mingw-w64-x86_64-libwinpthread-git [#####################] 100%
(6/9) upgrading mingw-w64-x86_64-python-soupsieve  [#####################] 100%
(7/9) upgrading mingw-w64-x86_64-windows-defau...  [#####################] 100%
(8/9) upgrading mingw-w64-x86_64-winpthreads-git   [#####################] 100%
(9/9) upgrading mingw-w64-x86_64-winstorecompa...  [#####################] 100%
```

So, I guess I'm fine now - but it's maybe a good idea I post this report anyways.

**Comment by Biswa96** [comment] 2022-02-16 14:48
libuuid.a is only owned by crt package.

```
$ pacman -F /mingw64/lib/libuuid.a
mingw64/lib/libuuid.a is owned by mingw64/mingw-w64-x86_64-crt-git 9.0.0.6373.5be8fcd83-2
```

Theoretically, there is no other package to conflict with that file. Wondering what the cause is.

**Comment by lazka** [comment] 2022-02-16 17:26
It used to be in https://packages.msys2.org/package/mingw-w64-x86_64-pupnp but was renamed there

**Comment by Biswa96** [comment] 2022-02-16 17:29
AFAIK, it was libupnp.a but OP mentioned libuuid.a.

**Comment by lazka** [comment] 2022-02-16 17:30
uh, oops

**Comment by lazka** [comment] 2022-03-12 19:38
Since there haven't been any other reports, I'd guess some package build/installer happened to write this file for you, and this isn't a general problem.

So, I'm going to close this for now.

**Closed by lazka** 2022-03-12 19:38 UTC
