### ISSUE TITLE
mingw-w64-x86_64-emacs-28.2-3 cpu load while idle and memory leak

### ISSUE THREAD

**Issue by chrislimpach** [msys2/MINGW-packages#16375] opened 2023-03-23 00:59 UTC
### Description / Steps to reproduce the issue

I upgraded to 28.2-3 yesterday and found the emacs process this morning using almost 64GB of memory, i.e. almost all memory.

I was able to reproduce the cpu/memory usage fairly easily by starting emacs with -Q, pasting the following into *scratch*:
```
(require 'uniquify)
(set-variable 'uniquify-buffer-name-style 'reverse)
```
and then pressing C-x C-e at the end of each line.

I observed the process in Process Explorer, and it shows the main thread using 2-3% cpu (on a 32 logical cpu system) and memory steadily increasing, after executing the lisp code.

I'm not able to reproduce the same issue after downgrading to 28.2-2.

I installed the ucrt64 version for comparison and I'm seeing the issue as well.

I don't believe the issue is specific to the quoted lisp code, this is just what happened to be at the top of my .emacs.el.

### Expected behavior

less cpu/memory usage

### Actual behavior

constant cpu usage and memory leak

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by oscarfv** [comment] 2023-03-25 15:12
Probably related to #16190.

Emacs 28.2-3 seems to be utterly broken.

**Comment by svraka** [comment] 2023-05-29 15:56
Hey, @chrislimpach, does this bug still occur with the latest build? If it was related to #16190, then it was most likely fixed in https://github.com/msys2/MINGW-packages/pull/17342 but the root cause needs further investigations, see https://github.com/msys2/MINGW-packages/issues/17343.

**Comment by Biswa96** [comment] 2024-06-05 04:47
Please re-open the issue if this still happens with latest emacs package.

**Closed by Biswa96** 2024-06-05 04:47 UTC
Labels: bug
