### ISSUE TITLE
Linking error generating static executables after the lastest gfortran update

### ISSUE THREAD

**Issue by javila** [msys2/MINGW-packages#7023] opened 2020-09-23 19:48 UTC
I'm unable to generate any static executable since the last gcc/gfortran update!?!

Here's a simple source test file: **lineq.f90**
```fortran
program LinearEquations
  implicit none

  double precision :: A(3,3), b(3)
  integer :: i, pivot(3), ok
  
  A(1,:)=(/3, 1, 3/)
  A(2,:)=(/1, 5, 9/)
  A(3,:)=(/2, 6, 5/)
  
  b(:)=(/-1, 3, -3/)

  call DGESV(3, 1, A, 3, pivot, b, 3, ok)

  do i=1, 3
    write(*,9) i, b(i)
  end do  

9 format('x[', i1, ']= ', f5.2)  
end program LinearEquations
```

Linking error:
```
$ gfortran -o lineq.exe lineq.f90 -static-libgfortran /mingw64/lib/libopenblas.a
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0\libgfortran.a(read.o):(.text$_gfortrani_convert_real+0xb7): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `strtoflt128'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0\libgfortran.a(read.o):(.text$_gfortrani_convert_infnan+0xb3): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `strtoflt128'
collect2.exe: error: ld returned 1 exit status
```

I never got this error before. I suppose the problem appeared after the last gcc/gfortran update since I usually keep MSYS2 up to date.

```
$ gfortran -v
Using built-in specs.
COLLECT_GCC=C:\msys64\mingw64\bin\gfortran.exe
COLLECT_LTO_WRAPPER=C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-10.2.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++ --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts=yes --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --disable-plugin --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev3, Built by MSYS2 project' --with-bugurl=https://github.com/msys2/MINGW-packages/issues --with-gnu-as --with-gnu-ld --with-boot-ldflags='-pipe -Wl,--dynamicbase,--high-entropy-va,--nxcompat -Wl,--disable-dynamicbase,--default-image-base-low -static-libstdc++ -static-libgcc' 'LDFLAGS_FOR_TARGET=-pipe -Wl,--dynamicbase,--high-entropy-va,--nxcompat' --enable-linker-plugin-flags='LDFLAGS=-static-libstdc++\ -static-libgcc\ -pipe\ -Wl,--dynamicbase,--high-entropy-va,--nxcompat\ -Wl,--stack,12582912'
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (Rev3, Built by MSYS2 project)
```

**Comment by jeremyd2019** [comment] 2020-09-23 20:22
Interesting.  I'm guessing those are weak symbols?  This looks rather like #6986.  Adding -Wl,--default-image-base-low should work around it.

I'm thinking I need to write a bug report for binutils upstream for this.

**Comment by javila** [comment] 2020-09-23 21:19
@jeremyd2019, just to make things a bit clearer...

I get no error when linking to libopenblas.dll, libgfortran-5.dll and libquadmath-0.dll (all them required to run my program). Also I get no error when linking directly to /mingw64/lib/libopenblas.a. I only get the error when trying to use -static-libgfortran.

Anyway, the workaround did the trick. Thanks.

**Comment by mati865** [comment] 2020-09-23 22:35
Yeah, this is another case of Binutils/GCC bug related to weak symbols:
```
$ nm /mingw64/lib/gcc/x86_64-w64-mingw32/10.2.0/libgfortran.a | grep -i " [w|v] "
                 w strtoflt128

$ nm /mingw64/lib/gcc/x86_64-w64-mingw32/10.2.0/libgfortran.a | grep strtoflt128
0000000000000000 A .weak.strtoflt128._gfortrani_set_integer
                 w strtoflt128
                 U strtoflt128
```

**Comment by lazka** [comment] 2020-09-24 10:02
just throwing this out there as a temporary option, we could change the binutils default back and use `-Wl,--default-image-base-high` in the makepkg config, so only our packages are affected.

**Comment by mati865** [comment] 2020-09-24 11:20
Yeah, considering the amount of reports LD seems not ready yet to use high imagebase.

**Comment by lazka** [comment] 2020-09-28 09:59
Should be "fixed" now, by changing the default back.

**Comment by lazka** [comment] 2021-01-31 15:21
Still the same error with binutils 2.36:

```
$ gfortran -o lineq.exe lineq.f90 -static-libgfortran /mingw64/lib/libopenblas.a
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0\libgfortran.a(read.o):(.text$_gfortrani_convert_real+0xb7): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `strtoflt128'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0\libgfortran.a(read.o):(.text$_gfortrani_convert_infnan+0xb3): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `strtoflt128'
collect2.exe: error: ld returned 1 exit status
```

**Comment by okhlybov** [comment] 2021-02-07 12:21
Confirmed. All static linking of gfortran code currently fails with exactly the same error.

**Comment by lazka** [comment] 2021-02-07 12:35
yes, see known issues: https://www.msys2.org/news/#2021-01-31-aslr-enabled-by-default

It seemed wrong to not enable ASLR for everyone just because of this. Sorry :/

**Comment by FrankHB** [comment] 2021-02-07 13:13
> yes, see known issues: https://www.msys2.org/news/#2021-01-31-aslr-enabled-by-default
> 
> It seemed wrong to not enable ASLR for everyone just because of this. Sorry :/

So should this issue be reopened, or kept closed as dup to #6986?

I don't think it comfortable to enable the change by default with uncertain possibility to fail. In my case, I build the binary essentionally as `g++ *.cpp` and something strange occurs like this:

```
:Dependency.cpp:(.debug_frame$_ZSt12__get_helperILy0ESt12_PlaceholderILi1EEJSt5_BindIFPFNSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEERKN8platform14FileDescriptorEES0_ILi2EEEEEERT0_RSt11_Tuple_implIXT_EJSH_DpT1_EE+0x1c): relocation truncated to fit: IMAGE_REL_AMD64_SECREL against `.debug_frame$_ZSt12__get_helperILy0ESt12_PlaceholderILi1EEJSt5_BindIFPFNSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEERKN8platform14FileDescriptorEES0_ILi2EEEEEERT0_RSt11_Tuple_implIXT_EJSH_DpT1_EE'
```

Note it is not against an undefined symbol, so [the upstream report](https://sourceware.org/bugzilla/show_bug.cgi?id=26659) literally does not cover this. It still has the same root cause (more or less) because `-Wl,--default-image-base-low` works, though. Or is this a really new bug so I should file a new issue according to https://www.msys2.org/news/#2021-01-31-aslr-enabled-by-default?

**Comment by jeremyd2019** [comment] 2021-02-07 20:10
On Sun, 7 Feb 2021, FrankHB wrote:

> ```
> :Dependency.cpp:(.debug_frame$_ZSt12__get_helperILy0ESt12_PlaceholderILi1EEJSt5_BindIFPFNSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEERKN8platform14FileDescriptorEES0_ILi2EEEEEERT0_RSt11_Tuple_implIXT_EJSH_DpT1_EE+0x1c): relocation truncated to fit: IMAGE_REL_AMD64_SECREL against `.debug_frame$_ZSt12__get_helperILy0ESt12_PlaceholderILi1EEJSt5_BindIFPFNSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEERKN8platform14FileDescriptorEES0_ILi2EEEEEERT0_RSt11_Tuple_implIXT_EJSH_DpT1_EE'
> ```
>
> Note it is not against an undefined symbol, so [the upstream report](https://sourceware.org/bugzilla/show_bug.cgi?id=26659) literally does not cover this. It still has the same root cause (more or less) because `-Wl,--default-image-base-low` works, though. Or is this a really new bug so I should file a new issue according to https://www.msys2.org/news/#2021-01-31-aslr-enabled-by-default?

This is not the same issue.  It's also a different relocation type.  I
think I've seen it before, but not sure.  It doesn't make a lot of sense
to me why there would be relocations in debug symbols anyway.

**Comment by ofry** [comment] 2021-03-30 14:24
Please reopen. It breaks GHC compiling, breaks GDB debugging...

See https://gitlab.haskell.org/ghc/ghc/-/issues/16780#note_342584

https://gitlab.haskell.org/ghc/ghc/-/issues/16780#note_342715

**Comment by lazka** [comment] 2021-03-30 14:33
sure, any help appreciated.

**Closed** 2021-04-01 17:55 UTC
