### ISSUE TITLE
Mingw should not distribute libvulkan-1.dll, that's violate the vulkan spec

### ISSUE THREAD

**Issue by lygstate** [msys2/MINGW-packages#11618] opened 2022-05-07 09:22 UTC
rational:
https://vulkan.lunarg.com/doc/view/1.2.148.1/windows/loader_and_layer_interface.html

The Vulkan loader library file name is vulkan-.dll. For example, for Vulkan version 1.X on Windows the library filename is vulkan-1.dll

**Comment by lazka** [comment] 2022-05-07 10:52
What's the downside/problems of that status quo besides violating the spec?

**Comment by mmuetzel** [comment] 2022-05-07 11:00
I'd guess it makes it a little more tricky to use `LoadLibrary` if the filename deviates from the spec. Any other reasons?

**Comment by lygstate** [comment] 2022-05-07 14:37
The rational https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/11550

**Comment by MehdiChinoune** [comment] 2022-08-28 08:45
duplicate of #2673

**Closed by MehdiChinoune** 2022-08-28 08:45 UTC
