### ISSUE TITLE
BINUTILS 2.40-1 linker fails with MS lib files

### ISSUE THREAD

**Issue by dfileccia** [msys2/MINGW-packages#15544] opened 2023-02-07 20:09 UTC
### Description / Steps to reproduce the issue

Link a Microsoft LIB format using "-l:". Example: -l:foo.lib

### Expected behavior

Generate an EXE or DLL

### Actual behavior

:-1: error: internal error: aborting at ../../binutils-2.40/ld/ldlang.c:527 in compare_section
:-1: error: please report this bug
:-1: error: collect2.exe: error: ld returned 1 exit status
:-1: error: [Makefile.Debug:90: ../../../bin64/plugins/canbus/fe2.dll] Error 1

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22000

### MINGW environments affected

- [x] MINGW64
- [x] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment] 2023-02-07 20:25
Duplicate of https://github.com/msys2/MINGW-packages/issues/15469

**Closed by Biswa96** 2023-02-07 20:25 UTC
Labels: bug

**Comment by lazka** [comment] 2023-02-08 10:25
Please update and try again now.

**Comment by dfileccia** [comment] 2023-02-08 15:16
Everything works now since 2.40-2 came down. Thank you.

David Fileccia

I have been all things unholy. If God can work through

me, he can work through anyone. -- Francis of Assisi

________________________________
