### ISSUE TITLE
texlive-formats-extra fails to install

### ISSUE THREAD

**Issue by luau-project** [msys2/MINGW-packages#21205] opened 2024-06-20 12:29 UTC
### Description / Steps to reproduce the issue

Steps to reproduce:
1. In order to make sure I was facing an issue, I got a clean MSYS2 install (uninstall MSYS2 then reinstall). Probably fails on "dirty" environments too;
2. Open a shell (mingw64, ucrt64, clang64);
3. Update it running ```pacman -Syuu``` as many times required;
4. Run a command to install the package: 
    * mingw64: ```pacman -S mingw-w64-x86_64-texlive-formats-extra```
    * ucrt64: ```pacman -S mingw-w64-ucrt-x86_64-texlive-formats-extra```
    * clang64: ```pacman -S mingw-w64-clang-x86_64-texlive-formats-extra```

### Expected behavior

The package should install normally.

### Actual behavior

Judging by the error message, there is a mismatch in ZLIB version

* mingw64:
    ![Screenshot from 2024-06-20 09-17-14](https://github.com/msys2/MINGW-packages/assets/18295115/42f7ecc6-6edf-4129-bfd3-c3a7c121cf03)

* ucrt64:
    ![Screenshot from 2024-06-20 09-06-13](https://github.com/msys2/MINGW-packages/assets/18295115/fdbd1103-a6e5-45db-bb50-97c031d0eae3)

* clang64:
    ![Screenshot from 2024-06-20 09-23-58](https://github.com/msys2/MINGW-packages/assets/18295115/c0d14d2c-72c5-4296-80c1-88d3c159d450)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment] 2024-06-20 12:31
Duplicate of #19981

**Closed by Biswa96** 2024-06-20 12:31 UTC
Labels: bug
