### ISSUE TITLE
clang with libc++ produces linker errors

### ISSUE THREAD

**Issue by ab396356** [msys2/MINGW-packages#5405] opened 2019-05-24 16:35 UTC
### Using:

Software | Version
-------- | -------
msys2-x86_64-20190523.exe | latest
mingw-w64-x86_64-clang | 8.0.0-2
mingw-w64-x86_64-libc++ | 8.0.0-2
mingw-w64-x86_64-libc++abi | 8.0.0-2

### Attempting to build "hello.cpp":

```c++
#include <iostream>

int main()
{
    std::cout << "Hello world!" << std::endl;
}
```

### With command:

```text
clang++ -stdlib=libc++ -o hello.exe hello.cpp -v 1>fail.txt 2>&1
```

### Contents of "fail.txt":

https://pastebin.com/2RfpR0BU

Let me know what I'm doing wrong, otherwise please fix libc++ soon.

**Comment by oscarfv** [comment] 2019-05-25 03:36
See #4782.

**Comment by ZachBacon** [comment] 2019-07-11 03:38
So I've done some testing. To get things properly linked with libc++ you also need to link to at least libc++abi and think this is needed but perhaps not libclang. I'm in the middle of testing some major testing with that and so far, things work.

**Comment by mati865** [comment] 2019-07-11 07:36
I should work: `clang++ -stdlib=libc++ -lc++abi hello.cpp`. Clang package may need few tweaks though.

**Comment by ZachBacon** [comment] 2019-07-11 14:07
It looks like the clang package isn't being rebuilt against itself.

**Comment by ZachBacon** [comment] 2019-07-14 22:10
The main blocker besides the -stdlib command not exactly being honoured, would be lld working, at least in regards to shared libs, upstream there is some work being done, but It'll be a little bit before that's done. But for now, things sorta work. If you like static libs.

**Comment by oscarfv** [comment] 2019-07-14 22:52
LLVM/Clang 8 finally is able to produce a correct build of one of my projects that creates quite a few shared libraries (it is a plugin-based architecture). At least for 64 bits. 32 bits has problems with throwing/catching exceptions.

I was delighted to see lld working as well. The only "issue" I found was lld incapability to link shared libraries without an import library.

@ZachBacon : are those lld issues related to -stdlib/libc++ specifically?

**Comment by mati865** [comment] 2019-07-15 08:42
> The main blocker besides the -stdlib command not exactly being honoured

That option works, it removes libstdc++ and uses libc++ instead. Libc++abi and libunwind are missing from link args but that's upstream issue.

> would be lld working, at least in regards to shared lib

LLD 8 sort of works for 64 bit libs, for 32 bit you need current trunk. There are still issues when crt isn't built with Clang+Lld but it's much better on current trunk. 

> The only "issue" I found was lld incapability to link shared libraries without an import library.

Seems like it won't be fixed anytime soon and it won't make it for LLD 9.

**Comment by selassje** [comment] 2020-03-16 00:21
I am seeing a bit different issue when compiling this piece of code from benchmark:
https://github.com/google/benchmark/blob/master/cmake/std_regex.cpp

$ clang++ -stdlib=libc++ -std=c++11 -o hello.exe cmake/std_regex.cpp -lc++ -lc++abi -v
clang version 9.0.1 (https://github.com/msys2/MINGW-packages.git 5e3b8820ed9f04221affee4197e458aca2612e87)
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: C:\msys64\mingw64\bin
 "C:\\msys64\\mingw64\\bin\\clang++.exe" -cc1 -triple x86_64-w64-windows-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name std_regex.cpp -mrelocation-model pic -pic-level 2 -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -momit-leaf-frame-pointer -v -resource-dir "C:\\msys64\\mingw64\\lib\\clang\\9.0.1" -internal-isystem "C:\\msys64\\mingw64\\x86_64-w64-mingw32\\include\\c++\\v1" -internal-isystem "C:\\msys64\\mingw64\\include\\c++\\v1" -internal-isystem "C:\\msys64\\mingw64\\lib\\clang\\9.0.1\\include" -internal-isystem "C:\\msys64\\mingw64\\x86_64-w64-mingw32/sys-root/mingw/include" -internal-isystem "C:\\msys64\\mingw64\\x86_64-w64-mingw32\\include" -internal-isystem "C:\\msys64\\mingw64\\include" -std=c++11 -fdeprecated-macro -fdebug-compilation-dir "F:\\Repos\\benchmark_issue_943" -ferror-limit 19 -fmessage-length 0 -fno-use-cxa-atexit -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fseh-exceptions -fdiagnostics-show-option -faddrsig -o "C:\\msys64\\tmp\\std_regex-2d48dc.o" -x c++ cmake/std_regex.cpp
clang -cc1 version 9.0.1 based upon LLVM 9.0.1 default target x86_64-w64-windows-gnu
ignoring nonexistent directory "C:\msys64\mingw64\x86_64-w64-mingw32\include\c++\v1"
ignoring nonexistent directory "C:\msys64\mingw64\x86_64-w64-mingw32/sys-root/mingw/include"
#include "..." search starts here:
#include <...> search starts here:
 C:\msys64\mingw64\include\c++\v1
 C:\msys64\mingw64\lib\clang\9.0.1\include
 C:\msys64\mingw64\x86_64-w64-mingw32\include
 C:\msys64\mingw64\include
End of search list.
 "C:\\msys64\\mingw64\\bin\\ld" -m i386pep -Bdynamic -o hello.exe "C:\\msys64\\mingw64\\x86_64-w64-mingw32\\lib\\crt2.o" "C:\\msys64\\mingw64\\lib\\gcc\\x86_64-w64-mingw32\\9.3.0\\crtbegin.o" "-LC:\\msys64\\mingw64\\lib\\gcc\\x86_64-w64-mingw32\\9.3.0" "-LC:\\msys64\\mingw64\\x86_64-w64-mingw32\\lib" "-LC:\\msys64\\mingw64\\lib" "-LC:\\msys64\\mingw64\\x86_64-w64-mingw32/sys-root/mingw/lib" "C:\\msys64\\tmp\\std_regex-2d48dc.o" -lc++ -lc++abi -lc++ -lmingw32 -lgcc_s -lgcc -lmoldname -lmingwex -lmsvcrt -lpthread -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 -lgcc_s -lgcc -lmoldname -lmingwex -lmsvcrt "C:\\msys64\\mingw64\\lib\\gcc\\x86_64-w64-mingw32\\9.3.0\\crtend.o"
C:\msys64\mingw64\lib/libc++.a(locale.cpp.obj): duplicate section `.rdata$_ZTSSt9exception[_ZTSSt9exception]' has different size
C:\msys64\mingw64\lib/libc++.a(locale.cpp.obj): duplicate section `.rdata$_ZTSSt13runtime_error[_ZTSSt13runtime_error]' has different size
C:\msys64\mingw64\lib/libc++.a(locale.cpp.obj): duplicate section `.rdata$_ZTISt13runtime_error[_ZTISt13runtime_error]' has different size
C:\msys64\mingw64\lib/libc++.a(locale.cpp.obj): duplicate section `.rdata$_ZTSNSt3__114__shared_countE[_ZTSNSt3__114__shared_countE]' has different size
C:\msys64\mingw64\lib/libc++.a(memory.cpp.obj): duplicate section `.rdata$_ZTSSt9exception[_ZTSSt9exception]' has different size
C:\msys64\mingw64\lib/libc++.a(memory.cpp.obj): duplicate section `.rdata$_ZTSNSt3__114__shared_countE[_ZTSNSt3__114__shared_countE]' has different size
C:\msys64\mingw64\lib/libc++.a(memory.cpp.obj): duplicate section `.rdata$_ZTSNSt3__119__shared_weak_countE[_ZTSNSt3__119__shared_weak_countE]' has different size
C:\msys64\mingw64\lib/libc++.a(memory.cpp.obj): duplicate section `.rdata$_ZTINSt3__119__shared_weak_countE[_ZTINSt3__119__shared_weak_countE]' has different size
C:\msys64\mingw64\lib/libc++.a(new.cpp.obj): duplicate section `.rdata$_ZTSSt9exception[_ZTSSt9exception]' has different size
C:\msys64\mingw64\lib/libc++.a(regex.cpp.obj): duplicate section `.rdata$_ZTSSt9exception[_ZTSSt9exception]' has different size
C:\msys64\mingw64\lib/libc++.a(regex.cpp.obj): duplicate section `.rdata$_ZTSSt13runtime_error[_ZTSSt13runtime_error]' has different size
C:\msys64\mingw64\lib/libc++.a(regex.cpp.obj): duplicate section `.rdata$_ZTISt13runtime_error[_ZTISt13runtime_error]' has different size
C:\msys64\mingw64\lib/libc++.a(regex.cpp.obj): duplicate section `.rdata$_ZTSNSt3__111regex_errorE[_ZTSNSt3__111regex_errorE]' has different size
C:\msys64\mingw64\lib/libc++.a(regex.cpp.obj): duplicate section `.rdata$_ZTINSt3__111regex_errorE[_ZTINSt3__111regex_errorE]' has different size
C:\msys64\mingw64\lib/libc++.a(string.cpp.obj): duplicate section `.rdata$_ZTSSt9exception[_ZTSSt9exception]' has different size
C:\msys64\mingw64\lib/libc++.a(string.cpp.obj): duplicate section `.rdata$_ZTISt11logic_error[_ZTISt11logic_error]' has different size
C:\msys64\mingw64\lib/libc++.a(string.cpp.obj): duplicate section `.rdata$_ZTSSt12length_error[_ZTSSt12length_error]' has different size
C:\msys64\mingw64\lib/libc++.a(string.cpp.obj): duplicate section `.rdata$_ZTISt12length_error[_ZTISt12length_error]' has different size
C:\msys64\mingw64\lib/libc++.a(system_error.cpp.obj): duplicate section `.rdata$_ZTSSt9exception[_ZTSSt9exception]' has different size
C:\msys64\mingw64\lib/libc++.a(system_error.cpp.obj): duplicate section `.rdata$_ZTSSt13runtime_error[_ZTSSt13runtime_error]' has different size
C:\msys64\mingw64\lib/libc++.a(system_error.cpp.obj): duplicate section `.rdata$_ZTISt13runtime_error[_ZTISt13runtime_error]' has different size
C:\msys64\mingw64\lib/libc++.a(vector.cpp.obj): duplicate section `.rdata$_ZTSSt9exception[_ZTSSt9exception]' has different size
C:\msys64\mingw64\lib/libc++.a(vector.cpp.obj): duplicate section `.rdata$_ZTISt11logic_error[_ZTISt11logic_error]' has different size
C:\msys64\mingw64\lib/libc++.a(vector.cpp.obj): duplicate section `.rdata$_ZTSSt12length_error[_ZTSSt12length_error]' has different size
C:\msys64\mingw64\lib/libc++.a(vector.cpp.obj): duplicate section `.rdata$_ZTISt12length_error[_ZTISt12length_error]' has different size
C:\msys64\mingw64\lib/libc++.a(ios.cpp.obj): duplicate section `.rdata$_ZTSSt9exception[_ZTSSt9exception]' has different size
C:\msys64\mingw64\lib/libc++.a(ios.cpp.obj): duplicate section `.rdata$_ZTSSt13runtime_error[_ZTSSt13runtime_error]' has different size
C:\msys64\mingw64\lib/libc++.a(ios.cpp.obj): duplicate section `.rdata$_ZTISt13runtime_error[_ZTISt13runtime_error]' has different size
C:\msys64\mingw64\lib/libc++.a(future.cpp.obj): duplicate section `.rdata$_ZTSSt9exception[_ZTSSt9exception]' has different size
C:\msys64\mingw64\lib/libc++.a(future.cpp.obj): duplicate section `.rdata$_ZTISt11logic_error[_ZTISt11logic_error]' has different size
C:\msys64\mingw64\lib/libc++.a(future.cpp.obj): duplicate section `.rdata$_ZTSNSt3__114__shared_countE[_ZTSNSt3__114__shared_countE]' has different size
C:\msys64\mingw64\lib/libc++abi.a(stdlib_exception.cpp.obj): duplicate section `.rdata$_ZTSSt9exception[_ZTSSt9exception]' has different size
C:\msys64\mingw64\lib/libc++abi.a(stdlib_stdexcept.cpp.obj): duplicate section `.rdata$_ZTSSt9exception[_ZTSSt9exception]' has different size
C:\msys64\mingw64\lib/libc++abi.a(stdlib_stdexcept.cpp.obj): duplicate section `.rdata$_ZTISt11logic_error[_ZTISt11logic_error]' has different size
C:\msys64\mingw64\lib/libc++abi.a(stdlib_stdexcept.cpp.obj): duplicate section `.rdata$_ZTSSt13runtime_error[_ZTSSt13runtime_error]' has different size
C:\msys64\mingw64\lib/libc++abi.a(stdlib_stdexcept.cpp.obj): duplicate section `.rdata$_ZTISt13runtime_error[_ZTISt13runtime_error]' has different size
C:\msys64\mingw64\lib/libc++abi.a(stdlib_stdexcept.cpp.obj): duplicate section `.rdata$_ZTSSt12length_error[_ZTSSt12length_error]' has different size
C:\msys64\mingw64\lib/libc++abi.a(stdlib_stdexcept.cpp.obj): duplicate section `.rdata$_ZTISt12length_error[_ZTISt12length_error]' has different size
C:\msys64\mingw64\lib/libc++abi.a(stdlib_typeinfo.cpp.obj): duplicate section `.rdata$_ZTSSt9exception[_ZTSSt9exception]' has different size
C:\msys64\mingw64\lib/libc++abi.a(stdlib_new_delete.cpp.obj): duplicate section `.rdata$_ZTSSt9exception[_ZTSSt9exception]' has different size
C:\msys64\mingw64\lib/libc++abi.a(cxa_personality.cpp.obj): duplicate section `.rdata$_ZTSSt9exception[_ZTSSt9exception]' has different size
C:\msys64\mingw64\lib/libc++abi.a(cxa_default_handlers.cpp.obj): duplicate section `.rdata$_ZTSSt9exception[_ZTSSt9exception]' has different size
C:\msys64\mingw64\lib/libc++abi.a(cxa_aux_runtime.cpp.obj): duplicate section `.rdata$_ZTSSt9exception[_ZTSSt9exception]' has different size

msys2-x86_64-20190524.exe | latest
-- | --
mingw-w64-x86_64-clang | 9.0.1-1
mingw-w64-x86_64-libc++ | 9.0.1-1
mingw-w64-x86_64-libc++abi | 9.0.1-1

**Closed** 2020-04-09 09:29 UTC

**Comment by intractabilis** [comment] 2020-06-18 05:33
Package|Version
-|-
mingw-w64-x86_64-clang|10.0.0-2
mingw-w64-x86_64-llvm |10.0.0-2
mingw-w64-x86_64-libc++|10.0.0-2
mingw-w64-x86_64-lld|10.0.0-2

The issue is closed, I assumed it is supposed to work in LLVM 10. However,
```cpp
// main.cpp
#include <stdexcept>

int main(int argc, char* argv[]) {
    throw std::runtime_error("Hello World!!!");
    return 0;
}
```

```
clang++ -v -stdlib=libc++ -fuse-ld=lld -o main.exe main.cpp
```
```
clang version 10.0.0 (https://github.com/msys2/MINGW-packages.git 7211ffb882cc3b7e7583c518aad45a22b278bc81)
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: c:\msys64\mingw64\bin
 "c:\\msys64\\mingw64\\bin\\clang++.exe" -cc1 -triple x86_64-w64-windows-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name main.cpp -mrelocation-model pic -pic-level 2 -mthread-model posix -mframe-pointer=none -fmath-errno -fno-rounding-math -masm-verbose -mconstructor-aliases -munwind-tables -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -v -resource-dir "c:\\msys64\\mingw64\\lib\\clang\\10.0.0" -internal-isystem "c:\\msys64\\mingw64\\x86_64-w64-mingw32\\include\\c++\\v1" -internal-isystem "c:\\msys64\\mingw64\\include\\c++\\v1" -internal-isystem "c:\\msys64\\mingw64\\lib\\clang\\10.0.0\\include" -internal-isystem "c:\\msys64\\mingw64\\x86_64-w64-mingw32/sys-root/mingw/include" -internal-isystem "c:\\msys64\\mingw64\\x86_64-w64-mingw32\\include" -internal-isystem "c:\\msys64\\mingw64\\include" -fdeprecated-macro -fdebug-compilation-dir "D:\\Work\\PSU\\CS-541\\PRG\\001\\clangtest" -ferror-limit 19 -fmessage-length 0 -fno-use-cxa-atexit -fgnuc-version=4.2.1 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fseh-exceptions -fdiagnostics-show-option -faddrsig -o "C:\\Users\\anon\\AppData\\Local\\Temp\\main-f9657d.o" -x c++ main.cpp
clang -cc1 version 10.0.0 based upon LLVM 10.0.0 default target x86_64-w64-windows-gnu
ignoring nonexistent directory "c:\msys64\mingw64\x86_64-w64-mingw32\include\c++\v1"
ignoring nonexistent directory "c:\msys64\mingw64\x86_64-w64-mingw32/sys-root/mingw/include"
#include "..." search starts here:
#include <...> search starts here:
 c:\msys64\mingw64\include\c++\v1
 c:\msys64\mingw64\lib\clang\10.0.0\include
 c:\msys64\mingw64\x86_64-w64-mingw32\include
 c:\msys64\mingw64\include
End of search list.
 "c:\\msys64\\mingw64\\bin\\ld.lld" -m i386pep -Bdynamic -o main.exe "c:\\msys64\\mingw64\\x86_64-w64-mingw32\\lib\\crt2.o" "c:\\msys64\\mingw64\\lib\\gcc\\x86_64-w64-mingw32\\10.1.0\\crtbegin.o" "-Lc:\\msys64\\mingw64\\lib\\gcc\\x86_64-w64-mingw32\\10.1.0" "-Lc:\\msys64\\mingw64\\x86_64-w64-mingw32\\lib" "-Lc:\\msys64\\mingw64\\lib" "-Lc:\\msys64\\mingw64\\x86_64-w64-mingw32/sys-root/mingw/lib" "C:\\Users\\anon\\AppData\\Local\\Temp\\main-f9657d.o" -lc++ -lmingw32 -lgcc_s -lgcc -lmoldname -lmingwex -lmsvcrt -lpthread -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 -lgcc_s -lgcc -lmoldname -lmingwex -lmsvcrt "c:\\msys64\\mingw64\\lib\\gcc\\x86_64-w64-mingw32\\10.1.0\\crtend.o"
lld-link: error: duplicate symbol: typeinfo name for std::exception
>>> defined at C:\Users\anon\AppData\Local\Temp\main-f9657d.o
>>> defined at libc++.a(stdlib_stdexcept.cpp.obj)

lld-link: error: duplicate symbol: typeinfo name for std::runtime_error
>>> defined at C:\Users\anon\AppData\Local\Temp\main-f9657d.o
>>> defined at libc++.a(stdlib_stdexcept.cpp.obj)

lld-link: error: duplicate symbol: typeinfo for std::runtime_error
>>> defined at C:\Users\anon\AppData\Local\Temp\main-f9657d.o
>>> defined at libc++.a(stdlib_stdexcept.cpp.obj)

lld-link: error: duplicate symbol: typeinfo name for std::exception
>>> defined at C:\Users\anon\AppData\Local\Temp\main-f9657d.o
>>> defined at libc++.a(cxa_personality.cpp.obj)

lld-link: error: duplicate symbol: typeinfo name for std::exception
>>> defined at C:\Users\anon\AppData\Local\Temp\main-f9657d.o
>>> defined at libc++.a(stdlib_exception.cpp.obj)

lld-link: error: duplicate symbol: typeinfo name for std::exception
>>> defined at C:\Users\anon\AppData\Local\Temp\main-f9657d.o
>>> defined at libc++.a(stdlib_typeinfo.cpp.obj)

lld-link: error: duplicate symbol: typeinfo name for std::exception
>>> defined at C:\Users\anon\AppData\Local\Temp\main-f9657d.o
>>> defined at libc++.a(cxa_default_handlers.cpp.obj)

lld-link: error: duplicate symbol: typeinfo name for std::exception
>>> defined at C:\Users\anon\AppData\Local\Temp\main-f9657d.o
>>> defined at libc++.a(cxa_aux_runtime.cpp.obj)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by mati865** [comment] 2020-06-18 12:35
I haven't tested code with exceptions when opening that PR (samples without exceptions work fine), could you open new issue?
I don't know why it doesn't work, maybe it only works when libc++abi and libc++ are built with clang/lld.

**Comment by intractabilis** [comment] 2020-06-18 17:08
> maybe it only works when libc++abi and libc++ are built with clang/lld

Check the command line in the linker output, the driver automatically adds `-lc++`, when `-stdlib=libc++` is specified. `libc++abi` is not present in the package.

> I haven't tested code with exceptions

I don't think it's about exceptions. I bet any code that instantiates RTTI from libc++ will have this problem.

> could you open new issue?

sure

**Comment by mati865** [comment] 2020-06-18 17:14
> Check the command line in the linker output, the driver automatically adds -lc++, when -stdlib=libc++ is specified. libc++abi is not present in the package.

No, I mean when libc++ is itself build by clang/lld like here https://github.com/mstorsjo/llvm-mingw. At MSYS2 everything is built by GCC+LD.

**Comment by intractabilis** [comment] 2020-06-18 17:18
Ah, got it. It could be the reason.

**Comment by deannagarcia** [comment] 2022-10-07 22:06
I'm still hitting this problem. Did anyone get this working or find a good workaround?

**Comment by mati865** [comment] 2022-10-07 22:38
We need more info like output of failed command with `-v` and source code that reproduces the problem because it works fine with code posted in this issue.

**Comment by deannagarcia** [comment] 2022-10-14 20:38
This was user error, but thanks for the quick response!
