### ISSUE TITLE
freerdp build fails

### ISSUE THREAD

**Issue by pfeatherstone** [msys2/MINGW-packages#5718] opened 2019-08-14 13:44 UTC
I ran: " MINGW_INSTALLS=mingw64 makepkg-mingw -sLf" inside the mingw-64-freerdp folder and got a whole host of errors relating to redeclarations. In my case the errors popped up in ntlm.c. I'm sure there are others. 

Example:
```
C:/msys64/home/pf-windows-dev/MINGW-packages/mingw-w64-freerdp/src/FreeRDP-2.0.0-rc4/winpr/libwinpr/sspi/NTLM/ntlm.h:86:2: error: redeclaration of enumerator 'MsvAvDnsDomainName'
   86 |  MsvAvDnsDomainName,
      |  ^~~~~~~~~~~~~~~~~~
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/sspi.h:10,
                 from C:/msys64/home/pf-windows-dev/MINGW-packages/mingw-w64-freerdp/src/FreeRDP-2.0.0-rc4/winpr/include/winpr/sspi.h:34,
                 from C:/msys64/home/pf-windows-dev/MINGW-packages/mingw-w64-freerdp/src/FreeRDP-2.0.0-rc4/winpr/libwinpr/sspi/NTLM/ntlm.c:25:
C:/msys64/mingw64/x86_64-w64-mingw32/include/ntsecapi.h:787:73: note: previous definition of 'MsvAvDnsDomainName' was here
  787 |     MsvAvEOL,MsvAvNbComputerName,MsvAvNbDomainName,MsvAvDnsComputerName,MsvAvDnsDomainName,MsvAvDnsTreeName,MsvAvFlags
      |                                                                         ^~~~~~~~~~~~~~~~~~
In file included from C:/msys64/home/pf-windows-dev/MINGW-packages/mingw-w64-freerdp/src/FreeRDP-2.0.0-rc4/winpr/libwinpr/sspi/NTLM/ntlm.c:33:
```

**Comment by sfhacker** [comment] 2019-08-15 12:10
@pfeatherstone I have no idea about this command 'mingw64 makepkg-mingw -sLf' but freerdp builds fine here (MSYS/MinGW // GCC 8.3.0 x86_64) using (freerdp) master branch.

We used cmake to build freerdp from source (master branch).

You should try again using cmake command.

**Comment by pfeatherstone** [comment] 2019-08-15 12:33
@sfhacker The documentation for this github repository explains how to build mingw packages. https://github.com/msys2/MINGW-packages#documentation

**Comment by pfeatherstone** [comment] 2019-08-15 12:43
@sfhacker I should have added that this documentation details to use the command: "mingw64 makepkg-mingw -sLf" inside the folder MINGW-packages/mingw-w64-freerdp

**Comment by sfhacker** [comment] 2019-08-15 13:11
@pfeatherstone It is working fine here. Perhaps your environment is broken or 'polluted' somehow.

Have you tried using cmake command?

![image](https://user-images.githubusercontent.com/25817529/63096659-d690b580-bf44-11e9-939a-697dbae28b8b.png)

...
...
![image](https://user-images.githubusercontent.com/25817529/63096680-e5776800-bf44-11e9-8915-9a4314cdd1a9.png)

Have you been able to fix the compilation errors? We don't see those errors in our MSYS/MINGW environment.

**Comment by Alexpux** [comment] 2019-08-15 13:13
The problem maybe because we switch to Win7 target by default

**Comment by sfhacker** [comment] 2019-08-15 13:20
@pfeatherstone You sound confused! Can you post the output of cmake command here?

**Comment by pfeatherstone** [comment] 2019-08-15 13:31
@sfhacker I think the confusion is that you're using MSYS version 1 with MINGW32. I'm using MSYS version 2 with MINGW64. The latter provides two environments: the MSYS2 environment and the MINGW64 environment. You get different behaviour when building in each one.

**Comment by sfhacker** [comment] 2019-08-15 13:42
Our environment works fine. We build large projects on a daily basis (e.g. OpenLDAP, Heimdal Kerberos, FreeRADIUS, etc). But your environment seems broken. You should sort that out first.

**Comment by sfhacker** [comment] 2019-08-15 14:25
I repeat myself: our env. works fine.
We have run out of ideas here! Perhaps you could try reinstalling your broken MSYS/MinGW envs or seek advice from someone with experience building apps on Windows.

![image](https://user-images.githubusercontent.com/25817529/63101289-25dbe380-bf4f-11e9-9861-a7763710cd2b.png)

**Comment by stahta01** [comment] 2019-08-15 15:21
> @sfhacker I think the confusion is that you're using MSYS version 1 with MINGW32. I'm using MSYS version 2 with MINGW64. The latter provides two environments: the MSYS2 environment and the MINGW64 environment. You get different behaviour when building in each one.

And, you are using the correct MSYS2 environment, right?

Tim S.

**Comment by stahta01** [comment] 2019-08-15 15:44
@pfeatherstone I just duplicated the build error; I will spend a hour or trying to fix it.

Tim S.

**Comment by pfeatherstone** [comment] 2019-08-15 16:22
The suspense is intense

**Comment by sfhacker** [comment] 2019-08-15 16:29
At last someone knows what has to be done! We are mere beginners here!

**Comment by stahta01** [comment] 2019-08-15 16:33
Going to build next without patch mingw-w64-redefinitions.patch.

I have decided the quickest solution is to edit mingw-w64-redefinitions.patch.

Tim S.

**Comment by stahta01** [comment] 2019-08-15 21:23
I am not making much progress; but, still trying for a short time in hope of making some progress. 
Tim S.

**Comment by stahta01** [comment] 2019-08-15 22:03
The problem is beyond me at this time. 

Link to my work; no idea if the work is and good.
[freerdp](https://github.com/stahta01/MINGW-packages/tree/freerdp)

Tim S.

**Comment by sfhacker** [comment] 2019-08-16 00:12
We were able to build it from source without any patching to the MinGW runtime but to freerdp codebase. There are freerdp outstanding issues (compilation and linking) from last year. No one has cared to fix and merge them to master branch.

Anyway, thanks for your time on this issue.

**Comment by stahta01** [comment] 2019-08-16 01:46
@sfhacker where can the patches you used be found?

Tim S.

**Comment by Alexpux** [comment] 2019-08-16 04:34
@stahta01 I think properly need to check ````__MINGW64_VERSION_MAJOR```` to not break old MINGW32 build

**Comment by pfeatherstone** [comment] 2019-08-16 07:56
So the MINGW32 build doesn't work for me either (when using MSYS2). Are there any major differences between MSYS and MSYS2? I thought it was just the pacman package manager introduced in MSYS2, which incidentally is what i'm using to install dependencies.

**Comment by Alexpux** [comment] 2019-08-16 08:13
@pfeatherstone there are two different MINGW runtimes. 
One from https://mingw.org and another from https://mingw-w64.org
Read [https://sourceforge.net/p/mingw-w64/wiki2/History/](https://sourceforge.net/p/mingw-w64/wiki2/History/)

MINGW from mingw.org is outdated and not actively developed.

MSYS2 project use mingw-w64 runtime for 32 and 64 bit.

**Comment by pfeatherstone** [comment] 2019-08-16 09:24
I'm using mingw-w64 since that's what's shipped with MSYS2. Since neither the MINGW32 or the MINGW64 builds work and I have a working CYGWIN build (though much slower) and I'm running out of time, I will have to leave it at that.

I might look into a freerdp proxy server than runs on linux so I can apply my mods there and connect with rdesktop on windows.

**Comment by sfhacker** [comment] 2019-08-16 11:40
There seems to be a lot of confusion and ignorance about certain projects. The same applies to CYGWIN, which does not produce native Windows binaries.
There are dozens of MSYS/MinGW binary distributions out there we could give them a try. The one we have been using for a long time works like a charm. We build large projects from source on a daily basis.
Regarding freerdp patches, there are outstanding compilation and linking issues reported last year. I believe patches should be merged into the main branch. Have a look at these issues: https://github.com/FreeRDP/FreeRDP/issues/5026 https://github.com/FreeRDP/FreeRDP/issues/5000

We can make the freerdp native Windows binaries  (master branch) available to anyone. Just let us know.

**Comment by stahta01** [comment] 2019-08-16 12:27
@sfhacker so was you lying when you said you patched freerdp in order to build it?
Or are you just never going to sure the patches?

Tim S.

**Comment by stahta01** [comment] 2019-08-16 13:55
Looks like sfhacker was likely building git master with patches.

Tim S.

**Comment by stahta01** [comment] 2019-08-16 15:24
[FreeRDP.zip](https://github.com/msys2/MINGW-packages/files/3510174/FreeRDP.zip)

Added patches I used to compile FreeRDP using Mingw32 and Mingw64 prompts.
Used these commands to build
`cmake -G"MSYS Makefiles" -DCMAKE_C_COMPILER=$MINGW_PREFIX/bin/gcc.exe -DCMAKE_CXX_COMPILER=$MINGW_PREFIX/bin/g++.exe -DWITH_CLIENT=ON ..

make VERBOSE=1 -j1
`
Tim S.

**Comment by sfhacker** [comment] 2019-08-16 15:39
I will test this right now!
Note that we produce MinGW Makefiles and native Windows binaries! I won't use the cmake command line proposed by you (@stahta01 )

**Comment by stahta01** [comment] 2019-08-16 15:52
Note: I have desire to use freerdp and I got it to build using changes copied from [astrand mingw-part2 branch](https://github.com/astrand/FreeRDP.git).

No idea if the patches make sense; I have no knowledge of FreeRDP code.

Tim S.

**Comment by pfeatherstone** [comment] 2019-08-16 19:06
@stahta01 Thank you! I will test on Monday

**Comment by stahta01** [comment] 2019-08-16 22:37
Found a possible code bug in freerdp; but, I have no idea which is wrong.

In file include/freerdp/server/rdpdr.h CreationTime and 5 others are of type UINT64 that maybe should be LARGE_INTEGER. MinGW64 has LARGE_INTEGER and [Microsoft aggrees](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/ns-ntifs-_file_directory_information)

I see no way to proceed on building the server code because I do not believe the freerdp is correct.

Tim S.

**Comment by stahta01** [comment] 2019-08-17 19:52
Decided the server code can not be built using MSys2 Mingw64 GCC.

Tim S.

**Comment by pfeatherstone** [comment] 2019-08-18 10:43
Above you mentioned you managed to build using mingw32 and mingw64. Do you mean you can’t hold using MSYS2 environment ?

**Comment by pfeatherstone** [comment] 2019-08-18 10:44
Build*

**Comment by stahta01** [comment] 2019-08-19 14:49
> Above you mentioned you managed to build using mingw32 and mingw64. Do you mean you can’t hold using MSYS2 environment ?

Using git master I can build using my git package.
[freerdp-git](https://github.com/stahta01/MINGW-packages/tree/freerdp)

**Comment by stahta01** [comment] 2019-08-19 15:00
I am likely done working on this package; feel free to commit my work. I have no plans to do a pull-request.

**Comment by Biswa96** [comment] 2023-08-31 18:25
freerdp is available in mingw packages repository. See this page for more information https://packages.msys2.org/base/mingw-w64-freerdp

Though it requires some patches to workaround the build issues.

**Closed by Biswa96** 2023-08-31 18:25 UTC
