### ISSUE TITLE
SDL2 linking (with CMake build) is broken since 2.0.12-2

### ISSUE THREAD

**Issue by rzumer** [msys2/MINGW-packages#6380] opened 2020-04-12 14:51 UTC
We rely on msys2 and SDL2 for CI. Our Windows runs have failed since the 2.0.12-2 release. See https://github.com/Arisotura/melonDS/runs/580755133 as a sample run. Earlier commits built with 2.0.12-1 came out fine.

**Comment by mati865** [comment] 2020-04-12 14:59
Possibly duplicate of https://github.com/msys2/MINGW-packages/issues/6379

**Comment by rzumer** [comment] 2020-04-12 15:26
Looks like going through pkg-config to find SDL2 instead of CMake's `find_package` solves the linking errors (see https://github.com/nadiaholmquist/melonDS/runs/580805962), but this is a regression from 2.0.12-1 and below.

**Comment by Alexpux** [comment] 2020-04-12 17:00
@rzumer paste here linking command

**Comment by rzumer** [comment] 2020-04-12 17:30
I don't have a Windows setup to get the linking command, but how can you tell it is an upstream issue when 2.0.12-1 worked without a problem?

**Comment by Alexpux** [comment] 2020-04-12 17:45
@rzumer 2.0.12 was build with autoconf scripts and it generte its own *.cmake files. Now we built with cmake and cmake generate its *.cmake files for SDL2 targets. At least FAudio builds fine with this cmake files. So maybe you can look into FAudio cmake scripts how they link with SDL2

**Comment by klei1984** [comment] 2020-04-19 18:01
I face the same or a very similar issue. I am at mingw-w64-i686-SDL2 2.0.12-4 now. I have no control over what version of msys2 packages to stick with, I am stuck at the latest versions.

So far I used the following cmake commands that worked on linux as well as on windows/mingw (mingw-w64-i686-SDL2 2.0.9-1):
```
find_package(SDL2 REQUIRED)
target_link_libraries(${GAME_BINARY} ${SDL2_LIBRARIES})
```

`SDL2_DIR` is set to `C:/msys64/mingw32/lib/cmake/SDL2`  on windows.

According to the MSYS2 [SDL package page](https://packages.msys2.org/base/mingw-w64-SDL2)  the upstream is basically the SDL homapage. This is the corresponding developer package there: 
`https://libsdl.org/release/SDL2-devel-2.0.12-mingw.tar.gz`

This is the upstream's cmake config file: `SDL2-2.0.12\i686-w64-mingw32\lib\cmake\SDL2\sdl2-config.cmake`

This is the one found in the MSYS2 package: `msys64\mingw32\lib\cmake\SDL2\SDL2Config.cmake`
```
/mingw32/lib/cmake/SDL2/SDL2Config.cmake
/mingw32/lib/cmake/SDL2/SDL2ConfigVersion.cmake
/mingw32/lib/cmake/SDL2/SDL2Targets-release.cmake
/mingw32/lib/cmake/SDL2/SDL2Targets.cmake
```

The two CMAKE scripts are totally different.

The last MSYS2 package that had the upstream CMAKE script is this `http://repo.msys2.org/mingw/i686/mingw-w64-i686-SDL2-2.0.12-1-any.pkg.tar.xz`

And the commit that broke backwards compatibility to some existing cmake project files and basic cross-compatibility between linux/sdl2 and msys2/sdl2 cmake handling is this: a082f60291110c0110024e89fef521b7c7c48798

@Alexpux The change was made by you. Could you please elaborate on why that change was necessary? It is surely not required by the upstead of SDL2. Is this change and compatibility _break_ really justified for the sake of FAudio which you also maintain? Or was the change necessary for something else?

**Comment by Alexpux** [comment] 2020-04-19 18:37
@klei1984 I’m just change build system from autoconf scripts to cmake. Those build systems generate different cmake files. With autoconf versions of cmake files it not possible to build last FAudio. So probably you will ask SDL2 developers why they generate different files?

**Comment by Alexpux** [comment] 2020-04-19 18:49
@klei1984 also from my point of view cmake files generated by cmake itself is more right choice than cmake files generated by autoconf

**Comment by klei1984** [comment] 2020-04-19 19:19
@Alexpux thanks for the link, I will look into it. I also read somewhere else that this SDL2::SDL2 is the better new approach of cmake, but I was never able to make it work.

**Comment by toomuchsalt** [comment] 2020-06-29 22:24
I'm facing similar issue. After updating my msys2 installation I'm unable to link with sdl2
```cpp
D:\ProgramFiles\Msys2\mingw64\bin\ld: D:\ProgramFiles\Msys2\mingw64\x86_64-w64-mingw32\lib/libmingw32.a(lib64_libmingw32_a-crt0_c.o): in function `main':
D:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

It seems to be somehow connected to `ld`, as using `ld.lld` fixes that problem. 
Though it brings another one, the SDL2::SDL2 target has `--no-undefined` flag set, which is not supported by lld( which is weird, as `ld.lld --help` state it does )

**Comment by mati865** [comment] 2020-07-01 19:52
> which is not supported by lld( which is weird, as ld.lld --help state it does )

`ld.lld` is ELF driver, to get help for MinGW driver use `ld.lld -m i386pep --help`.

**Comment by pyronide** [comment] 2021-04-27 08:54
> I'm facing similar issue. After updating my msys2 installation I'm unable to link with sdl2
> 
> ```c++
> D:\ProgramFiles\Msys2\mingw64\bin\ld: D:\ProgramFiles\Msys2\mingw64\x86_64-w64-mingw32\lib/libmingw32.a(lib64_libmingw32_a-crt0_c.o): in function `main':
> D:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain'
> clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> It seems to be somehow connected to `ld`, as using `ld.lld` fixes that problem.
> Though it brings another one, the SDL2::SDL2 target has `--no-undefined` flag set, which is not supported by lld( which is weird, as `ld.lld --help` state it does )

@toomuchsalt I was able to solve this by adding the following line after my `target_link_libraries(...)` line:
```add_definitions(-DSDL_MAIN_HANDLED)```

**Comment by Clownacy** [comment] 2022-02-02 13:26
I was able to fix this in my project without disabling SDL2's WinMain shim by manually including `mingw32` before SDL2:

```cmake
# Link SDL2
target_link_libraries(clownmdemufrontend mingw32)
find_package(SDL2)
if(SDL2_FOUND)
	target_link_libraries(clownmdemufrontend SDL2::SDL2main SDL2::SDL2)
else()
	add_subdirectory("libraries/SDL" EXCLUDE_FROM_ALL)
	target_link_libraries(clownmdemufrontend SDL2::SDL2main SDL2::SDL2-static)
endif()
```
`main` is defined by libmingw32, which depends on `WinMain`, which is defined by SDL2main, which depends on `SDL_main`, which is defined by your program (SDL2 uses a `#define` to change your `main` to `SDL_main`), so it seems there's some kind of dependency chaos going on there. Linking libmingw32 before SDL2main resolves this somehow.

**Comment by HunterZ** [comment] 2022-03-11 23:57
I've run into this too. Is there some way to solve this on the package end by tweaking the libsdl2 CMake imports?

Anyway, here is my own workaround, which tries to keep things cross-platform by only adding `mingw32` to the linker list only when `MINGW` is automatically defined by CMake:
```cmake
cmake_minimum_required(VERSION 3.22)
project(test)

find_package(SDL2 REQUIRED)

add_executable(${PROJECT_NAME} test.cpp)
target_link_libraries(${PROJECT_NAME}
  $<$<BOOL:${MINGW}>:mingw32>
  SDL2::SDL2main
  SDL2::SDL2
)
```

**Comment by MehdiChinoune** [comment] 2024-02-09 18:57
likely to be fixed

**Closed by MehdiChinoune** 2024-02-09 18:57 UTC
