### ISSUE TITLE
mingw-w64-x86_64-openssl-3.0.8-1 cannot load legacy provider (missing path translation)

### ISSUE THREAD

**Issue by stefantalpalaru** [msys2/MINGW-packages#16129] opened 2023-03-10 02:07 UTC
### Description / Steps to reproduce the issue

In order to use legacy ciphers like RC4 with OpenSSL 3 - something that BitTorrent clients like Transmission have to do - one needs to programmatically load the "Legacy" provider, as described here: https://github.com/openssl/openssl/blob/master/README-PROVIDERS.md#loading-providers

That is done by loading a DLL from a build-time configured directory. The OpenSSL PKGBUILD makes sure that MODULESDIR remains a POSIX path: https://github.com/msys2/MINGW-packages/blob/e23c607ddcb552895d09c4a8f25f184181f77b9b/mingw-w64-openssl/PKGBUILD#L101

Unfortunately, that POSIX path is fed up directly to `LoadLibraryW()`, not giving us the chance to translate it back to a Windows path: https://github.com/openssl/openssl/blob/31157bc0b46e04227b8468d3e6915e4d0332777c/crypto/dso/dso_win32.c#L54

This results in an OpenSSL error: "DSO support routines::could not load the shared library".

The workaround is to `export OPENSSL_MODULES='C:\msys64\mingw64\lib\ossl-modules'` which overrides the build-time variable.

A proper fix would probably be to patch "Configurations/10-main.conf", in the "mingw-common" section and change "dso_scheme" from "win32" to "dlfcn", in order to use `dlopen()` instead of `LoadLibrary()`: https://github.com/openssl/openssl/blob/31157bc0b46e04227b8468d3e6915e4d0332777c/Configurations/10-main.conf#L1497

"mingw-w64-libltdl" will probably be added as an OpenSSL package dependency.

### Expected behavior

I expect encrypted connections to work in Transmission and its test suite to pass.

### Actual behavior

They do not and it does not.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment] 2023-03-10 04:10
Please provide the steps or minimal sample code to reproduce the issue.

**Comment by lazka** [comment] 2023-03-10 07:12
In theory this should be fixed since https://github.com/msys2/MINGW-packages/commit/ff2cb0b7167a8f5de06b7535fb77de1493718e69

**Comment by stefantalpalaru** [comment] 2023-03-10 13:41
> Please provide the steps

Just run `make test` for Transmission and see `crypto-test` fail, because of what I just described.

> In theory this should be fixed

It only works for the `openssl` binary itself, because of that relative DLL path that `LoadLibraryW()` appends to its regular search paths (the first of which is the binary's own dir):

"If a relative path is specified, the entire relative path is appended to every token in the DLL search path list." - https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryw

To make it work for other binaries, like those from Transmission, your `modulesdir_relocation()` needs to output an absolute path.

**Comment by stefantalpalaru** [comment] 2023-03-10 14:28
> would using `get_dll_path` instead of `get_executable_path` maybe do the trick?

No, we need an absolute path in there.

**Comment by stefantalpalaru** [comment] 2023-03-10 17:33
Here's a short example program, for reproducing:

```c
// gcc openssl_legacy_provider.c -lcrypto -lssl -o openssl_legacy_provider

#include <stdio.h>
#include <stdlib.h>
#include <openssl/provider.h>


int main() {
        OSSL_PROVIDER *legacy, *deflt;

        legacy = OSSL_PROVIDER_load(NULL, "legacy");
        if (legacy == NULL) {
            printf("OpenSSL error: failed to load 'legacy' provider.\n");
            exit(EXIT_FAILURE);
        }

        deflt = OSSL_PROVIDER_load(NULL, "default");
        if (deflt == NULL) {
            printf("OpenSSL error: failed to load 'default' provider.\n");
            exit(EXIT_FAILURE);
        }

	printf("'legacy' and 'default' OpenSSL providers loaded.");

	return 0;
}
```

```sh
user@windows10 MINGW64 /c/Users/user/Desktop/devel
$ gcc openssl_legacy_provider.c -lcrypto -lssl -o openssl_legacy_provider

user@windows10 MINGW64 /c/Users/user/Desktop/devel
$ ./openssl_legacy_provider.exe
OpenSSL error: failed to load 'legacy' provider.

user@windows10 MINGW64 /c/Users/user/Desktop/devel
$ OPENSSL_MODULES='C:\msys64\mingw64\lib\ossl-modules' ./openssl_legacy_provider.exe
'legacy' and 'default' OpenSSL providers loaded.
```

**Comment by lazka** [comment] 2023-03-10 20:56
See https://github.com/msys2/MINGW-packages/pull/16141

**Closed** 2023-03-11 09:56 UTC
Labels: bug
