### ISSUE TITLE
SDL2 CMake config is broken

### ISSUE THREAD

**Issue by dhrdlicka** [msys2/MINGW-packages#6348] opened 2020-04-04 13:32 UTC
I am including SDL2 in my `CMakeLists.txt` file like this:
```cmake
find_package(SDL2 CONFIG REQUIRED)
target_link_libraries(test PRIVATE SDL2::SDL2)
```

However, that fails with the following error:
```
CMake Error in src/CMakeLists.txt:
  Imported target "SDL2::SDL2" includes non-existent path

    "/mingw32/include/SDL2"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

This is the same kind of issue as #5660.

Furthermore, the `SDL2::SDL2` target imports `libSDL2.so` for some reason, while I suppose it should be importing `libSDL2.dll.a`.

**Comment by stahta01** [comment] 2020-04-06 01:13
If you can give cmake newbie directions to duplicate the problem, I can see if I can find the cause.
And, hopefully a package fix.

Tim S.

**Comment by Alexpux** [comment] 2020-04-11 15:48
Fixed by https://github.com/msys2/MINGW-packages/commit/a082f60291110c0110024e89fef521b7c7c48798

**Closed by Alexpux** 2020-04-11 15:48 UTC
