### ISSUE TITLE
[ecppack] Mingw-w64 runtime failure: 32 bit pseudo relocation (...) out of range

### ISSUE THREAD

**Issue by umarcor** [msys2/MINGW-packages#10547] opened 2022-01-14 12:22 UTC
Binary `ecppack.exe` from [mingw-w64-prjtrellis](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-prjtrellis/PKGBUILD) is crashing on MINGW64 and UCRT64:

```
# ecppack
Mingw-w64 runtime failure:
32 bit pseudo relocation at 00007FF6E40F66A1 out of range, targeting 00007FFAB9EEDA10, yielding the value 00000003D5DF736B.
```

I'm confused about the 32 bit relocation issue, because both MINGW64 and UCRT64 are expected to be 64 bit environments.

Ref: stnolting/neorv32-setups#11

**Comment by Biswa96** [comment] 2022-01-14 13:15
The program is crashing in do_pseudo_reloc function, before main function is called. The error output comes from mingw-w64-crt, here https://github.com/mingw-w64/mingw-w64/blob/master/mingw-w64-crt/crt/pseudo-reloc.c

**Comment by umarcor** [comment] 2022-01-14 13:59
Yes. It was working for months, and it was broken during the last month.

- A successful run last month: https://github.com/stnolting/neorv32/actions/runs/1561230285
- Builds were broken because nextpnr was missing a dependency: https://github.com/stnolting/neorv32/actions/runs/1589974764
- That was fixed in #10505.
- Since then, ecppack is crashing: https://github.com/stnolting/neorv32/actions/runs/1665427560 (see jobs OrangeCrab or ULX3S)

**Comment by Biswa96** [comment] 2022-01-14 15:05
If I remove `-DCMAKE_C_COMPILER=clang` and `-DCMAKE_CXX_COMPILER=clang++` options from PKGBUILD file the program works fine in ucrt.

**Comment by mstorsjo** [comment] 2022-01-14 16:19
To debug this, I'd need to pinpoint exactly which symbol reference, where, in what generated code, is causing this. And that's a bit nontrivial.

To do that, I would need an unstripped exe that is showing this issue, ideally together with all the object files that are input to linking it, plus the corresponding error message (with the fault addresses that are printed in the message for that exact binary).

To clarify the issue, "32 bit pseudo relocation" doesn't mean that it is a 32 bit executable. But at the assembly/instruction levels, some instructions refer to other symbols in the address space, and even if the address space is 64 bit, there can be references in the form of a 32 bit offset added on top of the current address. If one instruction is referencing a symbol that at runtime turns out to be too far away for what you can describe with 32 bits (the DLL that is imported happens to be loaded not exactly next to the referencing EXE/DLL), then you'd get a crash at runtime. This error message tells you flat out that it won't work, instead of getting a crash that is even harder to debug. (But if the problematic codepath is never executed in practice, you might not have encountered it.)

**Comment by mstorsjo** [comment] 2022-01-14 22:07
I managed to pinpoint the issue, but it's quite unobvious. If this library has been built this way before, it has had a latent bug which the recent mingw-w64-crt fix exposes clearly on startup.

The root cause of the issue is an issue in how clang sets flags on functions in the generated code, combined with how ld.bfd determines the difference between functions and data in the list of exported symbols.

In one of the source files built, there's two symbols generated, `_ZN7Trellis8BitGroupC2Ev` and `_ZN7Trellis8BitGroupC1Ev` (only difference is 2 vs 1). Both symbols demangle into the same, `Trellis::BitGroup::BitGroup()`. I'm not offhand familiar with what the actual difference between the two symbols are.

In practice here, Clang generates the code for this function, and decides to produce one function but set both symbols to point at the same data. For each symbol/function, the compiler can set some flags indicating what kind of symbol it is.

In this case, for the BitDatabase.cpp file, Clang produces the following assembly:

```
        .def     _ZN7Trellis8BitGroupC2Ev;
        .scl    2;
        .type   32;
        .endef
        .text
        .globl  _ZN7Trellis8BitGroupC2Ev        # -- Begin function _ZN7Trellis8BitGroupC2Ev
        .p2align        4, 0x90
_ZN7Trellis8BitGroupC2Ev:               # @_ZN7Trellis8BitGroupC2Ev
# %bb.0:
        leaq    8(%rcx), %rax
        movl    $0, 8(%rcx)
        movq    $0, 16(%rcx)
        movq    %rax, 24(%rcx)
        movq    %rax, 32(%rcx)
        movq    $0, 40(%rcx)
        retq
                                        # -- End function

[... at the end of the output ...]

        .globl  _ZN7Trellis8BitGroupC1Ev
.set _ZN7Trellis8BitGroupC1Ev, _ZN7Trellis8BitGroupC2Ev
```

This means it generates a function `_ZN7Trellis8BitGroupC2Ev` and sets `.scl 2; .type 32;` for it. Then it defines a symbol `_ZN7Trellis8BitGroupC1Ev` as an alias pointing at the same as `_ZN7Trellis8BitGroupC2Ev`, but doesn't set any flags for this symbol.

If compiling the same source file with GCC instead, it produces this output assembly:
```
        .align 2
        .p2align 4
        .globl  _ZN7Trellis8BitGroupC2Ev
        .def    _ZN7Trellis8BitGroupC2Ev;       .scl    2;      .type   32;     .endef
        .seh_proc       _ZN7Trellis8BitGroupC2Ev
_ZN7Trellis8BitGroupC2Ev:
.LFB16700:
        .seh_endprologue
        leaq    8(%rcx), %rax
        movl    $0, 8(%rcx)
        movq    $0, 16(%rcx)
        movq    %rax, 24(%rcx)
        movq    %rax, 32(%rcx)
        movq    $0, 40(%rcx)
        ret
        .seh_endproc
        .globl  _ZN7Trellis8BitGroupC1Ev
        .def    _ZN7Trellis8BitGroupC1Ev;       .scl    2;      .type   32;     .endef
        .set    _ZN7Trellis8BitGroupC1Ev,_ZN7Trellis8BitGroupC2Ev
```

This does almost identically the same, but also sets the same `.scl 2; .type 32;` flags on the second symbol, which Clang is missing.

If inspecting the generated object files with `obj2yaml`, the GCC generated object file contains this:
```
  - Name:            _ZN7Trellis8BitGroupC1Ev
    Value:           10496
    SectionNumber:   1
    SimpleType:      IMAGE_SYM_TYPE_NULL
    ComplexType:     IMAGE_SYM_DTYPE_FUNCTION
    StorageClass:    IMAGE_SYM_CLASS_EXTERNAL
```
while the Clang generated object file contains this:
```
  - Name:            _ZN7Trellis8BitGroupC1Ev
    Value:           608
    SectionNumber:   1
    SimpleType:      IMAGE_SYM_TYPE_NULL
    ComplexType:     IMAGE_SYM_DTYPE_NULL
    StorageClass:    IMAGE_SYM_CLASS_EXTERNAL
```

Now when deciding what symbols to to export, and how, LLD looks at what kind of section (code or data) the symbols points at, and would realize that both symbols point at code, and would export both symbols as functions (not data). GNU ld on the other hand seems to use the symbol type (`IMAGE_SYM_DTYPE_FUNCTION` vs `IMAGE_SYM_DTYPE_NULL` here).

When GNU ld doesn't export `_ZN7Trellis8BitGroupC1Ev` as a function but as data, at link time, there's no thunk, but the linker ends up autoimporting and creating a runtime pseudo relocation for it instead. When the code tries to call `_ZN7Trellis8BitGroupC1Ev` (which doesn't use any dllimport annotation), it's expecting to reach that symbol with a 32 bit offset from the current position in code. The runtime pseudo relocation mechanism would try to fix that at runtime. But if the target function in another DLL ends up loaded too far away, it's impossible to fix, which is what the mingw-w64-crt error warns about.

Thus if Clang would generate the same kind of symbol type on aliased functions, this would work out, or if one would use LLD instead of ld.bfd, it would also happen to work. Or if compiling with GCC instead of Clang in this case.

**Comment by Biswa96** [comment] 2022-01-15 05:09
How did you determine that specific function or symbol? 🤯

**Comment by mstorsjo** [comment] 2022-01-15 23:03
> How did you determine that specific function or symbol? 🤯

I first looked at the build directory output and the command you sent, and realized that the binaries had a default load address of 0x0140000000, while the problematic relocation was at 0x07FF73BFF24D6 (due to being linked with the dynamicbase flag I would guess). So it's impossible to know exactly what those addresses mean in the image, and which other DLL it references.

So just looking at prebuilt executables/object files wasn't going to be enough in this case. To have a fully debuggable setup with all intermediate files available, I built the package with pkgbuild.

So to determine the actual address/offset in the loaded exe/dll, I had to know where all dlls and the main exe are loaded in the case when the error is reported. I tried with gdb, but it seemed like it exited on the error before I could inspect the memory layout. (I guess it could have been possible to set a breakpoint at the right place in pseudo-reloc.c too. Or extend the code in psuedo-reloc.c to iterate over all loaded dlls and print their name+load address.) But I used WinDbg where it was possible to check the memory layout after hitting the error, I googled that the WinDbg command `lm` prints what I needed to know. (There might have been other equally convenient ways of doing this too.)

With the error like `relocation at 00007FF753986911 out of range, targeting 00007FFB72CCDA10`, I looked at what exe/dll each of the addresses belonged to. The former was part of ecppack.exe (loaded at `00007ff753970000` and the latter was part of libtrellis.dll, loaded at `00007ffb72cb0000`. I then subtracted the exe/dll load address from the addresses printed, yielding `relocation at ecppack.exe + 0x16911, targeting libtrellis.dll + 0x1DA10`.

For libtrellis.dll, I used `llvm-readobj --coff-exports libtrellis.dll`, where I found this:
```
Export {
  Ordinal: 236
  Name: _ZN7Trellis8BitGroupC1Ev
  RVA: 0x1DA10
}
[...]
Export {
  Ordinal: 238
  Name: _ZN7Trellis8BitGroupC2Ev
  RVA: 0x1DA10
}
```
(This is certainly doable with other tools as well, I guess GNU objdump provides the same info somewhere too.)

Then for the relocation location, I disassembled the main binary ecppack.exe with `llvm-objdump -d ecppack.exe` (the corresponding GNU objdump probably would have worked just as well). In the output, I would search for the address 0x16911 + base 0x140000000 = 0x140016911. But as this might not be at the start of an instruction, and as it's unnecessary to search for the full string, I searched with the regex `1691.:`, which found this instruction:
```
140016910: e8 13 c3 00 00               callq   0x140022c28 <__imp__ZN7Trellis8BitGroupC1Ev>
```
(After the autoimport linker adjustments, it now points at `__imp__ZN7Trellis8BitGroupC1Ev` while it originally pointed at `_ZN7Trellis8BitGroupC1Ev` in the object file.) By running `c++filt _ZN7Trellis8BitGroupC1Ev` I learn that this corresponds to `Trellis::BitGroup::BitGroup()`. This instruction is the call instruction which at address 0x140016911, one byte into the instruction, encodes a 32 bit relative offset, which the runtime pseudo relocs would try to fix up to point at the real `_ZN7Trellis8BitGroupC1Ev`, which turned out to be too far away.)

By scrolling up around that spot, it seemed that this reference was in the function `_ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_N7Trellis8BitGroupEESt10_Select1stISA_ESt4lessIS5_ESaISA_EE17_M_construct_nodeIJRKSt21piecewise_construct_tSt5tupleIJOS5_EESL_IJEEEEEvPSt13_Rb_tree_nodeISA_EDpOT_`. Running c++filt on that gives a huge c++ template expansion; I'm not going to try to find that as such.

But I just ran a `grep -r _ZN7Trellis8BitGroupC1Ev *` in the build tree, which gave a couple of matches, among others pointing out BitDatabase.cpp.obj (which defines it) and ecppack.cpp.obj (which references it).

The symbol `Trellis::BitGroup::BitGroup()` is a function, so it should be fine to call it without dllimport, as there should be a normal thunk if it is marked as a function as it should. By looking at `llvm-nm libtrellis.dll.a`, I find this:
```

d000307.o:
00000000 i .idata$4
00000000 i .idata$5
00000000 i .idata$6
00000000 i .idata$7
00000000 t .text
00000000 I __imp__ZN7Trellis8BitGroupC1Ev
00000000 I __nm__ZN7Trellis8BitGroupC1Ev
         U _head_libtrellis_dll
```
As this has the `__imp_<name>` symbol but no corresponding `<name>` symbol, it looks like a data symbol in the import library.

Just to be sure, I rerun the linking command manually (I touch a file and rerun the build with `make VERBOSE=1`, copypaste the linking command and rerun it manually by appending `-Wl,--output-def,libtrellis.def`) and inspecting the generated libtrellis.def. There I see this:
```
    _ZN7Trellis8BitGroupC1Ev @236 DATA
    _ZN7Trellis8BitGroupC2ERKSt6vectorINS_10ChangedBitESaIS2_EE @237
    _ZN7Trellis8BitGroupC2Ev @238
```
So loud and clear, the linker does consider `_ZN7Trellis8BitGroupC1Ev` a data symbol while `_ZN7Trellis8BitGroupC2Ev` isn't.

I reran the build command for building BitDatabase.cpp.obj which defines those symbols, then changed `-c -o .../BitDatabase.cpp.obj` into `-S -o -` to make it produce assembly, to look at what the compiler generated. There I saw the function type markings (`.def ... .scl ; .type; .endef`) for one symbol but not for the other. Then I reran the same command but with g++ instead of clang++, and saw that g++ did produce the function type markings for both.

Finally, I serialized the test file with the compile command, but plugged in `-E -P -o bitdatabase-preproc.cpp`, which makes a standalone file that can be compiled anywhere. I ran that file with creduce, with criteria to keep the `.set _ZN7Trellis8BitGroupC1Ev, _ZN7Trellis8BitGroupC2Ev` but otherwise reduce it. That got me this minimal-ish example that still produces the same kind of function alias for this function:
```
namespace Trellis {
struct BitGroup {
  BitGroup();
};
BitGroup::BitGroup() {}
} // namespace Trellis
```
This is an example that can be used when experimenting with clang, trying to make it produce the right kind function type annotation on the function alias too.

**Comment by mstorsjo** [comment] 2022-01-27 09:02
FYI, I posted an initial attempt at fixing this in Clang at https://reviews.llvm.org/D118328.

**Comment by mikucionisaau** [comment] 2022-02-02 07:56
Hi, I ran into the similar (same?) issue `"Mingw-w64 runtime failure:
32 bit pseudo relocation at 00007FF6D51E65F0 out of range, targeting 00007FFCD6186920, yielding the value 0000000600FA03
2C."` when working with TBB (multithreading environment).
I then added `add_compile_options(-femulated-tls)` which was part of workaround for the issue #5786, and it worked. So maybe this is related.

**Comment by mati865** [comment] 2023-12-20 18:39
Fixed upstream.

**Closed by mati865** 2023-12-20 18:39 UTC
Labels: bug
