### ISSUE TITLE
CLANG64 output is not highlighted

### ISSUE THREAD

**Issue by iahung** [msys2/MINGW-packages#15565] opened 2023-02-08 19:21 UTC
UCRT64 output is highlighted properly. You fixed this bug for GCC but now it's CLANG.

https://github.com/msys2/MINGW-packages/issues/14087

**Comment by Biswa96** [comment] 2023-02-08 19:23
Duplicate of https://github.com/msys2/MINGW-packages/issues/2988

**Closed by Biswa96** 2023-02-08 19:23 UTC
