### ISSUE TITLE
TexLive groups won't successfully install

### ISSUE THREAD

**Issue by emiellr** [msys2/MINGW-packages#20708] opened 2024-04-23 11:21 UTC
### Description / Steps to reproduce the issue

Any attempt to install a *texlive-full package will result in failure.
```pacman -S mingw-w64-ucrt-x86_64-texlive-full```
results in:
```(36/36) reinstalling mingw-w64-ucrt-x86_64-texlive-science                                                          [#####################################################################] 100%
:: Running post-transaction hooks...
(1/4) Updating fontconfig cache...
(2/4) Updating TeXLive filename database...
>>> Running mktexlsr
>>> Running mtxrun (this might take a while)
PANIC: unprotected error in call to Lua API (zlib library version does not match - header: 1.3, library: 1.3.1)
/
grep: /ucrt64/var/lib/texmf/luatex-cache/context/*/trees/*.lua: No such file or directory
(3/4) Updating TeXLive format files...
>>> Running fmtutil (this might take a while)
PANIC: unprotected error in call to Lua API (zlib library version does not match - header: 1.3, library: 1.3.1)
error: command (/usr/share/libalpm/scripts/mingw-w64-ucrt-x86_64-texlive-fmtutil.script /usr/share/libalpm/scripts/mingw-w64-ucrt-x86_64-texlive-fmtutil.script ) failed to execute correctly
(4/4) Updating TeXLive font maps...
>>> Running updmap (this might take a while)
PANIC: unprotected error in call to Lua API (zlib library version does not match - header: 1.3, library: 1.3.1)
error: command (/usr/share/libalpm/scripts/mingw-w64-ucrt-x86_64-texlive-updmap.script /usr/share/libalpm/scripts/mingw-w64-ucrt-x86_64-texlive-updmap.script ) failed to execute correctly
```

### Expected behavior

Any *texlive-full package should install without zlib version mismatches.

### Actual behavior

Postinstall scripts will fail, possibly due to zlib mismatch (v1.3.1 instead of v1.3). This happens for mingw-w64, ucrt and clang64.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Unfortunately no, I have too much other stuff going on...

**Comment by Biswa96** [comment] 2024-04-23 12:48
Duplicate of #19981

**Closed by Biswa96** 2024-04-23 12:48 UTC
Labels: bug
